// Generated by kea-typegen on Sun, 10 May 2026 16:57:43 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { ScreenerQuestion, ScreenerQuestionType } from './screenerLogic'

export interface screenerLogicType extends Logic {
    actionCreators: {
        loadQuestions: (questions: ScreenerQuestion[]) => ({
            type: "load questions (features.studies.tabs.screener.screenerLogic)";
            payload: {
                questions: ScreenerQuestion[];
            };
        });
        addQuestion: (type?: ScreenerQuestionType) => ({
            type: "add question (features.studies.tabs.screener.screenerLogic)";
            payload: {
                type: ScreenerQuestionType;
            };
        });
        removeQuestion: (id: string) => ({
            type: "remove question (features.studies.tabs.screener.screenerLogic)";
            payload: {
                id: string;
            };
        });
        updateText: (id: string, text: string) => ({
            type: "update text (features.studies.tabs.screener.screenerLogic)";
            payload: {
                id: string;
                text: string;
            };
        });
        setType: (id: string, type: ScreenerQuestionType) => ({
            type: "set type (features.studies.tabs.screener.screenerLogic)";
            payload: {
                id: string;
                type: ScreenerQuestionType;
            };
        });
        toggleRequired: (id: string) => ({
            type: "toggle required (features.studies.tabs.screener.screenerLogic)";
            payload: {
                id: string;
            };
        });
        moveQuestion: (from: number, to: number) => ({
            type: "move question (features.studies.tabs.screener.screenerLogic)";
            payload: {
                from: number;
                to: number;
            };
        });
        setOptions: (id: string, options: string[]) => ({
            type: "set options (features.studies.tabs.screener.screenerLogic)";
            payload: {
                id: string;
                options: string[];
            };
        });
        togglePassOption: (id: string, optionIndex: number) => ({
            type: "toggle pass option (features.studies.tabs.screener.screenerLogic)";
            payload: {
                id: string;
                optionIndex: number;
            };
        });
        loadScreener: () => ({
            type: "load screener (features.studies.tabs.screener.screenerLogic)";
            payload: any;
        });
        loadScreenerSuccess: (loadedScreener: {
            id: string;
        } | null, payload?: any) => ({
            type: "load screener success (features.studies.tabs.screener.screenerLogic)";
            payload: {
                loadedScreener: {
                    id: string;
                } | null;
                payload?: any;
            };
        });
        loadScreenerFailure: (error: string, errorObject?: any) => ({
            type: "load screener failure (features.studies.tabs.screener.screenerLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
        saveScreener: () => ({
            type: "save screener (features.studies.tabs.screener.screenerLogic)";
            payload: any;
        });
        saveScreenerSuccess: (loadedScreener: {
            id: string;
        } | null, payload?: any) => ({
            type: "save screener success (features.studies.tabs.screener.screenerLogic)";
            payload: {
                loadedScreener: {
                    id: string;
                } | null;
                payload?: any;
            };
        });
        saveScreenerFailure: (error: string, errorObject?: any) => ({
            type: "save screener failure (features.studies.tabs.screener.screenerLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
    };
    actionKeys: {
        "load questions (features.studies.tabs.screener.screenerLogic)": "loadQuestions";
        "add question (features.studies.tabs.screener.screenerLogic)": "addQuestion";
        "remove question (features.studies.tabs.screener.screenerLogic)": "removeQuestion";
        "update text (features.studies.tabs.screener.screenerLogic)": "updateText";
        "set type (features.studies.tabs.screener.screenerLogic)": "setType";
        "toggle required (features.studies.tabs.screener.screenerLogic)": "toggleRequired";
        "move question (features.studies.tabs.screener.screenerLogic)": "moveQuestion";
        "set options (features.studies.tabs.screener.screenerLogic)": "setOptions";
        "toggle pass option (features.studies.tabs.screener.screenerLogic)": "togglePassOption";
        "load screener (features.studies.tabs.screener.screenerLogic)": "loadScreener";
        "load screener success (features.studies.tabs.screener.screenerLogic)": "loadScreenerSuccess";
        "load screener failure (features.studies.tabs.screener.screenerLogic)": "loadScreenerFailure";
        "save screener (features.studies.tabs.screener.screenerLogic)": "saveScreener";
        "save screener success (features.studies.tabs.screener.screenerLogic)": "saveScreenerSuccess";
        "save screener failure (features.studies.tabs.screener.screenerLogic)": "saveScreenerFailure";
    };
    actionTypes: {
        loadQuestions: "load questions (features.studies.tabs.screener.screenerLogic)";
        addQuestion: "add question (features.studies.tabs.screener.screenerLogic)";
        removeQuestion: "remove question (features.studies.tabs.screener.screenerLogic)";
        updateText: "update text (features.studies.tabs.screener.screenerLogic)";
        setType: "set type (features.studies.tabs.screener.screenerLogic)";
        toggleRequired: "toggle required (features.studies.tabs.screener.screenerLogic)";
        moveQuestion: "move question (features.studies.tabs.screener.screenerLogic)";
        setOptions: "set options (features.studies.tabs.screener.screenerLogic)";
        togglePassOption: "toggle pass option (features.studies.tabs.screener.screenerLogic)";
        loadScreener: "load screener (features.studies.tabs.screener.screenerLogic)";
        loadScreenerSuccess: "load screener success (features.studies.tabs.screener.screenerLogic)";
        loadScreenerFailure: "load screener failure (features.studies.tabs.screener.screenerLogic)";
        saveScreener: "save screener (features.studies.tabs.screener.screenerLogic)";
        saveScreenerSuccess: "save screener success (features.studies.tabs.screener.screenerLogic)";
        saveScreenerFailure: "save screener failure (features.studies.tabs.screener.screenerLogic)";
    };
    actions: {
        loadQuestions: (questions: ScreenerQuestion[]) => void;
        addQuestion: (type?: ScreenerQuestionType) => void;
        removeQuestion: (id: string) => void;
        updateText: (id: string, text: string) => void;
        setType: (id: string, type: ScreenerQuestionType) => void;
        toggleRequired: (id: string) => void;
        moveQuestion: (from: number, to: number) => void;
        setOptions: (id: string, options: string[]) => void;
        togglePassOption: (id: string, optionIndex: number) => void;
        loadScreener: () => void;
        loadScreenerSuccess: (loadedScreener: {
            id: string;
        } | null, payload?: any) => void;
        loadScreenerFailure: (error: string, errorObject?: any) => void;
        saveScreener: () => void;
        saveScreenerSuccess: (loadedScreener: {
            id: string;
        } | null, payload?: any) => void;
        saveScreenerFailure: (error: string, errorObject?: any) => void;
    };
    asyncActions: {
        loadQuestions: (questions: ScreenerQuestion[]) => Promise<any>;
        addQuestion: (type?: ScreenerQuestionType) => Promise<any>;
        removeQuestion: (id: string) => Promise<any>;
        updateText: (id: string, text: string) => Promise<any>;
        setType: (id: string, type: ScreenerQuestionType) => Promise<any>;
        toggleRequired: (id: string) => Promise<any>;
        moveQuestion: (from: number, to: number) => Promise<any>;
        setOptions: (id: string, options: string[]) => Promise<any>;
        togglePassOption: (id: string, optionIndex: number) => Promise<any>;
        loadScreener: () => Promise<any>;
        loadScreenerSuccess: (loadedScreener: {
            id: string;
        } | null, payload?: any) => Promise<any>;
        loadScreenerFailure: (error: string, errorObject?: any) => Promise<any>;
        saveScreener: () => Promise<any>;
        saveScreenerSuccess: (loadedScreener: {
            id: string;
        } | null, payload?: any) => Promise<any>;
        saveScreenerFailure: (error: string, errorObject?: any) => Promise<any>;
    };
    defaults: {
        questions: ScreenerQuestion[];
        loadedScreener: {
            id: string;
        } | null;
        loadedScreenerLoading: boolean;
    };
    events: {};
    key: undefined;
    listeners: {
        "loadScreenerSuccess": ((action: {
            type: "load screener success (features.studies.tabs.screener.screenerLogic)";
            payload: {
                loadedScreener: {
                    id: string;
                } | null;
                payload?: any;
            };
        }, previousState: any) => void | Promise<void>)[];
    };
    path: [
        "features",
        "studies",
        "tabs",
        "screener",
        "screenerLogic"
    ];
    pathString: "features.studies.tabs.screener.screenerLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {
        questions: ScreenerQuestion[];
        loadedScreener: {
            id: string;
        } | null;
        loadedScreenerLoading: boolean;
    };
    reducers: {
        questions: (state: ScreenerQuestion[], action: any, fullState: any) => ScreenerQuestion[];
        loadedScreener: (state: {
            id: string;
        } | null, action: any, fullState: any) => {
            id: string;
        } | null;
        loadedScreenerLoading: (state: boolean, action: any, fullState: any) => boolean;
    };
    selector: (state: any) => {
        questions: ScreenerQuestion[];
        loadedScreener: {
            id: string;
        } | null;
        loadedScreenerLoading: boolean;
    };
    selectors: {
        questions: (state: any, props?: any) => ScreenerQuestion[];
        loadedScreener: (state: any, props?: any) => {
            id: string;
        } | null;
        loadedScreenerLoading: (state: any, props?: any) => boolean;
        studyId: (state: any, props?: any) => string | null;
    };
    sharedListeners: {};
    values: {
        questions: ScreenerQuestion[];
        loadedScreener: {
            id: string;
        } | null;
        loadedScreenerLoading: boolean;
        studyId: string | null;
    };
    _isKea: true;
    _isKeaWithKey: false;
}