// Generated by kea-typegen on Sun, 10 May 2026 16:52:04 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { ParticipantContext, ParticipantStep, ScreenerQuestion } from './participantEntryLogic'

export interface participantEntryLogicType extends Logic {
    actionCreators: {
        setSlug: (slug: string) => ({
            type: "set slug (features.participant.participantEntryLogic)";
            payload: {
                slug: string;
            };
        });
        submitConsent: () => ({
            type: "submit consent (features.participant.participantEntryLogic)";
            payload: {
                value: true;
            };
        });
        submitScreener: (answers: Record<string, unknown>) => ({
            type: "submit screener (features.participant.participantEntryLogic)";
            payload: {
                answers: Record<string, unknown>;
            };
        });
        startSession: () => ({
            type: "start session (features.participant.participantEntryLogic)";
            payload: {
                value: true;
            };
        });
        loadContext: () => ({
            type: "load context (features.participant.participantEntryLogic)";
            payload: any;
        });
        loadContextSuccess: (context: ParticipantContext, payload?: any) => ({
            type: "load context success (features.participant.participantEntryLogic)";
            payload: {
                context: ParticipantContext;
                payload?: any;
            };
        });
        loadContextFailure: (error: string, errorObject?: any) => ({
            type: "load context failure (features.participant.participantEntryLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
        setNextStep: (step: ParticipantStep) => ({
            type: "set next step (features.participant.participantEntryLogic)";
            payload: ParticipantStep;
        });
        setNextStepSuccess: (nextStep: ParticipantStep, payload?: ParticipantStep) => ({
            type: "set next step success (features.participant.participantEntryLogic)";
            payload: {
                nextStep: ParticipantStep;
                payload?: ParticipantStep;
            };
        });
        setNextStepFailure: (error: string, errorObject?: any) => ({
            type: "set next step failure (features.participant.participantEntryLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
        loadScreener: () => ({
            type: "load screener (features.participant.participantEntryLogic)";
            payload: any;
        });
        loadScreenerSuccess: (screenerQuestions: ScreenerQuestion[], payload?: any) => ({
            type: "load screener success (features.participant.participantEntryLogic)";
            payload: {
                screenerQuestions: ScreenerQuestion[];
                payload?: any;
            };
        });
        loadScreenerFailure: (error: string, errorObject?: any) => ({
            type: "load screener failure (features.participant.participantEntryLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
    };
    actionKeys: {
        "set slug (features.participant.participantEntryLogic)": "setSlug";
        "submit consent (features.participant.participantEntryLogic)": "submitConsent";
        "submit screener (features.participant.participantEntryLogic)": "submitScreener";
        "start session (features.participant.participantEntryLogic)": "startSession";
        "load context (features.participant.participantEntryLogic)": "loadContext";
        "load context success (features.participant.participantEntryLogic)": "loadContextSuccess";
        "load context failure (features.participant.participantEntryLogic)": "loadContextFailure";
        "set next step (features.participant.participantEntryLogic)": "setNextStep";
        "set next step success (features.participant.participantEntryLogic)": "setNextStepSuccess";
        "set next step failure (features.participant.participantEntryLogic)": "setNextStepFailure";
        "load screener (features.participant.participantEntryLogic)": "loadScreener";
        "load screener success (features.participant.participantEntryLogic)": "loadScreenerSuccess";
        "load screener failure (features.participant.participantEntryLogic)": "loadScreenerFailure";
    };
    actionTypes: {
        setSlug: "set slug (features.participant.participantEntryLogic)";
        submitConsent: "submit consent (features.participant.participantEntryLogic)";
        submitScreener: "submit screener (features.participant.participantEntryLogic)";
        startSession: "start session (features.participant.participantEntryLogic)";
        loadContext: "load context (features.participant.participantEntryLogic)";
        loadContextSuccess: "load context success (features.participant.participantEntryLogic)";
        loadContextFailure: "load context failure (features.participant.participantEntryLogic)";
        setNextStep: "set next step (features.participant.participantEntryLogic)";
        setNextStepSuccess: "set next step success (features.participant.participantEntryLogic)";
        setNextStepFailure: "set next step failure (features.participant.participantEntryLogic)";
        loadScreener: "load screener (features.participant.participantEntryLogic)";
        loadScreenerSuccess: "load screener success (features.participant.participantEntryLogic)";
        loadScreenerFailure: "load screener failure (features.participant.participantEntryLogic)";
    };
    actions: {
        setSlug: (slug: string) => void;
        submitConsent: () => void;
        submitScreener: (answers: Record<string, unknown>) => void;
        startSession: () => void;
        loadContext: () => void;
        loadContextSuccess: (context: ParticipantContext, payload?: any) => void;
        loadContextFailure: (error: string, errorObject?: any) => void;
        setNextStep: (step: ParticipantStep) => void;
        setNextStepSuccess: (nextStep: ParticipantStep, payload?: ParticipantStep) => void;
        setNextStepFailure: (error: string, errorObject?: any) => void;
        loadScreener: () => void;
        loadScreenerSuccess: (screenerQuestions: ScreenerQuestion[], payload?: any) => void;
        loadScreenerFailure: (error: string, errorObject?: any) => void;
    };
    asyncActions: {
        setSlug: (slug: string) => Promise<any>;
        submitConsent: () => Promise<any>;
        submitScreener: (answers: Record<string, unknown>) => Promise<any>;
        startSession: () => Promise<any>;
        loadContext: () => Promise<any>;
        loadContextSuccess: (context: ParticipantContext, payload?: any) => Promise<any>;
        loadContextFailure: (error: string, errorObject?: any) => Promise<any>;
        setNextStep: (step: ParticipantStep) => Promise<any>;
        setNextStepSuccess: (nextStep: ParticipantStep, payload?: ParticipantStep) => Promise<any>;
        setNextStepFailure: (error: string, errorObject?: any) => Promise<any>;
        loadScreener: () => Promise<any>;
        loadScreenerSuccess: (screenerQuestions: ScreenerQuestion[], payload?: any) => Promise<any>;
        loadScreenerFailure: (error: string, errorObject?: any) => Promise<any>;
    };
    defaults: {
        slug: string;
        errorCode: string | null;
        context: ParticipantContext | null;
        contextLoading: boolean;
        nextStep: ParticipantStep;
        nextStepLoading: boolean;
        screenerQuestions: ScreenerQuestion[];
        screenerQuestionsLoading: boolean;
    };
    events: {};
    key: undefined;
    listeners: {
        "loadContextSuccess": ((action: {
            type: "load context success (features.participant.participantEntryLogic)";
            payload: {
                context: ParticipantContext;
                payload?: any;
            };
        }, previousState: any) => void | Promise<void>)[];
        "loadContextFailure": ((action: {
            type: "load context failure (features.participant.participantEntryLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        }, previousState: any) => void | Promise<void>)[];
        "submitConsent": ((action: {
            type: "submit consent (features.participant.participantEntryLogic)";
            payload: {
                value: true;
            };
        }, previousState: any) => void | Promise<void>)[];
        "submitScreener": ((action: {
            type: "submit screener (features.participant.participantEntryLogic)";
            payload: {
                answers: Record<string, unknown>;
            };
        }, previousState: any) => void | Promise<void>)[];
        "startSession": ((action: {
            type: "start session (features.participant.participantEntryLogic)";
            payload: {
                value: true;
            };
        }, previousState: any) => void | Promise<void>)[];
    };
    path: [
        "features",
        "participant",
        "participantEntryLogic"
    ];
    pathString: "features.participant.participantEntryLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {
        slug: string;
        errorCode: string | null;
        context: ParticipantContext | null;
        contextLoading: boolean;
        nextStep: ParticipantStep;
        nextStepLoading: boolean;
        screenerQuestions: ScreenerQuestion[];
        screenerQuestionsLoading: boolean;
    };
    reducers: {
        slug: (state: string, action: any, fullState: any) => string;
        errorCode: (state: string | null, action: any, fullState: any) => string | null;
        context: (state: ParticipantContext | null, action: any, fullState: any) => ParticipantContext | null;
        contextLoading: (state: boolean, action: any, fullState: any) => boolean;
        nextStep: (state: ParticipantStep, action: any, fullState: any) => ParticipantStep;
        nextStepLoading: (state: boolean, action: any, fullState: any) => boolean;
        screenerQuestions: (state: ScreenerQuestion[], action: any, fullState: any) => ScreenerQuestion[];
        screenerQuestionsLoading: (state: boolean, action: any, fullState: any) => boolean;
    };
    selector: (state: any) => {
        slug: string;
        errorCode: string | null;
        context: ParticipantContext | null;
        contextLoading: boolean;
        nextStep: ParticipantStep;
        nextStepLoading: boolean;
        screenerQuestions: ScreenerQuestion[];
        screenerQuestionsLoading: boolean;
    };
    selectors: {
        slug: (state: any, props?: any) => string;
        errorCode: (state: any, props?: any) => string | null;
        context: (state: any, props?: any) => ParticipantContext | null;
        contextLoading: (state: any, props?: any) => boolean;
        nextStep: (state: any, props?: any) => ParticipantStep;
        nextStepLoading: (state: any, props?: any) => boolean;
        screenerQuestions: (state: any, props?: any) => ScreenerQuestion[];
        screenerQuestionsLoading: (state: any, props?: any) => boolean;
        studyName: (state: any, props?: any) => string;
    };
    sharedListeners: {};
    values: {
        slug: string;
        errorCode: string | null;
        context: ParticipantContext | null;
        contextLoading: boolean;
        nextStep: ParticipantStep;
        nextStepLoading: boolean;
        screenerQuestions: ScreenerQuestion[];
        screenerQuestionsLoading: boolean;
        studyName: string;
    };
    _isKea: true;
    _isKeaWithKey: false;
    __keaTypeGenInternalSelectorTypes: {
        studyName: (context: ParticipantContext | null) => string;
    };
}