// Generated by kea-typegen on Sun, 10 May 2026 03:01:28 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from "kea";

import type {
  InterviewMode,
  InterviewTurn,
  LocalAttachment,
  SessionStatus,
  Stimulus,
} from "./types";

export interface interviewRoomLogicType extends Logic {
  actionCreators: {
    selectMode: (mode: InterviewMode) => {
      type: "select mode (scenes.interview_room.interviewRoomLogic)";
      payload: {
        mode: InterviewMode;
      };
    };
    startSession: () => {
      type: "start session (scenes.interview_room.interviewRoomLogic)";
      payload: {
        value: true;
      };
    };
    setSessionId: (sessionId: string) => {
      type: "set session id (scenes.interview_room.interviewRoomLogic)";
      payload: {
        sessionId: string;
      };
    };
    appendTurn: (turn: InterviewTurn) => {
      type: "append turn (scenes.interview_room.interviewRoomLogic)";
      payload: {
        turn: InterviewTurn;
      };
    };
    setPhase: (phase: SessionStatus) => {
      type: "set phase (scenes.interview_room.interviewRoomLogic)";
      payload: {
        phase: SessionStatus;
      };
    };
    setError: (error: string | null) => {
      type: "set error (scenes.interview_room.interviewRoomLogic)";
      payload: {
        error: string | null;
      };
    };
    setPreviewMode: (enabled: boolean) => {
      type: "set preview mode (scenes.interview_room.interviewRoomLogic)";
      payload: {
        enabled: boolean;
      };
    };
    attachFile: (file: File) => {
      type: "attach file (scenes.interview_room.interviewRoomLogic)";
      payload: {
        file: File;
      };
    };
    removeAttachment: (id: string) => {
      type: "remove attachment (scenes.interview_room.interviewRoomLogic)";
      payload: {
        id: string;
      };
    };
    showStimulus: (stimulus: Stimulus) => {
      type: "show stimulus (scenes.interview_room.interviewRoomLogic)";
      payload: {
        stimulus: Stimulus;
      };
    };
    hideStimulus: () => {
      type: "hide stimulus (scenes.interview_room.interviewRoomLogic)";
      payload: {
        value: true;
      };
    };
    clear: () => {
      type: "clear (scenes.interview_room.interviewRoomLogic)";
      payload: {
        value: true;
      };
    };
  };
  actionKeys: {
    "select mode (scenes.interview_room.interviewRoomLogic)": "selectMode";
    "start session (scenes.interview_room.interviewRoomLogic)": "startSession";
    "set session id (scenes.interview_room.interviewRoomLogic)": "setSessionId";
    "append turn (scenes.interview_room.interviewRoomLogic)": "appendTurn";
    "set phase (scenes.interview_room.interviewRoomLogic)": "setPhase";
    "set error (scenes.interview_room.interviewRoomLogic)": "setError";
    "set preview mode (scenes.interview_room.interviewRoomLogic)": "setPreviewMode";
    "attach file (scenes.interview_room.interviewRoomLogic)": "attachFile";
    "remove attachment (scenes.interview_room.interviewRoomLogic)": "removeAttachment";
    "show stimulus (scenes.interview_room.interviewRoomLogic)": "showStimulus";
    "hide stimulus (scenes.interview_room.interviewRoomLogic)": "hideStimulus";
    "clear (scenes.interview_room.interviewRoomLogic)": "clear";
  };
  actionTypes: {
    selectMode: "select mode (scenes.interview_room.interviewRoomLogic)";
    startSession: "start session (scenes.interview_room.interviewRoomLogic)";
    setSessionId: "set session id (scenes.interview_room.interviewRoomLogic)";
    appendTurn: "append turn (scenes.interview_room.interviewRoomLogic)";
    setPhase: "set phase (scenes.interview_room.interviewRoomLogic)";
    setError: "set error (scenes.interview_room.interviewRoomLogic)";
    setPreviewMode: "set preview mode (scenes.interview_room.interviewRoomLogic)";
    attachFile: "attach file (scenes.interview_room.interviewRoomLogic)";
    removeAttachment: "remove attachment (scenes.interview_room.interviewRoomLogic)";
    showStimulus: "show stimulus (scenes.interview_room.interviewRoomLogic)";
    hideStimulus: "hide stimulus (scenes.interview_room.interviewRoomLogic)";
    clear: "clear (scenes.interview_room.interviewRoomLogic)";
  };
  actions: {
    selectMode: (mode: InterviewMode) => void;
    startSession: () => void;
    setSessionId: (sessionId: string) => void;
    appendTurn: (turn: InterviewTurn) => void;
    setPhase: (phase: SessionStatus) => void;
    setError: (error: string | null) => void;
    setPreviewMode: (enabled: boolean) => void;
    attachFile: (file: File) => void;
    removeAttachment: (id: string) => void;
    showStimulus: (stimulus: Stimulus) => void;
    hideStimulus: () => void;
    clear: () => void;
  };
  asyncActions: {
    selectMode: (mode: InterviewMode) => Promise<any>;
    startSession: () => Promise<any>;
    setSessionId: (sessionId: string) => Promise<any>;
    appendTurn: (turn: InterviewTurn) => Promise<any>;
    setPhase: (phase: SessionStatus) => Promise<any>;
    setError: (error: string | null) => Promise<any>;
    setPreviewMode: (enabled: boolean) => Promise<any>;
    attachFile: (file: File) => Promise<any>;
    removeAttachment: (id: string) => Promise<any>;
    showStimulus: (stimulus: Stimulus) => Promise<any>;
    hideStimulus: () => Promise<any>;
    clear: () => Promise<any>;
  };
  defaults: {
    mode: InterviewMode;
    sessionId: string | null;
    turns: InterviewTurn[];
    phase: SessionStatus;
    error: string | null;
    previewMode: boolean;
    attachments: LocalAttachment[];
    activeStimulus: Stimulus | null;
  };
  events: {};
  key: undefined;
  listeners: {
    startSession: ((
      action: {
        type: "start session (scenes.interview_room.interviewRoomLogic)";
        payload: {
          value: true;
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
  };
  path: ["scenes", "interview_room", "interviewRoomLogic"];
  pathString: "scenes.interview_room.interviewRoomLogic";
  props: Record<string, unknown>;
  reducer: (
    state: any,
    action: any,
    fullState: any,
  ) => {
    mode: InterviewMode;
    sessionId: string | null;
    turns: InterviewTurn[];
    phase: SessionStatus;
    error: string | null;
    previewMode: boolean;
    attachments: LocalAttachment[];
    activeStimulus: Stimulus | null;
  };
  reducers: {
    mode: (state: InterviewMode, action: any, fullState: any) => InterviewMode;
    sessionId: (
      state: string | null,
      action: any,
      fullState: any,
    ) => string | null;
    turns: (
      state: InterviewTurn[],
      action: any,
      fullState: any,
    ) => InterviewTurn[];
    phase: (state: SessionStatus, action: any, fullState: any) => SessionStatus;
    error: (state: string | null, action: any, fullState: any) => string | null;
    previewMode: (state: boolean, action: any, fullState: any) => boolean;
    attachments: (
      state: LocalAttachment[],
      action: any,
      fullState: any,
    ) => LocalAttachment[];
    activeStimulus: (
      state: Stimulus | null,
      action: any,
      fullState: any,
    ) => Stimulus | null;
  };
  selector: (state: any) => {
    mode: InterviewMode;
    sessionId: string | null;
    turns: InterviewTurn[];
    phase: SessionStatus;
    error: string | null;
    previewMode: boolean;
    attachments: LocalAttachment[];
    activeStimulus: Stimulus | null;
  };
  selectors: {
    mode: (state: any, props?: any) => InterviewMode;
    sessionId: (state: any, props?: any) => string | null;
    turns: (state: any, props?: any) => InterviewTurn[];
    phase: (state: any, props?: any) => SessionStatus;
    error: (state: any, props?: any) => string | null;
    previewMode: (state: any, props?: any) => boolean;
    attachments: (state: any, props?: any) => LocalAttachment[];
    activeStimulus: (state: any, props?: any) => Stimulus | null;
  };
  sharedListeners: {};
  values: {
    mode: InterviewMode;
    sessionId: string | null;
    turns: InterviewTurn[];
    phase: SessionStatus;
    error: string | null;
    previewMode: boolean;
    attachments: LocalAttachment[];
    activeStimulus: Stimulus | null;
  };
  _isKea: true;
  _isKeaWithKey: false;
}
