// Generated by kea-typegen on Sun, 10 May 2026 17:48:14 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from "kea";

import type { TextTurn } from "./textInterviewLogic";

export interface textInterviewLogicType extends Logic {
  actionCreators: {
    setSessionId: (sessionId: string) => {
      type: "set session id (features.interview.textInterviewLogic)";
      payload: {
        sessionId: string;
      };
    };
    bootstrapFromUrl: () => {
      type: "bootstrap from url (features.interview.textInterviewLogic)";
      payload: {
        value: true;
      };
    };
    setDraft: (draft: string) => {
      type: "set draft (features.interview.textInterviewLogic)";
      payload: {
        draft: string;
      };
    };
    sendMessage: () => {
      type: "send message (features.interview.textInterviewLogic)";
      payload: {
        value: true;
      };
    };
    appendUserTurn: (text: string) => {
      type: "append user turn (features.interview.textInterviewLogic)";
      payload: {
        text: string;
      };
    };
    updateStreamingAssistant: (partial: string) => {
      type: "update streaming assistant (features.interview.textInterviewLogic)";
      payload: {
        partial: string;
      };
    };
    finalizeAssistant: (
      finalText: string,
      sessionStatus: string,
    ) => {
      type: "finalize assistant (features.interview.textInterviewLogic)";
      payload: {
        finalText: string;
        sessionStatus: string;
      };
    };
    setError: (error: string | null) => {
      type: "set error (features.interview.textInterviewLogic)";
      payload: {
        error: string | null;
      };
    };
    setSending: (isSending: boolean) => {
      type: "set sending (features.interview.textInterviewLogic)";
      payload: {
        isSending: boolean;
      };
    };
    setCompleted: (isCompleted: boolean) => {
      type: "set completed (features.interview.textInterviewLogic)";
      payload: {
        isCompleted: boolean;
      };
    };
  };
  actionKeys: {
    "set session id (features.interview.textInterviewLogic)": "setSessionId";
    "bootstrap from url (features.interview.textInterviewLogic)": "bootstrapFromUrl";
    "set draft (features.interview.textInterviewLogic)": "setDraft";
    "send message (features.interview.textInterviewLogic)": "sendMessage";
    "append user turn (features.interview.textInterviewLogic)": "appendUserTurn";
    "update streaming assistant (features.interview.textInterviewLogic)": "updateStreamingAssistant";
    "finalize assistant (features.interview.textInterviewLogic)": "finalizeAssistant";
    "set error (features.interview.textInterviewLogic)": "setError";
    "set sending (features.interview.textInterviewLogic)": "setSending";
    "set completed (features.interview.textInterviewLogic)": "setCompleted";
  };
  actionTypes: {
    setSessionId: "set session id (features.interview.textInterviewLogic)";
    bootstrapFromUrl: "bootstrap from url (features.interview.textInterviewLogic)";
    setDraft: "set draft (features.interview.textInterviewLogic)";
    sendMessage: "send message (features.interview.textInterviewLogic)";
    appendUserTurn: "append user turn (features.interview.textInterviewLogic)";
    updateStreamingAssistant: "update streaming assistant (features.interview.textInterviewLogic)";
    finalizeAssistant: "finalize assistant (features.interview.textInterviewLogic)";
    setError: "set error (features.interview.textInterviewLogic)";
    setSending: "set sending (features.interview.textInterviewLogic)";
    setCompleted: "set completed (features.interview.textInterviewLogic)";
  };
  actions: {
    setSessionId: (sessionId: string) => void;
    bootstrapFromUrl: () => void;
    setDraft: (draft: string) => void;
    sendMessage: () => void;
    appendUserTurn: (text: string) => void;
    updateStreamingAssistant: (partial: string) => void;
    finalizeAssistant: (finalText: string, sessionStatus: string) => void;
    setError: (error: string | null) => void;
    setSending: (isSending: boolean) => void;
    setCompleted: (isCompleted: boolean) => void;
  };
  asyncActions: {
    setSessionId: (sessionId: string) => Promise<any>;
    bootstrapFromUrl: () => Promise<any>;
    setDraft: (draft: string) => Promise<any>;
    sendMessage: () => Promise<any>;
    appendUserTurn: (text: string) => Promise<any>;
    updateStreamingAssistant: (partial: string) => Promise<any>;
    finalizeAssistant: (
      finalText: string,
      sessionStatus: string,
    ) => Promise<any>;
    setError: (error: string | null) => Promise<any>;
    setSending: (isSending: boolean) => Promise<any>;
    setCompleted: (isCompleted: boolean) => Promise<any>;
  };
  defaults: {
    sessionId: string;
    turns: TextTurn[];
    draft: string;
    isSending: boolean;
    error: string | null;
    isCompleted: boolean;
  };
  events: {};
  key: undefined;
  listeners: {
    bootstrapFromUrl: ((
      action: {
        type: "bootstrap from url (features.interview.textInterviewLogic)";
        payload: {
          value: true;
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
    sendMessage: ((
      action: {
        type: "send message (features.interview.textInterviewLogic)";
        payload: {
          value: true;
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
  };
  path: ["features", "interview", "textInterviewLogic"];
  pathString: "features.interview.textInterviewLogic";
  props: Record<string, unknown>;
  reducer: (
    state: any,
    action: any,
    fullState: any,
  ) => {
    sessionId: string;
    turns: TextTurn[];
    draft: string;
    isSending: boolean;
    error: string | null;
    isCompleted: boolean;
  };
  reducers: {
    sessionId: (state: string, action: any, fullState: any) => string;
    turns: (state: TextTurn[], action: any, fullState: any) => TextTurn[];
    draft: (state: string, action: any, fullState: any) => string;
    isSending: (state: boolean, action: any, fullState: any) => boolean;
    error: (state: string | null, action: any, fullState: any) => string | null;
    isCompleted: (state: boolean, action: any, fullState: any) => boolean;
  };
  selector: (state: any) => {
    sessionId: string;
    turns: TextTurn[];
    draft: string;
    isSending: boolean;
    error: string | null;
    isCompleted: boolean;
  };
  selectors: {
    sessionId: (state: any, props?: any) => string;
    turns: (state: any, props?: any) => TextTurn[];
    draft: (state: any, props?: any) => string;
    isSending: (state: any, props?: any) => boolean;
    error: (state: any, props?: any) => string | null;
    isCompleted: (state: any, props?: any) => boolean;
  };
  sharedListeners: {};
  values: {
    sessionId: string;
    turns: TextTurn[];
    draft: string;
    isSending: boolean;
    error: string | null;
    isCompleted: boolean;
  };
  _isKea: true;
  _isKeaWithKey: false;
}
