// Generated by kea-typegen on Sun, 10 May 2026 02:51:59 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from "kea";

import type { AudioCapture } from "./voice/index";
import type { ServerMessage } from "./voiceStreamLogic";
import type { InterviewTurn, SessionStatus } from "./types";

export interface voiceStreamLogicType extends Logic {
  actionCreators: {
    attachCapture: (capture: AudioCapture) => {
      type: "attach capture (scenes.interview_room.voiceStreamLogic)";
      payload: {
        capture: AudioCapture;
      };
    };
    connect: (sessionId: string) => {
      type: "connect (scenes.interview_room.voiceStreamLogic)";
      payload: {
        sessionId: string;
      };
    };
    disconnect: () => {
      type: "disconnect (scenes.interview_room.voiceStreamLogic)";
      payload: {
        value: true;
      };
    };
    serverMessage: (message: ServerMessage) => {
      type: "server message (scenes.interview_room.voiceStreamLogic)";
      payload: {
        message: ServerMessage;
      };
    };
    appendCaption: (turn: InterviewTurn) => {
      type: "append caption (scenes.interview_room.voiceStreamLogic)";
      payload: {
        turn: InterviewTurn;
      };
    };
    setPartialCaption: (text: string) => {
      type: "set partial caption (scenes.interview_room.voiceStreamLogic)";
      payload: {
        text: string;
      };
    };
    setAgentCaption: (text: string) => {
      type: "set agent caption (scenes.interview_room.voiceStreamLogic)";
      payload: {
        text: string;
      };
    };
    setMicLevel: (level: number) => {
      type: "set mic level (scenes.interview_room.voiceStreamLogic)";
      payload: {
        level: number;
      };
    };
    setPhase: (phase: SessionStatus) => {
      type: "set phase (scenes.interview_room.voiceStreamLogic)";
      payload: {
        phase: SessionStatus;
      };
    };
    setError: (error: string | null) => {
      type: "set error (scenes.interview_room.voiceStreamLogic)";
      payload: {
        error: string | null;
      };
    };
    setPttActive: (active: boolean) => {
      type: "set ptt active (scenes.interview_room.voiceStreamLogic)";
      payload: {
        active: boolean;
      };
    };
    setBotSpeaking: (speaking: boolean) => {
      type: "set bot speaking (scenes.interview_room.voiceStreamLogic)";
      payload: {
        speaking: boolean;
      };
    };
    pttPress: () => {
      type: "ptt press (scenes.interview_room.voiceStreamLogic)";
      payload: {
        value: true;
      };
    };
    sendTextInput: (text: string) => {
      type: "send text input (scenes.interview_room.voiceStreamLogic)";
      payload: {
        text: string;
      };
    };
    clear: () => {
      type: "clear (scenes.interview_room.voiceStreamLogic)";
      payload: {
        value: true;
      };
    };
  };
  actionKeys: {
    "attach capture (scenes.interview_room.voiceStreamLogic)": "attachCapture";
    "connect (scenes.interview_room.voiceStreamLogic)": "connect";
    "disconnect (scenes.interview_room.voiceStreamLogic)": "disconnect";
    "server message (scenes.interview_room.voiceStreamLogic)": "serverMessage";
    "append caption (scenes.interview_room.voiceStreamLogic)": "appendCaption";
    "set partial caption (scenes.interview_room.voiceStreamLogic)": "setPartialCaption";
    "set agent caption (scenes.interview_room.voiceStreamLogic)": "setAgentCaption";
    "set mic level (scenes.interview_room.voiceStreamLogic)": "setMicLevel";
    "set phase (scenes.interview_room.voiceStreamLogic)": "setPhase";
    "set error (scenes.interview_room.voiceStreamLogic)": "setError";
    "set ptt active (scenes.interview_room.voiceStreamLogic)": "setPttActive";
    "set bot speaking (scenes.interview_room.voiceStreamLogic)": "setBotSpeaking";
    "ptt press (scenes.interview_room.voiceStreamLogic)": "pttPress";
    "send text input (scenes.interview_room.voiceStreamLogic)": "sendTextInput";
    "clear (scenes.interview_room.voiceStreamLogic)": "clear";
  };
  actionTypes: {
    attachCapture: "attach capture (scenes.interview_room.voiceStreamLogic)";
    connect: "connect (scenes.interview_room.voiceStreamLogic)";
    disconnect: "disconnect (scenes.interview_room.voiceStreamLogic)";
    serverMessage: "server message (scenes.interview_room.voiceStreamLogic)";
    appendCaption: "append caption (scenes.interview_room.voiceStreamLogic)";
    setPartialCaption: "set partial caption (scenes.interview_room.voiceStreamLogic)";
    setAgentCaption: "set agent caption (scenes.interview_room.voiceStreamLogic)";
    setMicLevel: "set mic level (scenes.interview_room.voiceStreamLogic)";
    setPhase: "set phase (scenes.interview_room.voiceStreamLogic)";
    setError: "set error (scenes.interview_room.voiceStreamLogic)";
    setPttActive: "set ptt active (scenes.interview_room.voiceStreamLogic)";
    setBotSpeaking: "set bot speaking (scenes.interview_room.voiceStreamLogic)";
    pttPress: "ptt press (scenes.interview_room.voiceStreamLogic)";
    sendTextInput: "send text input (scenes.interview_room.voiceStreamLogic)";
    clear: "clear (scenes.interview_room.voiceStreamLogic)";
  };
  actions: {
    attachCapture: (capture: AudioCapture) => void;
    connect: (sessionId: string) => void;
    disconnect: () => void;
    serverMessage: (message: ServerMessage) => void;
    appendCaption: (turn: InterviewTurn) => void;
    setPartialCaption: (text: string) => void;
    setAgentCaption: (text: string) => void;
    setMicLevel: (level: number) => void;
    setPhase: (phase: SessionStatus) => void;
    setError: (error: string | null) => void;
    setPttActive: (active: boolean) => void;
    setBotSpeaking: (speaking: boolean) => void;
    pttPress: () => void;
    sendTextInput: (text: string) => void;
    clear: () => void;
  };
  asyncActions: {
    attachCapture: (capture: AudioCapture) => Promise<any>;
    connect: (sessionId: string) => Promise<any>;
    disconnect: () => Promise<any>;
    serverMessage: (message: ServerMessage) => Promise<any>;
    appendCaption: (turn: InterviewTurn) => Promise<any>;
    setPartialCaption: (text: string) => Promise<any>;
    setAgentCaption: (text: string) => Promise<any>;
    setMicLevel: (level: number) => Promise<any>;
    setPhase: (phase: SessionStatus) => Promise<any>;
    setError: (error: string | null) => Promise<any>;
    setPttActive: (active: boolean) => Promise<any>;
    setBotSpeaking: (speaking: boolean) => Promise<any>;
    pttPress: () => Promise<any>;
    sendTextInput: (text: string) => Promise<any>;
    clear: () => Promise<any>;
  };
  defaults: {
    connected: boolean;
    phase: SessionStatus;
    bargeInEnabled: boolean;
    pttActive: boolean;
    botSpeaking: boolean;
    partialCaption: string;
    agentCaption: string;
    turns: InterviewTurn[];
    micLevel: number;
    error: string | null;
  };
  events: {};
  key: undefined;
  listeners: {
    attachCapture: ((
      action: {
        type: "attach capture (scenes.interview_room.voiceStreamLogic)";
        payload: {
          capture: AudioCapture;
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
    connect: ((
      action: {
        type: "connect (scenes.interview_room.voiceStreamLogic)";
        payload: {
          sessionId: string;
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
    pttPress: ((
      action: {
        type: "ptt press (scenes.interview_room.voiceStreamLogic)";
        payload: {
          value: true;
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
    sendTextInput: ((
      action: {
        type: "send text input (scenes.interview_room.voiceStreamLogic)";
        payload: {
          text: string;
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
    disconnect: ((
      action: {
        type: "disconnect (scenes.interview_room.voiceStreamLogic)";
        payload: {
          value: true;
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
    serverMessage: ((
      action: {
        type: "server message (scenes.interview_room.voiceStreamLogic)";
        payload: {
          message: ServerMessage;
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
    clear: ((
      action: {
        type: "clear (scenes.interview_room.voiceStreamLogic)";
        payload: {
          value: true;
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
  };
  path: ["scenes", "interview_room", "voiceStreamLogic"];
  pathString: "scenes.interview_room.voiceStreamLogic";
  props: Record<string, unknown>;
  reducer: (
    state: any,
    action: any,
    fullState: any,
  ) => {
    connected: boolean;
    phase: SessionStatus;
    bargeInEnabled: boolean;
    pttActive: boolean;
    botSpeaking: boolean;
    partialCaption: string;
    agentCaption: string;
    turns: InterviewTurn[];
    micLevel: number;
    error: string | null;
  };
  reducers: {
    connected: (state: boolean, action: any, fullState: any) => boolean;
    phase: (state: SessionStatus, action: any, fullState: any) => SessionStatus;
    bargeInEnabled: (state: boolean, action: any, fullState: any) => boolean;
    pttActive: (state: boolean, action: any, fullState: any) => boolean;
    botSpeaking: (state: boolean, action: any, fullState: any) => boolean;
    partialCaption: (state: string, action: any, fullState: any) => string;
    agentCaption: (state: string, action: any, fullState: any) => string;
    turns: (
      state: InterviewTurn[],
      action: any,
      fullState: any,
    ) => InterviewTurn[];
    micLevel: (state: number, action: any, fullState: any) => number;
    error: (state: string | null, action: any, fullState: any) => string | null;
  };
  selector: (state: any) => {
    connected: boolean;
    phase: SessionStatus;
    bargeInEnabled: boolean;
    pttActive: boolean;
    botSpeaking: boolean;
    partialCaption: string;
    agentCaption: string;
    turns: InterviewTurn[];
    micLevel: number;
    error: string | null;
  };
  selectors: {
    connected: (state: any, props?: any) => boolean;
    phase: (state: any, props?: any) => SessionStatus;
    bargeInEnabled: (state: any, props?: any) => boolean;
    pttActive: (state: any, props?: any) => boolean;
    botSpeaking: (state: any, props?: any) => boolean;
    partialCaption: (state: any, props?: any) => string;
    agentCaption: (state: any, props?: any) => string;
    turns: (state: any, props?: any) => InterviewTurn[];
    micLevel: (state: any, props?: any) => number;
    error: (state: any, props?: any) => string | null;
  };
  sharedListeners: {};
  values: {
    connected: boolean;
    phase: SessionStatus;
    bargeInEnabled: boolean;
    pttActive: boolean;
    botSpeaking: boolean;
    partialCaption: string;
    agentCaption: string;
    turns: InterviewTurn[];
    micLevel: number;
    error: string | null;
  };
  _isKea: true;
  _isKeaWithKey: false;
}
