// Generated by kea-typegen on Sat, 09 May 2026 18:46:08 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { Scene } from './routes'
import type { SceneConfig, SceneParams } from './sceneTypes'

export interface sceneLogicType extends Logic {
    actionCreators: {
        setScene: (scene: Scene, params: SceneParams) => ({
            type: "set scene (app.sceneLogic)";
            payload: {
                params: SceneParams;
                scene: Scene;
            };
        });
    };
    actionKeys: {
        "set scene (app.sceneLogic)": "setScene";
    };
    actionTypes: {
        setScene: "set scene (app.sceneLogic)";
    };
    actions: {
        setScene: (scene: Scene, params: SceneParams) => void;
    };
    asyncActions: {
        setScene: (scene: Scene, params: SceneParams) => Promise<any>;
    };
    defaults: {
        activeScene: Scene;
        sceneParams: SceneParams;
    };
    events: {};
    key: undefined;
    listeners: {};
    path: [
        "app",
        "sceneLogic"
    ];
    pathString: "app.sceneLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {
        activeScene: Scene;
        sceneParams: SceneParams;
    };
    reducers: {
        activeScene: (state: Scene, action: any, fullState: any) => Scene;
        sceneParams: (state: SceneParams, action: any, fullState: any) => SceneParams;
    };
    selector: (state: any) => {
        activeScene: Scene;
        sceneParams: SceneParams;
    };
    selectors: {
        activeScene: (state: any, props?: any) => Scene;
        sceneParams: (state: any, props?: any) => SceneParams;
        activeSceneConfig: (state: any, props?: any) => SceneConfig;
    };
    sharedListeners: {};
    values: {
        activeScene: Scene;
        sceneParams: SceneParams;
        activeSceneConfig: SceneConfig;
    };
    _isKea: true;
    _isKeaWithKey: false;
    __keaTypeGenInternalSelectorTypes: {
        activeSceneConfig: (activeScene: Scene) => SceneConfig;
    };
}