// Generated by kea-typegen on Sat, 09 May 2026 18:43:39 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from "kea";

import type { AskMerismMessage } from "./types";

export interface askLogicType extends Logic {
  actionCreators: {
    askQuestion: (question: string) => {
      type: "ask question (scenes.ask.askLogic)";
      payload: {
        question: string;
      };
    };
    pushMessage: (message: AskMerismMessage) => {
      type: "push message (scenes.ask.askLogic)";
      payload: {
        message: AskMerismMessage;
      };
    };
    updateMessage: (
      id: string,
      patch: Partial<AskMerismMessage>,
    ) => {
      type: "update message (scenes.ask.askLogic)";
      payload: {
        id: string;
        patch: Partial<AskMerismMessage>;
      };
    };
    setSending: (sending: boolean) => {
      type: "set sending (scenes.ask.askLogic)";
      payload: {
        sending: boolean;
      };
    };
    clear: () => {
      type: "clear (scenes.ask.askLogic)";
      payload: {
        value: true;
      };
    };
  };
  actionKeys: {
    "ask question (scenes.ask.askLogic)": "askQuestion";
    "push message (scenes.ask.askLogic)": "pushMessage";
    "update message (scenes.ask.askLogic)": "updateMessage";
    "set sending (scenes.ask.askLogic)": "setSending";
    "clear (scenes.ask.askLogic)": "clear";
  };
  actionTypes: {
    askQuestion: "ask question (scenes.ask.askLogic)";
    pushMessage: "push message (scenes.ask.askLogic)";
    updateMessage: "update message (scenes.ask.askLogic)";
    setSending: "set sending (scenes.ask.askLogic)";
    clear: "clear (scenes.ask.askLogic)";
  };
  actions: {
    askQuestion: (question: string) => void;
    pushMessage: (message: AskMerismMessage) => void;
    updateMessage: (id: string, patch: Partial<AskMerismMessage>) => void;
    setSending: (sending: boolean) => void;
    clear: () => void;
  };
  asyncActions: {
    askQuestion: (question: string) => Promise<any>;
    pushMessage: (message: AskMerismMessage) => Promise<any>;
    updateMessage: (
      id: string,
      patch: Partial<AskMerismMessage>,
    ) => Promise<any>;
    setSending: (sending: boolean) => Promise<any>;
    clear: () => Promise<any>;
  };
  defaults: {
    messages: AskMerismMessage[];
    isSending: boolean;
  };
  events: {};
  key: undefined;
  listeners: {
    askQuestion: ((
      action: {
        type: "ask question (scenes.ask.askLogic)";
        payload: {
          question: string;
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
  };
  path: ["scenes", "ask", "askLogic"];
  pathString: "scenes.ask.askLogic";
  props: Record<string, unknown>;
  reducer: (
    state: any,
    action: any,
    fullState: any,
  ) => {
    messages: AskMerismMessage[];
    isSending: boolean;
  };
  reducers: {
    messages: (
      state: AskMerismMessage[],
      action: any,
      fullState: any,
    ) => AskMerismMessage[];
    isSending: (state: boolean, action: any, fullState: any) => boolean;
  };
  selector: (state: any) => {
    messages: AskMerismMessage[];
    isSending: boolean;
  };
  selectors: {
    messages: (state: any, props?: any) => AskMerismMessage[];
    isSending: (state: any, props?: any) => boolean;
    messageCount: (state: any, props?: any) => number;
    lastAssistant: (state: any, props?: any) => AskMerismMessage | undefined;
  };
  sharedListeners: {};
  values: {
    messages: AskMerismMessage[];
    isSending: boolean;
    messageCount: number;
    lastAssistant: AskMerismMessage | undefined;
  };
  _isKea: true;
  _isKeaWithKey: false;
  __keaTypeGenInternalSelectorTypes: {
    messageCount: (messages: AskMerismMessage[]) => number;
    lastAssistant: (
      messages: AskMerismMessage[],
    ) => AskMerismMessage | undefined;
  };
}
