// Generated by kea-typegen on Sat, 09 May 2026 19:18:12 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from "kea";

import type { InterviewSession } from "../../../../types";

export interface sessionsLogicType extends Logic {
  actionCreators: {
    loadSessions: (studyId: string) => {
      type: "load sessions (features.studies.tabs.sessions.sessionsLogic)";
      payload: string;
    };
    loadSessionsSuccess: (
      sessions: InterviewSession[],
      payload?: string,
    ) => {
      type: "load sessions success (features.studies.tabs.sessions.sessionsLogic)";
      payload: {
        sessions: InterviewSession[];
        payload?: string;
      };
    };
    loadSessionsFailure: (
      error: string,
      errorObject?: any,
    ) => {
      type: "load sessions failure (features.studies.tabs.sessions.sessionsLogic)";
      payload: {
        error: string;
        errorObject?: any;
      };
    };
  };
  actionKeys: {
    "load sessions (features.studies.tabs.sessions.sessionsLogic)": "loadSessions";
    "load sessions success (features.studies.tabs.sessions.sessionsLogic)": "loadSessionsSuccess";
    "load sessions failure (features.studies.tabs.sessions.sessionsLogic)": "loadSessionsFailure";
  };
  actionTypes: {
    loadSessions: "load sessions (features.studies.tabs.sessions.sessionsLogic)";
    loadSessionsSuccess: "load sessions success (features.studies.tabs.sessions.sessionsLogic)";
    loadSessionsFailure: "load sessions failure (features.studies.tabs.sessions.sessionsLogic)";
  };
  actions: {
    loadSessions: (studyId: string) => void;
    loadSessionsSuccess: (
      sessions: InterviewSession[],
      payload?: string,
    ) => void;
    loadSessionsFailure: (error: string, errorObject?: any) => void;
  };
  asyncActions: {
    loadSessions: (studyId: string) => Promise<any>;
    loadSessionsSuccess: (
      sessions: InterviewSession[],
      payload?: string,
    ) => Promise<any>;
    loadSessionsFailure: (error: string, errorObject?: any) => Promise<any>;
  };
  defaults: {
    sessions: InterviewSession[];
    sessionsLoading: boolean;
  };
  events: {};
  key: undefined;
  listeners: {};
  path: ["features", "studies", "tabs", "sessions", "sessionsLogic"];
  pathString: "features.studies.tabs.sessions.sessionsLogic";
  props: Record<string, unknown>;
  reducer: (
    state: any,
    action: any,
    fullState: any,
  ) => {
    sessions: InterviewSession[];
    sessionsLoading: boolean;
  };
  reducers: {
    sessions: (
      state: InterviewSession[],
      action: any,
      fullState: any,
    ) => InterviewSession[];
    sessionsLoading: (state: boolean, action: any, fullState: any) => boolean;
  };
  selector: (state: any) => {
    sessions: InterviewSession[];
    sessionsLoading: boolean;
  };
  selectors: {
    sessions: (state: any, props?: any) => InterviewSession[];
    sessionsLoading: (state: any, props?: any) => boolean;
  };
  sharedListeners: {};
  values: {
    sessions: InterviewSession[];
    sessionsLoading: boolean;
  };
  _isKea: true;
  _isKeaWithKey: false;
}
