// Generated by kea-typegen on Sun, 10 May 2026 15:37:26 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from "kea";

import type { Study } from "../../types";
import type { User } from "../../types";

export interface studiesLogicType extends Logic {
  actionCreators: {
    createStudy: () => {
      type: "create study (features.studies.studiesLogic)";
      payload: {
        value: true;
      };
    };
    setPage: (page: number) => {
      type: "set page (features.studies.studiesLogic)";
      payload: {
        page: number;
      };
    };
    setPageSize: (size: number) => {
      type: "set page size (features.studies.studiesLogic)";
      payload: {
        size: number;
      };
    };
    loadStudies: () => {
      type: "load studies (features.studies.studiesLogic)";
      payload: any;
    };
    loadStudiesSuccess: (
      studies: Study[],
      payload?: any,
    ) => {
      type: "load studies success (features.studies.studiesLogic)";
      payload: {
        studies: Study[];
        payload?: any;
      };
    };
    loadStudiesFailure: (
      error: string,
      errorObject?: any,
    ) => {
      type: "load studies failure (features.studies.studiesLogic)";
      payload: {
        error: string;
        errorObject?: any;
      };
    };
    createStudySuccess: (
      newStudy: Study,
      payload?: {
        value: true;
      },
    ) => {
      type: "create study success (features.studies.studiesLogic)";
      payload: {
        newStudy: Study;
        payload?: {
          value: true;
        };
      };
    };
    createStudyFailure: (
      error: string,
      errorObject?: any,
    ) => {
      type: "create study failure (features.studies.studiesLogic)";
      payload: {
        error: string;
        errorObject?: any;
      };
    };
  };
  actionKeys: {
    "create study (features.studies.studiesLogic)": "createStudy";
    "set page (features.studies.studiesLogic)": "setPage";
    "set page size (features.studies.studiesLogic)": "setPageSize";
    "load studies (features.studies.studiesLogic)": "loadStudies";
    "load studies success (features.studies.studiesLogic)": "loadStudiesSuccess";
    "load studies failure (features.studies.studiesLogic)": "loadStudiesFailure";
    "create study success (features.studies.studiesLogic)": "createStudySuccess";
    "create study failure (features.studies.studiesLogic)": "createStudyFailure";
  };
  actionTypes: {
    createStudy: "create study (features.studies.studiesLogic)";
    setPage: "set page (features.studies.studiesLogic)";
    setPageSize: "set page size (features.studies.studiesLogic)";
    loadStudies: "load studies (features.studies.studiesLogic)";
    loadStudiesSuccess: "load studies success (features.studies.studiesLogic)";
    loadStudiesFailure: "load studies failure (features.studies.studiesLogic)";
    createStudySuccess: "create study success (features.studies.studiesLogic)";
    createStudyFailure: "create study failure (features.studies.studiesLogic)";
  };
  actions: {
    createStudy: () => void;
    setPage: (page: number) => void;
    setPageSize: (size: number) => void;
    loadStudies: () => void;
    loadStudiesSuccess: (studies: Study[], payload?: any) => void;
    loadStudiesFailure: (error: string, errorObject?: any) => void;
    createStudySuccess: (
      newStudy: Study,
      payload?: {
        value: true;
      },
    ) => void;
    createStudyFailure: (error: string, errorObject?: any) => void;
  };
  asyncActions: {
    createStudy: () => Promise<any>;
    setPage: (page: number) => Promise<any>;
    setPageSize: (size: number) => Promise<any>;
    loadStudies: () => Promise<any>;
    loadStudiesSuccess: (studies: Study[], payload?: any) => Promise<any>;
    loadStudiesFailure: (error: string, errorObject?: any) => Promise<any>;
    createStudySuccess: (
      newStudy: Study,
      payload?: {
        value: true;
      },
    ) => Promise<any>;
    createStudyFailure: (error: string, errorObject?: any) => Promise<any>;
  };
  defaults: {
    page: number;
    pageSize: number;
    hasLoaded: boolean;
    studies: Study[];
    studiesLoading: boolean;
    newStudy: Study | null;
    newStudyLoading: boolean;
  };
  events: {};
  key: undefined;
  listeners: {
    createStudySuccess: ((
      action: {
        type: "create study success (features.studies.studiesLogic)";
        payload: {
          newStudy: Study;
          payload?: {
            value: true;
          };
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
  };
  path: ["features", "studies", "studiesLogic"];
  pathString: "features.studies.studiesLogic";
  props: Record<string, unknown>;
  reducer: (
    state: any,
    action: any,
    fullState: any,
  ) => {
    page: number;
    pageSize: number;
    hasLoaded: boolean;
    studies: Study[];
    studiesLoading: boolean;
    newStudy: Study | null;
    newStudyLoading: boolean;
  };
  reducers: {
    page: (state: number, action: any, fullState: any) => number;
    pageSize: (state: number, action: any, fullState: any) => number;
    hasLoaded: (state: boolean, action: any, fullState: any) => boolean;
    studies: (state: Study[], action: any, fullState: any) => Study[];
    studiesLoading: (state: boolean, action: any, fullState: any) => boolean;
    newStudy: (
      state: Study | null,
      action: any,
      fullState: any,
    ) => Study | null;
    newStudyLoading: (state: boolean, action: any, fullState: any) => boolean;
  };
  selector: (state: any) => {
    page: number;
    pageSize: number;
    hasLoaded: boolean;
    studies: Study[];
    studiesLoading: boolean;
    newStudy: Study | null;
    newStudyLoading: boolean;
  };
  selectors: {
    page: (state: any, props?: any) => number;
    pageSize: (state: any, props?: any) => number;
    hasLoaded: (state: any, props?: any) => boolean;
    studies: (state: any, props?: any) => Study[];
    studiesLoading: (state: any, props?: any) => boolean;
    newStudy: (state: any, props?: any) => Study | null;
    newStudyLoading: (state: any, props?: any) => boolean;
    draftStudies: (state: any, props?: any) => Study[];
    liveStudies: (state: any, props?: any) => Study[];
    archivedStudies: (state: any, props?: any) => Study[];
    closedStudies: (state: any, props?: any) => Study[];
    pageCount: (state: any, props?: any) => number;
  };
  sharedListeners: {};
  values: {
    page: number;
    pageSize: number;
    hasLoaded: boolean;
    studies: Study[];
    studiesLoading: boolean;
    newStudy: Study | null;
    newStudyLoading: boolean;
    draftStudies: Study[];
    liveStudies: Study[];
    archivedStudies: Study[];
    closedStudies: Study[];
    pageCount: number;
    user: User | null;
  };
  _isKea: true;
  _isKeaWithKey: false;
  __keaTypeGenInternalSelectorTypes: {
    draftStudies: (studies: Study[]) => Study[];
    liveStudies: (studies: Study[]) => Study[];
    archivedStudies: (studies: Study[]) => Study[];
    closedStudies: (studies: Study[]) => Study[];
    pageCount: (studies: Study[], pageSize: number) => number;
  };
}
