// Generated by kea-typegen on Sat, 09 May 2026 18:41:16 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from "kea";

import type { SceneParams } from "../../app/sceneTypes";
import type { Study } from "../../types";
import type { Scene } from "../../app/routes";

export interface studyLogicType extends Logic {
  actionCreators: {
    loadStudy: () => {
      type: "load study (features.studies.studyLogic)";
      payload: any;
    };
    loadStudySuccess: (
      study: Study | null,
      payload?: any,
    ) => {
      type: "load study success (features.studies.studyLogic)";
      payload: {
        study: Study | null;
        payload?: any;
      };
    };
    loadStudyFailure: (
      error: string,
      errorObject?: any,
    ) => {
      type: "load study failure (features.studies.studyLogic)";
      payload: {
        error: string;
        errorObject?: any;
      };
    };
  };
  actionKeys: {
    "load study (features.studies.studyLogic)": "loadStudy";
    "load study success (features.studies.studyLogic)": "loadStudySuccess";
    "load study failure (features.studies.studyLogic)": "loadStudyFailure";
  };
  actionTypes: {
    loadStudy: "load study (features.studies.studyLogic)";
    loadStudySuccess: "load study success (features.studies.studyLogic)";
    loadStudyFailure: "load study failure (features.studies.studyLogic)";
  };
  actions: {
    loadStudy: () => void;
    loadStudySuccess: (study: Study | null, payload?: any) => void;
    loadStudyFailure: (error: string, errorObject?: any) => void;
  };
  asyncActions: {
    loadStudy: () => Promise<any>;
    loadStudySuccess: (study: Study | null, payload?: any) => Promise<any>;
    loadStudyFailure: (error: string, errorObject?: any) => Promise<any>;
  };
  defaults: {
    study: Study | null;
    studyLoading: boolean;
  };
  events: {};
  key: undefined;
  listeners: {};
  path: ["features", "studies", "studyLogic"];
  pathString: "features.studies.studyLogic";
  props: Record<string, unknown>;
  reducer: (
    state: any,
    action: any,
    fullState: any,
  ) => {
    study: Study | null;
    studyLoading: boolean;
  };
  reducers: {
    study: (state: Study | null, action: any, fullState: any) => Study | null;
    studyLoading: (state: boolean, action: any, fullState: any) => boolean;
  };
  selector: (state: any) => {
    study: Study | null;
    studyLoading: boolean;
  };
  selectors: {
    study: (state: any, props?: any) => Study | null;
    studyLoading: (state: any, props?: any) => boolean;
    sceneParams: (state: any, props?: any) => SceneParams;
    studyId: (state: any, props?: any) => string | null;
    activeTab: (state: any, props?: any) => string;
  };
  sharedListeners: {};
  values: {
    study: Study | null;
    studyLoading: boolean;
    sceneParams: SceneParams;
    studyId: string | null;
    activeTab: string;
  };
  _isKea: true;
  _isKeaWithKey: false;
  __keaTypeGenInternalSelectorTypes: {
    studyId: (
      sceneParams: import("~//app/sceneTypes").SceneParams,
    ) => string | null;
    activeTab: (sceneParams: import("~//app/sceneTypes").SceneParams) => string;
  };
  __keaTypeGenInternalReducerActions: {
    "set scene (app.sceneLogic)": (
      scene: Scene,
      params: SceneParams,
    ) => {
      payload: {
        params: SceneParams;
        scene: Scene;
      };
      type: "set scene (app.sceneLogic)";
    };
  };
}
