// Generated by kea-typegen on Sun, 10 May 2026 16:56:44 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { OutlineSection, OutlineSectionScope, ProbePolicy } from './outlineEditorLogic'

export interface outlineEditorLogicType extends Logic {
    actionCreators: {
        loadSections: (sections: OutlineSection[]) => ({
            type: "load sections (features.studies.tabs.outline.outlineEditorLogic)";
            payload: {
                sections: OutlineSection[];
            };
        });
        moveQuestion: (sectionId: string, fromIndex: number, toIndex: number) => ({
            type: "move question (features.studies.tabs.outline.outlineEditorLogic)";
            payload: {
                fromIndex: number;
                sectionId: string;
                toIndex: number;
            };
        });
        moveSection: (fromIndex: number, toIndex: number) => ({
            type: "move section (features.studies.tabs.outline.outlineEditorLogic)";
            payload: {
                fromIndex: number;
                toIndex: number;
            };
        });
        addQuestion: (sectionId: string) => ({
            type: "add question (features.studies.tabs.outline.outlineEditorLogic)";
            payload: {
                sectionId: string;
            };
        });
        updateQuestionText: (sectionId: string, questionId: string, text: string) => ({
            type: "update question text (features.studies.tabs.outline.outlineEditorLogic)";
            payload: {
                questionId: string;
                sectionId: string;
                text: string;
            };
        });
        updateQuestionIntent: (sectionId: string, questionId: string, intent: string) => ({
            type: "update question intent (features.studies.tabs.outline.outlineEditorLogic)";
            payload: {
                intent: string;
                questionId: string;
                sectionId: string;
            };
        });
        updateQuestionProbePolicy: (sectionId: string, questionId: string, policy: ProbePolicy) => ({
            type: "update question probe policy (features.studies.tabs.outline.outlineEditorLogic)";
            payload: {
                policy: ProbePolicy;
                questionId: string;
                sectionId: string;
            };
        });
        updateQuestionMaxProbes: (sectionId: string, questionId: string, maxProbes: number) => ({
            type: "update question max probes (features.studies.tabs.outline.outlineEditorLogic)";
            payload: {
                maxProbes: number;
                questionId: string;
                sectionId: string;
            };
        });
        toggleQuestionRequired: (sectionId: string, questionId: string) => ({
            type: "toggle question required (features.studies.tabs.outline.outlineEditorLogic)";
            payload: {
                questionId: string;
                sectionId: string;
            };
        });
        removeQuestion: (sectionId: string, questionId: string) => ({
            type: "remove question (features.studies.tabs.outline.outlineEditorLogic)";
            payload: {
                questionId: string;
                sectionId: string;
            };
        });
        setSectionScope: (sectionId: string, scope: OutlineSectionScope, conceptBlockId?: string | null) => ({
            type: "set section scope (features.studies.tabs.outline.outlineEditorLogic)";
            payload: {
                conceptBlockId: string | null;
                scope: OutlineSectionScope;
                sectionId: string;
            };
        });
        loadGuide: () => ({
            type: "load guide (features.studies.tabs.outline.outlineEditorLogic)";
            payload: any;
        });
        loadGuideSuccess: (loadedGuide: {
            id: string;
            sections: OutlineSection[];
        } | null, payload?: any) => ({
            type: "load guide success (features.studies.tabs.outline.outlineEditorLogic)";
            payload: {
                loadedGuide: {
                    id: string;
                    sections: OutlineSection[];
                } | null;
                payload?: any;
            };
        });
        loadGuideFailure: (error: string, errorObject?: any) => ({
            type: "load guide failure (features.studies.tabs.outline.outlineEditorLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
        saveGuide: () => ({
            type: "save guide (features.studies.tabs.outline.outlineEditorLogic)";
            payload: any;
        });
        saveGuideSuccess: (loadedGuide: {
            id: string;
            sections: OutlineSection[];
        } | null, payload?: any) => ({
            type: "save guide success (features.studies.tabs.outline.outlineEditorLogic)";
            payload: {
                loadedGuide: {
                    id: string;
                    sections: OutlineSection[];
                } | null;
                payload?: any;
            };
        });
        saveGuideFailure: (error: string, errorObject?: any) => ({
            type: "save guide failure (features.studies.tabs.outline.outlineEditorLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
    };
    actionKeys: {
        "load sections (features.studies.tabs.outline.outlineEditorLogic)": "loadSections";
        "move question (features.studies.tabs.outline.outlineEditorLogic)": "moveQuestion";
        "move section (features.studies.tabs.outline.outlineEditorLogic)": "moveSection";
        "add question (features.studies.tabs.outline.outlineEditorLogic)": "addQuestion";
        "update question text (features.studies.tabs.outline.outlineEditorLogic)": "updateQuestionText";
        "update question intent (features.studies.tabs.outline.outlineEditorLogic)": "updateQuestionIntent";
        "update question probe policy (features.studies.tabs.outline.outlineEditorLogic)": "updateQuestionProbePolicy";
        "update question max probes (features.studies.tabs.outline.outlineEditorLogic)": "updateQuestionMaxProbes";
        "toggle question required (features.studies.tabs.outline.outlineEditorLogic)": "toggleQuestionRequired";
        "remove question (features.studies.tabs.outline.outlineEditorLogic)": "removeQuestion";
        "set section scope (features.studies.tabs.outline.outlineEditorLogic)": "setSectionScope";
        "load guide (features.studies.tabs.outline.outlineEditorLogic)": "loadGuide";
        "load guide success (features.studies.tabs.outline.outlineEditorLogic)": "loadGuideSuccess";
        "load guide failure (features.studies.tabs.outline.outlineEditorLogic)": "loadGuideFailure";
        "save guide (features.studies.tabs.outline.outlineEditorLogic)": "saveGuide";
        "save guide success (features.studies.tabs.outline.outlineEditorLogic)": "saveGuideSuccess";
        "save guide failure (features.studies.tabs.outline.outlineEditorLogic)": "saveGuideFailure";
    };
    actionTypes: {
        loadSections: "load sections (features.studies.tabs.outline.outlineEditorLogic)";
        moveQuestion: "move question (features.studies.tabs.outline.outlineEditorLogic)";
        moveSection: "move section (features.studies.tabs.outline.outlineEditorLogic)";
        addQuestion: "add question (features.studies.tabs.outline.outlineEditorLogic)";
        updateQuestionText: "update question text (features.studies.tabs.outline.outlineEditorLogic)";
        updateQuestionIntent: "update question intent (features.studies.tabs.outline.outlineEditorLogic)";
        updateQuestionProbePolicy: "update question probe policy (features.studies.tabs.outline.outlineEditorLogic)";
        updateQuestionMaxProbes: "update question max probes (features.studies.tabs.outline.outlineEditorLogic)";
        toggleQuestionRequired: "toggle question required (features.studies.tabs.outline.outlineEditorLogic)";
        removeQuestion: "remove question (features.studies.tabs.outline.outlineEditorLogic)";
        setSectionScope: "set section scope (features.studies.tabs.outline.outlineEditorLogic)";
        loadGuide: "load guide (features.studies.tabs.outline.outlineEditorLogic)";
        loadGuideSuccess: "load guide success (features.studies.tabs.outline.outlineEditorLogic)";
        loadGuideFailure: "load guide failure (features.studies.tabs.outline.outlineEditorLogic)";
        saveGuide: "save guide (features.studies.tabs.outline.outlineEditorLogic)";
        saveGuideSuccess: "save guide success (features.studies.tabs.outline.outlineEditorLogic)";
        saveGuideFailure: "save guide failure (features.studies.tabs.outline.outlineEditorLogic)";
    };
    actions: {
        loadSections: (sections: OutlineSection[]) => void;
        moveQuestion: (sectionId: string, fromIndex: number, toIndex: number) => void;
        moveSection: (fromIndex: number, toIndex: number) => void;
        addQuestion: (sectionId: string) => void;
        updateQuestionText: (sectionId: string, questionId: string, text: string) => void;
        updateQuestionIntent: (sectionId: string, questionId: string, intent: string) => void;
        updateQuestionProbePolicy: (sectionId: string, questionId: string, policy: ProbePolicy) => void;
        updateQuestionMaxProbes: (sectionId: string, questionId: string, maxProbes: number) => void;
        toggleQuestionRequired: (sectionId: string, questionId: string) => void;
        removeQuestion: (sectionId: string, questionId: string) => void;
        setSectionScope: (sectionId: string, scope: OutlineSectionScope, conceptBlockId?: string | null) => void;
        loadGuide: () => void;
        loadGuideSuccess: (loadedGuide: {
            id: string;
            sections: OutlineSection[];
        } | null, payload?: any) => void;
        loadGuideFailure: (error: string, errorObject?: any) => void;
        saveGuide: () => void;
        saveGuideSuccess: (loadedGuide: {
            id: string;
            sections: OutlineSection[];
        } | null, payload?: any) => void;
        saveGuideFailure: (error: string, errorObject?: any) => void;
    };
    asyncActions: {
        loadSections: (sections: OutlineSection[]) => Promise<any>;
        moveQuestion: (sectionId: string, fromIndex: number, toIndex: number) => Promise<any>;
        moveSection: (fromIndex: number, toIndex: number) => Promise<any>;
        addQuestion: (sectionId: string) => Promise<any>;
        updateQuestionText: (sectionId: string, questionId: string, text: string) => Promise<any>;
        updateQuestionIntent: (sectionId: string, questionId: string, intent: string) => Promise<any>;
        updateQuestionProbePolicy: (sectionId: string, questionId: string, policy: ProbePolicy) => Promise<any>;
        updateQuestionMaxProbes: (sectionId: string, questionId: string, maxProbes: number) => Promise<any>;
        toggleQuestionRequired: (sectionId: string, questionId: string) => Promise<any>;
        removeQuestion: (sectionId: string, questionId: string) => Promise<any>;
        setSectionScope: (sectionId: string, scope: OutlineSectionScope, conceptBlockId?: string | null) => Promise<any>;
        loadGuide: () => Promise<any>;
        loadGuideSuccess: (loadedGuide: {
            id: string;
            sections: OutlineSection[];
        } | null, payload?: any) => Promise<any>;
        loadGuideFailure: (error: string, errorObject?: any) => Promise<any>;
        saveGuide: () => Promise<any>;
        saveGuideSuccess: (loadedGuide: {
            id: string;
            sections: OutlineSection[];
        } | null, payload?: any) => Promise<any>;
        saveGuideFailure: (error: string, errorObject?: any) => Promise<any>;
    };
    defaults: {
        sections: OutlineSection[];
        loadedGuide: {
            id: string;
            sections: OutlineSection[];
        } | null;
        loadedGuideLoading: boolean;
    };
    events: {};
    key: undefined;
    listeners: {
        "loadGuideSuccess": ((action: {
            type: "load guide success (features.studies.tabs.outline.outlineEditorLogic)";
            payload: {
                loadedGuide: {
                    id: string;
                    sections: OutlineSection[];
                } | null;
                payload?: any;
            };
        }, previousState: any) => void | Promise<void>)[];
    };
    path: [
        "features",
        "studies",
        "tabs",
        "outline",
        "outlineEditorLogic"
    ];
    pathString: "features.studies.tabs.outline.outlineEditorLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {
        sections: OutlineSection[];
        loadedGuide: {
            id: string;
            sections: OutlineSection[];
        } | null;
        loadedGuideLoading: boolean;
    };
    reducers: {
        sections: (state: OutlineSection[], action: any, fullState: any) => OutlineSection[];
        loadedGuide: (state: {
            id: string;
            sections: OutlineSection[];
        } | null, action: any, fullState: any) => {
            id: string;
            sections: OutlineSection[];
        } | null;
        loadedGuideLoading: (state: boolean, action: any, fullState: any) => boolean;
    };
    selector: (state: any) => {
        sections: OutlineSection[];
        loadedGuide: {
            id: string;
            sections: OutlineSection[];
        } | null;
        loadedGuideLoading: boolean;
    };
    selectors: {
        sections: (state: any, props?: any) => OutlineSection[];
        loadedGuide: (state: any, props?: any) => {
            id: string;
            sections: OutlineSection[];
        } | null;
        loadedGuideLoading: (state: any, props?: any) => boolean;
        studyId: (state: any, props?: any) => string | null;
    };
    sharedListeners: {};
    values: {
        sections: OutlineSection[];
        loadedGuide: {
            id: string;
            sections: OutlineSection[];
        } | null;
        loadedGuideLoading: boolean;
        studyId: string | null;
    };
    _isKea: true;
    _isKeaWithKey: false;
}