// Generated by kea-typegen on Sat, 09 May 2026 18:41:10 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { OutlineReviewChatMessage, OutlineSection } from './types'

export interface outlineReviewLogicType extends Logic {
    actionCreators: {
        openFor: (studyId: string, initialSections: OutlineSection[]) => ({
            type: "open for (scenes.outline_review.outlineReviewLogic)";
            payload: {
                initialSections: OutlineSection[];
                studyId: string;
            };
        });
        close: () => ({
            type: "close (scenes.outline_review.outlineReviewLogic)";
            payload: {
                value: true;
            };
        });
        send: (text: string) => ({
            type: "send (scenes.outline_review.outlineReviewLogic)";
            payload: {
                text: string;
            };
        });
        pushMessage: (message: OutlineReviewChatMessage) => ({
            type: "push message (scenes.outline_review.outlineReviewLogic)";
            payload: {
                message: OutlineReviewChatMessage;
            };
        });
        markApplied: (messageId: string) => ({
            type: "mark applied (scenes.outline_review.outlineReviewLogic)";
            payload: {
                messageId: string;
            };
        });
        setSending: (sending: boolean) => ({
            type: "set sending (scenes.outline_review.outlineReviewLogic)";
            payload: {
                sending: boolean;
            };
        });
        setError: (error: string | null) => ({
            type: "set error (scenes.outline_review.outlineReviewLogic)";
            payload: {
                error: string | null;
            };
        });
    };
    actionKeys: {
        "open for (scenes.outline_review.outlineReviewLogic)": "openFor";
        "close (scenes.outline_review.outlineReviewLogic)": "close";
        "send (scenes.outline_review.outlineReviewLogic)": "send";
        "push message (scenes.outline_review.outlineReviewLogic)": "pushMessage";
        "mark applied (scenes.outline_review.outlineReviewLogic)": "markApplied";
        "set sending (scenes.outline_review.outlineReviewLogic)": "setSending";
        "set error (scenes.outline_review.outlineReviewLogic)": "setError";
    };
    actionTypes: {
        openFor: "open for (scenes.outline_review.outlineReviewLogic)";
        close: "close (scenes.outline_review.outlineReviewLogic)";
        send: "send (scenes.outline_review.outlineReviewLogic)";
        pushMessage: "push message (scenes.outline_review.outlineReviewLogic)";
        markApplied: "mark applied (scenes.outline_review.outlineReviewLogic)";
        setSending: "set sending (scenes.outline_review.outlineReviewLogic)";
        setError: "set error (scenes.outline_review.outlineReviewLogic)";
    };
    actions: {
        openFor: (studyId: string, initialSections: OutlineSection[]) => void;
        close: () => void;
        send: (text: string) => void;
        pushMessage: (message: OutlineReviewChatMessage) => void;
        markApplied: (messageId: string) => void;
        setSending: (sending: boolean) => void;
        setError: (error: string | null) => void;
    };
    asyncActions: {
        openFor: (studyId: string, initialSections: OutlineSection[]) => Promise<any>;
        close: () => Promise<any>;
        send: (text: string) => Promise<any>;
        pushMessage: (message: OutlineReviewChatMessage) => Promise<any>;
        markApplied: (messageId: string) => Promise<any>;
        setSending: (sending: boolean) => Promise<any>;
        setError: (error: string | null) => Promise<any>;
    };
    defaults: {
        open: boolean;
        studyId: string | null;
        sections: OutlineSection[];
        messages: OutlineReviewChatMessage[];
        isSending: boolean;
        error: string | null;
    };
    events: {};
    key: undefined;
    listeners: {
        "send": ((action: {
            type: "send (scenes.outline_review.outlineReviewLogic)";
            payload: {
                text: string;
            };
        }, previousState: any) => void | Promise<void>)[];
    };
    path: [
        "scenes",
        "outline_review",
        "outlineReviewLogic"
    ];
    pathString: "scenes.outline_review.outlineReviewLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {
        open: boolean;
        studyId: string | null;
        sections: OutlineSection[];
        messages: OutlineReviewChatMessage[];
        isSending: boolean;
        error: string | null;
    };
    reducers: {
        open: (state: boolean, action: any, fullState: any) => boolean;
        studyId: (state: string | null, action: any, fullState: any) => string | null;
        sections: (state: OutlineSection[], action: any, fullState: any) => OutlineSection[];
        messages: (state: OutlineReviewChatMessage[], action: any, fullState: any) => OutlineReviewChatMessage[];
        isSending: (state: boolean, action: any, fullState: any) => boolean;
        error: (state: string | null, action: any, fullState: any) => string | null;
    };
    selector: (state: any) => {
        open: boolean;
        studyId: string | null;
        sections: OutlineSection[];
        messages: OutlineReviewChatMessage[];
        isSending: boolean;
        error: string | null;
    };
    selectors: {
        open: (state: any, props?: any) => boolean;
        studyId: (state: any, props?: any) => string | null;
        sections: (state: any, props?: any) => OutlineSection[];
        messages: (state: any, props?: any) => OutlineReviewChatMessage[];
        isSending: (state: any, props?: any) => boolean;
        error: (state: any, props?: any) => string | null;
    };
    sharedListeners: {};
    values: {
        open: boolean;
        studyId: string | null;
        sections: OutlineSection[];
        messages: OutlineReviewChatMessage[];
        isSending: boolean;
        error: string | null;
    };
    _isKea: true;
    _isKeaWithKey: false;
}