export type OutlineOp =
  | {
      op: "modify_question";
      question_id: string;
      new_text: string;
      reason?: string;
    }
  | {
      op: "insert_question";
      after_question_id: string;
      new_question: Record<string, unknown>;
      reason?: string;
    }
  | { op: "remove_question"; question_id: string; reason?: string };

export interface OutlineReviewResponse {
  reply_markdown: string;
  proposed_changes: OutlineOp[];
  awaiting_user_decision: boolean;
}

export interface OutlineReviewChatMessage {
  id: string;
  role: "researcher" | "assistant";
  text: string;
  proposed_changes?: OutlineOp[];
}

export type OutlineSectionScope = "global" | "per_concept" | "comparative";

// ── question / section (generic shape, used by review/import flows) ─────────

export interface OutlineQuestion {
  id: string;
  text: string;
  /** What this question aims to produce + probing direction. */
  intent: string;
  probe_policy: "none" | "light" | "deep";
  /** Hard cap on probes (1-5). */
  max_probes: number;
  required?: boolean;
  linked_stimulus_ids?: string[];

  /** @deprecated kept for wire back-compat; ignore in new code. */
  followup_depth?: number;
}

export interface OutlineSection {
  id: string;
  title: string;
  /**
   * Concept Testing 2.0:
   *   - "global"       — runs once per session (warmup, closing)
   *   - "per_concept"  — runs once per concept in the named block
   *   - "comparative"  — runs once after all concepts (cross-concept wrap-up)
   */
  scope?: OutlineSectionScope;
  /** Required when ``scope === "per_concept"``. */
  concept_block_id?: string | null;
  questions: OutlineQuestion[];
}

// ── Conductor v3 (LangGraph) outline shape ──────────────────────────────────
// Per ADR 0012 + docs/specs/conductor-v3/. This is the wire shape persisted
// at `InterviewGuide.sections` for v3 sessions — the dual-engine routing key
// is the top-level `version: "v3"` literal (AGENTS.md Rule 13).
//
// A full visual editor is still TODO (R29). For v3 ship, researchers can
// PUT this JSON directly via `/api/studies/:id/outline/` or edit via admin.

export type V3FollowUpMode = "off" | "standard" | "deep";

export interface V3Question {
  /** Stable identifier — `^[a-zA-Z0-9_]+$`. Auto-generated by the editor. */
  id: string;
  /** What the moderator literally asks the participant. Verbatim. */
  ask: string;
  /**
   * Per-question follow-up intensity.
   * - ``off``: never probe; advance after each user reply (judge LLM not called).
   * - ``standard``: lenient bar; probe budget = ``Configuration.standard_followups`` (default 2).
   * - ``deep``: strict bar (concrete detail required); budget = ``Configuration.deep_followups`` (default 4).
   *
   * Set per-question — researchers commonly use ``off`` on background
   * questions and ``deep`` on pain-point deep-dives.
   */
  follow_up_mode: V3FollowUpMode;
  /**
   * Optional. Researcher-written natural-language guidance on how to
   * probe. Embedded verbatim in the judge prompt as the probing tactic
   * guideline. Leave empty / null for default judge behavior.
   */
  probe_instruction?: string | null;
}

export interface V3Section {
  id: string;
  title: string;
  questions: V3Question[];
}

/**
 * Top-level outline shape persisted on `InterviewGuide.sections` for v3.
 * The `version: "v3"` literal is the dual-engine routing key per Rule 13.
 */
export interface V3Outline {
  version: "v3";
  sections: V3Section[];
}

