// Generated by kea-typegen on Sun, 10 May 2026 03:53:49 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { Study } from '../../../../types'
import type { ConceptBlockRow, Rotation } from './conceptBlocksLogic'

export interface conceptBlocksLogicType extends Logic {
    actionCreators: {
        createBlock: (title: string) => ({
            type: "create block (features.studies.tabs.stimuli.conceptBlocksLogic)";
            payload: {
                title: string;
            };
        });
        deleteBlock: (blockId: string) => ({
            type: "delete block (features.studies.tabs.stimuli.conceptBlocksLogic)";
            payload: {
                blockId: string;
            };
        });
        setRotation: (blockId: string, rotation: Rotation) => ({
            type: "set rotation (features.studies.tabs.stimuli.conceptBlocksLogic)";
            payload: {
                blockId: string;
                rotation: Rotation;
            };
        });
        addConcept: (blockId: string, payload: {
            label: string;
            notes?: string;
            stimulus: string;
        }) => ({
            type: "add concept (features.studies.tabs.stimuli.conceptBlocksLogic)";
            payload: {
                blockId: string;
                payload: {
                    label: string;
                    notes?: string | undefined;
                    stimulus: string;
                };
            };
        });
        removeConcept: (blockId: string, conceptId: string) => ({
            type: "remove concept (features.studies.tabs.stimuli.conceptBlocksLogic)";
            payload: {
                blockId: string;
                conceptId: string;
            };
        });
        reorderConcept: (blockId: string, fromIndex: number, toIndex: number) => ({
            type: "reorder concept (features.studies.tabs.stimuli.conceptBlocksLogic)";
            payload: {
                blockId: string;
                fromIndex: number;
                toIndex: number;
            };
        });
        setError: (error: string | null) => ({
            type: "set error (features.studies.tabs.stimuli.conceptBlocksLogic)";
            payload: {
                error: string | null;
            };
        });
        loadBlocks: () => ({
            type: "load blocks (features.studies.tabs.stimuli.conceptBlocksLogic)";
            payload: any;
        });
        loadBlocksSuccess: (blocks: ConceptBlockRow[], payload?: any) => ({
            type: "load blocks success (features.studies.tabs.stimuli.conceptBlocksLogic)";
            payload: {
                blocks: ConceptBlockRow[];
                payload?: any;
            };
        });
        loadBlocksFailure: (error: string, errorObject?: any) => ({
            type: "load blocks failure (features.studies.tabs.stimuli.conceptBlocksLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
    };
    actionKeys: {
        "create block (features.studies.tabs.stimuli.conceptBlocksLogic)": "createBlock";
        "delete block (features.studies.tabs.stimuli.conceptBlocksLogic)": "deleteBlock";
        "set rotation (features.studies.tabs.stimuli.conceptBlocksLogic)": "setRotation";
        "add concept (features.studies.tabs.stimuli.conceptBlocksLogic)": "addConcept";
        "remove concept (features.studies.tabs.stimuli.conceptBlocksLogic)": "removeConcept";
        "reorder concept (features.studies.tabs.stimuli.conceptBlocksLogic)": "reorderConcept";
        "set error (features.studies.tabs.stimuli.conceptBlocksLogic)": "setError";
        "load blocks (features.studies.tabs.stimuli.conceptBlocksLogic)": "loadBlocks";
        "load blocks success (features.studies.tabs.stimuli.conceptBlocksLogic)": "loadBlocksSuccess";
        "load blocks failure (features.studies.tabs.stimuli.conceptBlocksLogic)": "loadBlocksFailure";
    };
    actionTypes: {
        createBlock: "create block (features.studies.tabs.stimuli.conceptBlocksLogic)";
        deleteBlock: "delete block (features.studies.tabs.stimuli.conceptBlocksLogic)";
        setRotation: "set rotation (features.studies.tabs.stimuli.conceptBlocksLogic)";
        addConcept: "add concept (features.studies.tabs.stimuli.conceptBlocksLogic)";
        removeConcept: "remove concept (features.studies.tabs.stimuli.conceptBlocksLogic)";
        reorderConcept: "reorder concept (features.studies.tabs.stimuli.conceptBlocksLogic)";
        setError: "set error (features.studies.tabs.stimuli.conceptBlocksLogic)";
        loadBlocks: "load blocks (features.studies.tabs.stimuli.conceptBlocksLogic)";
        loadBlocksSuccess: "load blocks success (features.studies.tabs.stimuli.conceptBlocksLogic)";
        loadBlocksFailure: "load blocks failure (features.studies.tabs.stimuli.conceptBlocksLogic)";
    };
    actions: {
        createBlock: (title: string) => void;
        deleteBlock: (blockId: string) => void;
        setRotation: (blockId: string, rotation: Rotation) => void;
        addConcept: (blockId: string, payload: {
            label: string;
            notes?: string;
            stimulus: string;
        }) => void;
        removeConcept: (blockId: string, conceptId: string) => void;
        reorderConcept: (blockId: string, fromIndex: number, toIndex: number) => void;
        setError: (error: string | null) => void;
        loadBlocks: () => void;
        loadBlocksSuccess: (blocks: ConceptBlockRow[], payload?: any) => void;
        loadBlocksFailure: (error: string, errorObject?: any) => void;
    };
    asyncActions: {
        createBlock: (title: string) => Promise<any>;
        deleteBlock: (blockId: string) => Promise<any>;
        setRotation: (blockId: string, rotation: Rotation) => Promise<any>;
        addConcept: (blockId: string, payload: {
            label: string;
            notes?: string;
            stimulus: string;
        }) => Promise<any>;
        removeConcept: (blockId: string, conceptId: string) => Promise<any>;
        reorderConcept: (blockId: string, fromIndex: number, toIndex: number) => Promise<any>;
        setError: (error: string | null) => Promise<any>;
        loadBlocks: () => Promise<any>;
        loadBlocksSuccess: (blocks: ConceptBlockRow[], payload?: any) => Promise<any>;
        loadBlocksFailure: (error: string, errorObject?: any) => Promise<any>;
    };
    defaults: {
        blocks: ConceptBlockRow[];
        blocksLoading: boolean;
        error: string | null;
    };
    events: {};
    key: undefined;
    listeners: {
        "createBlock": ((action: {
            type: "create block (features.studies.tabs.stimuli.conceptBlocksLogic)";
            payload: {
                title: string;
            };
        }, previousState: any) => void | Promise<void>)[];
        "deleteBlock": ((action: {
            type: "delete block (features.studies.tabs.stimuli.conceptBlocksLogic)";
            payload: {
                blockId: string;
            };
        }, previousState: any) => void | Promise<void>)[];
        "setRotation": ((action: {
            type: "set rotation (features.studies.tabs.stimuli.conceptBlocksLogic)";
            payload: {
                blockId: string;
                rotation: Rotation;
            };
        }, previousState: any) => void | Promise<void>)[];
        "addConcept": ((action: {
            type: "add concept (features.studies.tabs.stimuli.conceptBlocksLogic)";
            payload: {
                blockId: string;
                payload: {
                    label: string;
                    notes?: string | undefined;
                    stimulus: string;
                };
            };
        }, previousState: any) => void | Promise<void>)[];
        "removeConcept": ((action: {
            type: "remove concept (features.studies.tabs.stimuli.conceptBlocksLogic)";
            payload: {
                blockId: string;
                conceptId: string;
            };
        }, previousState: any) => void | Promise<void>)[];
        "reorderConcept": ((action: {
            type: "reorder concept (features.studies.tabs.stimuli.conceptBlocksLogic)";
            payload: {
                blockId: string;
                fromIndex: number;
                toIndex: number;
            };
        }, previousState: any) => void | Promise<void>)[];
    };
    path: [
        "features",
        "studies",
        "tabs",
        "stimuli",
        "conceptBlocksLogic"
    ];
    pathString: "features.studies.tabs.stimuli.conceptBlocksLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {
        blocks: ConceptBlockRow[];
        blocksLoading: boolean;
        error: string | null;
    };
    reducers: {
        blocks: (state: ConceptBlockRow[], action: any, fullState: any) => ConceptBlockRow[];
        blocksLoading: (state: boolean, action: any, fullState: any) => boolean;
        error: (state: string | null, action: any, fullState: any) => string | null;
    };
    selector: (state: any) => {
        blocks: ConceptBlockRow[];
        blocksLoading: boolean;
        error: string | null;
    };
    selectors: {
        blocks: (state: any, props?: any) => ConceptBlockRow[];
        blocksLoading: (state: any, props?: any) => boolean;
        error: (state: any, props?: any) => string | null;
        study: (state: any, props?: any) => Study | null;
        studyId: (state: any, props?: any) => string | null;
    };
    sharedListeners: {};
    values: {
        blocks: ConceptBlockRow[];
        blocksLoading: boolean;
        error: string | null;
        study: Study | null;
        studyId: string | null;
    };
    _isKea: true;
    _isKeaWithKey: false;
    __keaTypeGenInternalSelectorTypes: {
        studyId: (study: null | import("~//types").Study) => string | null;
    };
}