// Generated by kea-typegen on Sun, 10 May 2026 07:02:18 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { HomeStats, HomeTab } from './homeLogic'
import type { Study } from '../../types'

export interface homeLogicType extends Logic {
    actionCreators: {
        setActiveTab: (tab: HomeTab) => ({
            type: "set active tab (features.home.homeLogic)";
            payload: {
                tab: HomeTab;
            };
        });
        loadStats: () => ({
            type: "load stats (features.home.homeLogic)";
            payload: any;
        });
        loadStatsSuccess: (stats: HomeStats, payload?: any) => ({
            type: "load stats success (features.home.homeLogic)";
            payload: {
                stats: HomeStats;
                payload?: any;
            };
        });
        loadStatsFailure: (error: string, errorObject?: any) => ({
            type: "load stats failure (features.home.homeLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
        loadStudies: () => ({
            type: "load studies (features.home.homeLogic)";
            payload: any;
        });
        loadStudiesSuccess: (studies: Study[], payload?: any) => ({
            type: "load studies success (features.home.homeLogic)";
            payload: {
                studies: Study[];
                payload?: any;
            };
        });
        loadStudiesFailure: (error: string, errorObject?: any) => ({
            type: "load studies failure (features.home.homeLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
    };
    actionKeys: {
        "set active tab (features.home.homeLogic)": "setActiveTab";
        "load stats (features.home.homeLogic)": "loadStats";
        "load stats success (features.home.homeLogic)": "loadStatsSuccess";
        "load stats failure (features.home.homeLogic)": "loadStatsFailure";
        "load studies (features.home.homeLogic)": "loadStudies";
        "load studies success (features.home.homeLogic)": "loadStudiesSuccess";
        "load studies failure (features.home.homeLogic)": "loadStudiesFailure";
    };
    actionTypes: {
        setActiveTab: "set active tab (features.home.homeLogic)";
        loadStats: "load stats (features.home.homeLogic)";
        loadStatsSuccess: "load stats success (features.home.homeLogic)";
        loadStatsFailure: "load stats failure (features.home.homeLogic)";
        loadStudies: "load studies (features.home.homeLogic)";
        loadStudiesSuccess: "load studies success (features.home.homeLogic)";
        loadStudiesFailure: "load studies failure (features.home.homeLogic)";
    };
    actions: {
        setActiveTab: (tab: HomeTab) => void;
        loadStats: () => void;
        loadStatsSuccess: (stats: HomeStats, payload?: any) => void;
        loadStatsFailure: (error: string, errorObject?: any) => void;
        loadStudies: () => void;
        loadStudiesSuccess: (studies: Study[], payload?: any) => void;
        loadStudiesFailure: (error: string, errorObject?: any) => void;
    };
    asyncActions: {
        setActiveTab: (tab: HomeTab) => Promise<any>;
        loadStats: () => Promise<any>;
        loadStatsSuccess: (stats: HomeStats, payload?: any) => Promise<any>;
        loadStatsFailure: (error: string, errorObject?: any) => Promise<any>;
        loadStudies: () => Promise<any>;
        loadStudiesSuccess: (studies: Study[], payload?: any) => Promise<any>;
        loadStudiesFailure: (error: string, errorObject?: any) => Promise<any>;
    };
    defaults: {
        activeTab: HomeTab;
        stats: HomeStats | null;
        statsLoading: boolean;
        studies: Study[];
        studiesLoading: boolean;
    };
    events: {};
    key: undefined;
    listeners: {};
    path: [
        "features",
        "home",
        "homeLogic"
    ];
    pathString: "features.home.homeLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {
        activeTab: HomeTab;
        stats: HomeStats | null;
        statsLoading: boolean;
        studies: Study[];
        studiesLoading: boolean;
    };
    reducers: {
        activeTab: (state: HomeTab, action: any, fullState: any) => HomeTab;
        stats: (state: HomeStats | null, action: any, fullState: any) => HomeStats | null;
        statsLoading: (state: boolean, action: any, fullState: any) => boolean;
        studies: (state: Study[], action: any, fullState: any) => Study[];
        studiesLoading: (state: boolean, action: any, fullState: any) => boolean;
    };
    selector: (state: any) => {
        activeTab: HomeTab;
        stats: HomeStats | null;
        statsLoading: boolean;
        studies: Study[];
        studiesLoading: boolean;
    };
    selectors: {
        activeTab: (state: any, props?: any) => HomeTab;
        stats: (state: any, props?: any) => HomeStats | null;
        statsLoading: (state: any, props?: any) => boolean;
        studies: (state: any, props?: any) => Study[];
        studiesLoading: (state: any, props?: any) => boolean;
        draftStudies: (state: any, props?: any) => Study[];
        activeStudies: (state: any, props?: any) => Study[];
    };
    sharedListeners: {};
    values: {
        activeTab: HomeTab;
        stats: HomeStats | null;
        statsLoading: boolean;
        studies: Study[];
        studiesLoading: boolean;
        draftStudies: Study[];
        activeStudies: Study[];
    };
    _isKea: true;
    _isKeaWithKey: false;
    __keaTypeGenInternalSelectorTypes: {
        draftStudies: (studies: Study[]) => Study[];
        activeStudies: (studies: Study[]) => Study[];
    };
}