# Generated by Django 5.2.13 on 2026-05-09 18:54

import django.db.models.deletion
import merism.models.study
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("feishu", "Feishu"),
                            ("wecom", "Wecom"),
                            ("wecom_bot", "Wecom Bot"),
                            ("qq_group", "Qq Group"),
                            ("qq_guild", "Qq Guild"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                        ],
                        default="inactive",
                        max_length=16,
                    ),
                ),
                ("credentials_encrypted", models.BinaryField(blank=True, null=True)),
                ("last_healthy_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "merism_channel_config",
            },
        ),
        migrations.CreateModel(
            name="InterviewGuide",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.CharField(default="1.0.0", max_length=16)),
                ("is_current", models.BooleanField(default=True)),
                ("language", models.CharField(default="en", max_length=8)),
                ("sections", models.JSONField(default=list)),
            ],
            options={
                "db_table": "merism_interview_guide",
            },
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("feishu", "Feishu"),
                            ("wecom", "Wecom"),
                            ("wecom_bot", "Wecom Bot"),
                            ("qq_group", "Qq Group"),
                            ("qq_guild", "Qq Guild"),
                        ],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="Shipped by Merism, not team-owned."
                    ),
                ),
            ],
            options={
                "db_table": "merism_message_template",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=64, unique=True)),
            ],
            options={
                "db_table": "merism_organization",
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=200
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("attributes", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "merism_participant",
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=16,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="merism.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merism_org_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "merism_organization_membership",
                "unique_together": {("organization", "user")},
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="members",
            field=models.ManyToManyField(
                related_name="merism_organizations",
                through="merism.OrganizationMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "research_goal",
                    models.TextField(
                        help_text="The single research goal anchoring every AI step."
                    ),
                ),
                ("research_background", models.TextField(blank=True, default="")),
                ("hypothesis", models.TextField(blank=True, default="")),
                ("success_metrics", models.JSONField(blank=True, default=dict)),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=80, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready"),
                            ("recruiting", "Recruiting"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "interview_mode",
                    models.CharField(
                        choices=[
                            ("voice", "Voice"),
                            ("video", "Video"),
                            ("text", "Text"),
                            ("offline", "Offline"),
                        ],
                        default="voice",
                        max_length=16,
                    ),
                ),
                ("estimated_minutes", models.PositiveIntegerField(default=20)),
                (
                    "section_count_override",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("barge_in_enabled", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merism_studies_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "merism_study",
            },
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("direct_link", "Direct Link"),
                            ("cowagent", "Cowagent"),
                            ("email", "Email"),
                            ("behavior_trigger", "Behavior Trigger"),
                        ],
                        default="direct_link",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("started", "Started"),
                            ("consented", "Consented"),
                            ("screened", "Screened"),
                            ("interviewing", "Interviewing"),
                            ("completed", "Completed"),
                            ("dropped", "Dropped"),
                        ],
                        default="invited",
                        max_length=16,
                    ),
                ),
                ("is_preview", models.BooleanField(default=False)),
                ("delivery_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("browser_token", models.UUIDField(default=uuid.uuid4)),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participations",
                        to="merism.participant",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="merism.study",
                    ),
                ),
            ],
            options={
                "db_table": "merism_participation",
            },
        ),
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("voice", "Voice"),
                            ("video", "Video"),
                            ("text", "Text"),
                            ("offline", "Offline"),
                        ],
                        default="voice",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("transcript", models.JSONField(blank=True, default=list)),
                (
                    "audio_s3_key",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "video_s3_key",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("vision_frames", models.JSONField(blank=True, default=list)),
                ("moderator_state", models.JSONField(blank=True, default=dict)),
                ("decision_log", models.JSONField(blank=True, default=list)),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="merism.interviewguide",
                    ),
                ),
                (
                    "participation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="merism.participation",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_sessions",
                        to="merism.study",
                    ),
                ),
            ],
            options={
                "db_table": "merism_interview_session",
            },
        ),
        migrations.AddField(
            model_name="interviewguide",
            name="study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guides",
                to="merism.study",
            ),
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="merism.organization",
                    ),
                ),
            ],
            options={
                "db_table": "merism_team",
            },
        ),
        migrations.CreateModel(
            name="StudyTrigger",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("event", "Event"),
                            ("segment", "Segment"),
                            ("cohort", "Cohort"),
                        ],
                        default="event",
                        max_length=16,
                    ),
                ),
                (
                    "event_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "predicate",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Condition-specific filter. Event → {properties: [...]}.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggers",
                        to="merism.study",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_triggers",
                        to="merism.team",
                    ),
                ),
            ],
            options={
                "db_table": "merism_study_trigger",
            },
        ),
        migrations.CreateModel(
            name="StudyTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pricing", "Pricing"),
                            ("onboarding", "Onboarding"),
                            ("churn", "Churn"),
                            ("concept_test", "Concept Test"),
                            ("usability", "Usability"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                (
                    "interview_mode",
                    models.CharField(
                        choices=[
                            ("voice", "Voice"),
                            ("video", "Video"),
                            ("text", "Text"),
                            ("offline", "Offline"),
                        ],
                        default="voice",
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("is_system", models.BooleanField(default=False)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_templates",
                        to="merism.team",
                    ),
                ),
            ],
            options={
                "db_table": "merism_study_template",
            },
        ),
        migrations.CreateModel(
            name="StudyReport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generating", "Generating"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("content", models.JSONField(blank=True, default=dict)),
                ("charts", models.JSONField(blank=True, default=list)),
                (
                    "generated_by",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="merism.study",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_reports",
                        to="merism.team",
                    ),
                ),
            ],
            options={
                "db_table": "merism_study_report",
            },
        ),
        migrations.CreateModel(
            name="StudyLink",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default=merism.models.study._generate_slug,
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="merism.study",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_links",
                        to="merism.team",
                    ),
                ),
            ],
            options={
                "db_table": "merism_study_link",
            },
        ),
        migrations.CreateModel(
            name="StudyKnowledgeBase",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "study",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kb",
                        to="merism.study",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_kbs",
                        to="merism.team",
                    ),
                ),
            ],
            options={
                "db_table": "merism_study_kb",
            },
        ),
        migrations.AddField(
            model_name="study",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studies",
                to="merism.team",
            ),
        ),
        migrations.CreateModel(
            name="Stimulus",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("text", "Text"),
                            ("pdf", "Pdf"),
                            ("link", "Link"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("content", models.JSONField(blank=True, default=dict)),
                ("linked_question_ids", models.JSONField(blank=True, default=list)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stimuli",
                        to="merism.study",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stimuli",
                        to="merism.team",
                    ),
                ),
            ],
            options={
                "db_table": "merism_stimulus",
            },
        ),
        migrations.CreateModel(
            name="SessionInsight",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("summary", models.TextField(blank=True, default="")),
                ("highlights", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("extracted_tasks", models.JSONField(blank=True, default=list)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insight",
                        to="merism.interviewsession",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_insights",
                        to="merism.team",
                    ),
                ),
            ],
            options={
                "db_table": "merism_session_insight",
            },
        ),
        migrations.CreateModel(
            name="Screener",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("questions", models.JSONField(blank=True, default=list)),
                ("pass_logic", models.JSONField(blank=True, default=dict)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screeners",
                        to="merism.study",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screeners",
                        to="merism.team",
                    ),
                ),
            ],
            options={
                "db_table": "merism_screener",
            },
        ),
        migrations.CreateModel(
            name="RecruitmentBroadcast",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("sending", "Sending"),
                            ("completed", "Completed"),
                            ("partially_failed", "Partially Failed"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("approved_snapshot", models.JSONField(blank=True, default=dict)),
                ("counters", models.JSONField(blank=True, default=dict)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcasts",
                        to="merism.channelconfig",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="broadcasts",
                        to="merism.messagetemplate",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcasts",
                        to="merism.study",
                    ),
                ),
                (
                    "study_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broadcasts",
                        to="merism.studylink",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_broadcasts",
                        to="merism.team",
                    ),
                ),
            ],
            options={
                "db_table": "merism_recruitment_broadcast",
            },
        ),
        migrations.AddField(
            model_name="participation",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participations",
                to="merism.team",
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="merism.team",
            ),
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_templates",
                to="merism.team",
            ),
        ),
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("content", models.TextField(blank=True, default="")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("session_transcript", "Session Transcript"),
                            ("study_report", "Study Report"),
                            ("session_insight", "Session Insight"),
                            ("note", "Note"),
                        ],
                        default="session_transcript",
                        max_length=32,
                    ),
                ),
                ("source_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("indexing", "Indexing"),
                            ("indexed", "Indexed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_documents",
                        to="merism.interviewsession",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_documents",
                        to="merism.study",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_documents",
                        to="merism.team",
                    ),
                ),
            ],
            options={
                "db_table": "merism_knowledge_document",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("chunk_index", models.PositiveIntegerField()),
                ("content", models.TextField()),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="merism.knowledgedocument",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_chunks",
                        to="merism.team",
                    ),
                ),
            ],
            options={
                "db_table": "merism_knowledge_chunk",
            },
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_sessions",
                to="merism.team",
            ),
        ),
        migrations.CreateModel(
            name="InterviewRecording",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("video_s3_key", models.CharField(max_length=512)),
                ("duration_s", models.FloatField(blank=True, null=True)),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recording",
                        to="merism.interviewsession",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_recordings",
                        to="merism.team",
                    ),
                ),
            ],
            options={
                "db_table": "merism_interview_recording",
            },
        ),
        migrations.AddField(
            model_name="interviewguide",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_guides",
                to="merism.team",
            ),
        ),
        migrations.CreateModel(
            name="DeliveryRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recipient_id", models.CharField(db_index=True, max_length=200)),
                ("recipient_kind", models.CharField(default="user", max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "message_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="merism.recruitmentbroadcast",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_records",
                        to="merism.team",
                    ),
                ),
            ],
            options={
                "db_table": "merism_delivery_record",
            },
        ),
        migrations.CreateModel(
            name="CustomReportQuery",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField()),
                ("answer_markdown", models.TextField(blank=True, default="")),
                ("chart_spec", models.JSONField(blank=True, default=dict)),
                ("citations", models.JSONField(blank=True, default=list)),
                ("pinned", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merism_custom_report_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_report_queries",
                        to="merism.study",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_report_queries",
                        to="merism.team",
                    ),
                ),
            ],
            options={
                "db_table": "merism_custom_report_query",
            },
        ),
        migrations.CreateModel(
            name="CoreMemory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("organization", "Organization"),
                            ("team", "Team"),
                            ("user", "User"),
                        ],
                        default="team",
                        max_length=16,
                    ),
                ),
                ("content", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merism_core_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="core_memories",
                        to="merism.team",
                    ),
                ),
            ],
            options={
                "db_table": "merism_core_memory",
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=300)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merism_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="merism.team",
                    ),
                ),
            ],
            options={
                "db_table": "merism_conversation",
            },
        ),
        migrations.CreateModel(
            name="ChannelHealthCheck",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ok", models.BooleanField()),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_checks",
                        to="merism.channelconfig",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_health_checks",
                        to="merism.team",
                    ),
                ),
            ],
            options={
                "db_table": "merism_channel_health_check",
            },
        ),
        migrations.AddField(
            model_name="channelconfig",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_configs",
                to="merism.team",
            ),
        ),
        migrations.CreateModel(
            name="AggregateSynthesis",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("headline", models.TextField(blank=True, default="")),
                ("themes", models.JSONField(blank=True, default=list)),
                ("covered_goals", models.JSONField(blank=True, default=list)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aggregate_syntheses",
                        to="merism.study",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aggregate_syntheses",
                        to="merism.team",
                    ),
                ),
            ],
            options={
                "db_table": "merism_aggregate_synthesis",
            },
        ),
        migrations.CreateModel(
            name="AgentMemory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merism_agent_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_memories",
                        to="merism.team",
                    ),
                ),
            ],
            options={
                "db_table": "merism_agent_memory",
            },
        ),
        migrations.CreateModel(
            name="TeamResearchKnowledgeBase",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Team Research Knowledge Base", max_length=200
                    ),
                ),
                (
                    "embedding_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Override embedding model + dimension here.",
                    ),
                ),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_kb",
                        to="merism.team",
                    ),
                ),
            ],
            options={
                "db_table": "merism_team_research_kb",
            },
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["organization"], name="merism_team_org_idx"),
        ),
        migrations.AddIndex(
            model_name="studytrigger",
            index=models.Index(
                fields=["team", "is_active"], name="merism_trig_team_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studytrigger",
            index=models.Index(fields=["study"], name="merism_trig_study_idx"),
        ),
        migrations.AddIndex(
            model_name="studytemplate",
            index=models.Index(
                fields=["team", "category"], name="merism_tmpl_team_cat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studytemplate",
            index=models.Index(fields=["is_system"], name="merism_tmpl_system_idx"),
        ),
        migrations.AddIndex(
            model_name="studyreport",
            index=models.Index(
                fields=["team", "study"], name="merism_sr_team_study_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studyreport",
            index=models.Index(fields=["status"], name="merism_sr_status_idx"),
        ),
        migrations.AddIndex(
            model_name="studylink",
            index=models.Index(fields=["slug"], name="merism_link_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="studyknowledgebase",
            index=models.Index(
                fields=["team", "study"], name="merism_skb_team_study_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="study",
            index=models.Index(
                fields=["team", "status"], name="merism_study_team_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="study",
            index=models.Index(
                fields=["team", "-created_at"], name="merism_study_team_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stimulus",
            index=models.Index(
                fields=["team", "study"], name="merism_stim_team_study_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stimulus",
            index=models.Index(fields=["kind"], name="merism_stim_kind_idx"),
        ),
        migrations.AddIndex(
            model_name="sessioninsight",
            index=models.Index(fields=["team"], name="merism_si_team_idx"),
        ),
        migrations.AddIndex(
            model_name="screener",
            index=models.Index(
                fields=["team", "study"], name="merism_scr_team_study_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recruitmentbroadcast",
            index=models.Index(
                fields=["team", "status"], name="merism_rb_team_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recruitmentbroadcast",
            index=models.Index(fields=["study"], name="merism_rb_study_idx"),
        ),
        migrations.AddIndex(
            model_name="participation",
            index=models.Index(
                fields=["team", "study", "status"], name="merism_ptn_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="participation",
            index=models.Index(fields=["delivery_id"], name="merism_ptn_delivery_idx"),
        ),
        migrations.AddIndex(
            model_name="participant",
            index=models.Index(
                fields=["team", "external_id"], name="merism_part_extid_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagetemplate",
            index=models.Index(
                fields=["team", "channel_type"], name="merism_mt_team_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagetemplate",
            index=models.Index(fields=["is_system"], name="merism_mt_system_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["team", "source_type"], name="merism_kd_team_src_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(fields=["study"], name="merism_kd_study_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(fields=["status"], name="merism_kd_status_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgechunk",
            index=models.Index(fields=["team"], name="merism_kc_team_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgechunk",
            index=models.Index(
                fields=["document", "chunk_index"], name="merism_kc_doc_order_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="knowledgechunk",
            unique_together={("document", "chunk_index")},
        ),
        migrations.AddIndex(
            model_name="interviewsession",
            index=models.Index(
                fields=["team", "study", "status"], name="merism_sess_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interviewsession",
            index=models.Index(fields=["participation"], name="merism_sess_ptn_idx"),
        ),
        migrations.AddIndex(
            model_name="interviewguide",
            index=models.Index(
                fields=["study", "is_current"], name="merism_guide_current_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="interviewguide",
            constraint=models.UniqueConstraint(
                fields=("study", "version"), name="merism_guide_unique_version"
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryrecord",
            index=models.Index(
                fields=["broadcast", "status"], name="merism_dr_bcast_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryrecord",
            index=models.Index(fields=["recipient_id"], name="merism_dr_rcpt_idx"),
        ),
        migrations.AddIndex(
            model_name="customreportquery",
            index=models.Index(
                fields=["team", "study", "-created_at"], name="merism_crq_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customreportquery",
            index=models.Index(fields=["pinned"], name="merism_crq_pinned_idx"),
        ),
        migrations.AddIndex(
            model_name="corememory",
            index=models.Index(
                fields=["team", "scope"], name="merism_cm_team_scope_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="corememory",
            constraint=models.UniqueConstraint(
                fields=("team", "scope", "user"), name="merism_cm_unique_scope"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["team", "user", "-updated_at"], name="merism_conv_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="channelhealthcheck",
            index=models.Index(
                fields=["channel", "-created_at"], name="merism_chc_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="channelconfig",
            index=models.Index(
                fields=["team", "channel_type"], name="merism_cc_team_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="channelconfig",
            index=models.Index(fields=["status"], name="merism_cc_status_idx"),
        ),
        migrations.AddIndex(
            model_name="aggregatesynthesis",
            index=models.Index(
                fields=["team", "study", "-generated_at"], name="merism_as_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentmemory",
            index=models.Index(
                fields=["team", "is_deleted"], name="merism_am_team_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentmemory",
            index=models.Index(fields=["user"], name="merism_am_user_idx"),
        ),
    ]
