// Generated by kea-typegen on Sun, 10 May 2026 16:53:36 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { BroadcastRow, StudyLinkRow } from './broadcastsLogic'

export interface broadcastsLogicType extends Logic {
    actionCreators: {
        loadBroadcasts: () => ({
            type: "load broadcasts (features.studies.tabs.recruit.broadcastsLogic)";
            payload: any;
        });
        loadBroadcastsSuccess: (broadcasts: BroadcastRow[], payload?: any) => ({
            type: "load broadcasts success (features.studies.tabs.recruit.broadcastsLogic)";
            payload: {
                broadcasts: BroadcastRow[];
                payload?: any;
            };
        });
        loadBroadcastsFailure: (error: string, errorObject?: any) => ({
            type: "load broadcasts failure (features.studies.tabs.recruit.broadcastsLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
        loadStudyLinks: () => ({
            type: "load study links (features.studies.tabs.recruit.broadcastsLogic)";
            payload: any;
        });
        loadStudyLinksSuccess: (studyLinks: StudyLinkRow[], payload?: any) => ({
            type: "load study links success (features.studies.tabs.recruit.broadcastsLogic)";
            payload: {
                studyLinks: StudyLinkRow[];
                payload?: any;
            };
        });
        loadStudyLinksFailure: (error: string, errorObject?: any) => ({
            type: "load study links failure (features.studies.tabs.recruit.broadcastsLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
        createStudyLink: () => ({
            type: "create study link (features.studies.tabs.recruit.broadcastsLogic)";
            payload: any;
        });
        createStudyLinkSuccess: (studyLinks: StudyLinkRow[], payload?: any) => ({
            type: "create study link success (features.studies.tabs.recruit.broadcastsLogic)";
            payload: {
                studyLinks: StudyLinkRow[];
                payload?: any;
            };
        });
        createStudyLinkFailure: (error: string, errorObject?: any) => ({
            type: "create study link failure (features.studies.tabs.recruit.broadcastsLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
    };
    actionKeys: {
        "load broadcasts (features.studies.tabs.recruit.broadcastsLogic)": "loadBroadcasts";
        "load broadcasts success (features.studies.tabs.recruit.broadcastsLogic)": "loadBroadcastsSuccess";
        "load broadcasts failure (features.studies.tabs.recruit.broadcastsLogic)": "loadBroadcastsFailure";
        "load study links (features.studies.tabs.recruit.broadcastsLogic)": "loadStudyLinks";
        "load study links success (features.studies.tabs.recruit.broadcastsLogic)": "loadStudyLinksSuccess";
        "load study links failure (features.studies.tabs.recruit.broadcastsLogic)": "loadStudyLinksFailure";
        "create study link (features.studies.tabs.recruit.broadcastsLogic)": "createStudyLink";
        "create study link success (features.studies.tabs.recruit.broadcastsLogic)": "createStudyLinkSuccess";
        "create study link failure (features.studies.tabs.recruit.broadcastsLogic)": "createStudyLinkFailure";
    };
    actionTypes: {
        loadBroadcasts: "load broadcasts (features.studies.tabs.recruit.broadcastsLogic)";
        loadBroadcastsSuccess: "load broadcasts success (features.studies.tabs.recruit.broadcastsLogic)";
        loadBroadcastsFailure: "load broadcasts failure (features.studies.tabs.recruit.broadcastsLogic)";
        loadStudyLinks: "load study links (features.studies.tabs.recruit.broadcastsLogic)";
        loadStudyLinksSuccess: "load study links success (features.studies.tabs.recruit.broadcastsLogic)";
        loadStudyLinksFailure: "load study links failure (features.studies.tabs.recruit.broadcastsLogic)";
        createStudyLink: "create study link (features.studies.tabs.recruit.broadcastsLogic)";
        createStudyLinkSuccess: "create study link success (features.studies.tabs.recruit.broadcastsLogic)";
        createStudyLinkFailure: "create study link failure (features.studies.tabs.recruit.broadcastsLogic)";
    };
    actions: {
        loadBroadcasts: () => void;
        loadBroadcastsSuccess: (broadcasts: BroadcastRow[], payload?: any) => void;
        loadBroadcastsFailure: (error: string, errorObject?: any) => void;
        loadStudyLinks: () => void;
        loadStudyLinksSuccess: (studyLinks: StudyLinkRow[], payload?: any) => void;
        loadStudyLinksFailure: (error: string, errorObject?: any) => void;
        createStudyLink: () => void;
        createStudyLinkSuccess: (studyLinks: StudyLinkRow[], payload?: any) => void;
        createStudyLinkFailure: (error: string, errorObject?: any) => void;
    };
    asyncActions: {
        loadBroadcasts: () => Promise<any>;
        loadBroadcastsSuccess: (broadcasts: BroadcastRow[], payload?: any) => Promise<any>;
        loadBroadcastsFailure: (error: string, errorObject?: any) => Promise<any>;
        loadStudyLinks: () => Promise<any>;
        loadStudyLinksSuccess: (studyLinks: StudyLinkRow[], payload?: any) => Promise<any>;
        loadStudyLinksFailure: (error: string, errorObject?: any) => Promise<any>;
        createStudyLink: () => Promise<any>;
        createStudyLinkSuccess: (studyLinks: StudyLinkRow[], payload?: any) => Promise<any>;
        createStudyLinkFailure: (error: string, errorObject?: any) => Promise<any>;
    };
    defaults: {
        broadcasts: BroadcastRow[];
        broadcastsLoading: boolean;
        studyLinks: StudyLinkRow[];
        studyLinksLoading: boolean;
    };
    events: {};
    key: undefined;
    listeners: {};
    path: [
        "features",
        "studies",
        "tabs",
        "recruit",
        "broadcastsLogic"
    ];
    pathString: "features.studies.tabs.recruit.broadcastsLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {
        broadcasts: BroadcastRow[];
        broadcastsLoading: boolean;
        studyLinks: StudyLinkRow[];
        studyLinksLoading: boolean;
    };
    reducers: {
        broadcasts: (state: BroadcastRow[], action: any, fullState: any) => BroadcastRow[];
        broadcastsLoading: (state: boolean, action: any, fullState: any) => boolean;
        studyLinks: (state: StudyLinkRow[], action: any, fullState: any) => StudyLinkRow[];
        studyLinksLoading: (state: boolean, action: any, fullState: any) => boolean;
    };
    selector: (state: any) => {
        broadcasts: BroadcastRow[];
        broadcastsLoading: boolean;
        studyLinks: StudyLinkRow[];
        studyLinksLoading: boolean;
    };
    selectors: {
        broadcasts: (state: any, props?: any) => BroadcastRow[];
        broadcastsLoading: (state: any, props?: any) => boolean;
        studyLinks: (state: any, props?: any) => StudyLinkRow[];
        studyLinksLoading: (state: any, props?: any) => boolean;
        studyId: (state: any, props?: any) => string | null;
    };
    sharedListeners: {};
    values: {
        broadcasts: BroadcastRow[];
        broadcastsLoading: boolean;
        studyLinks: StudyLinkRow[];
        studyLinksLoading: boolean;
        studyId: string | null;
    };
    _isKea: true;
    _isKeaWithKey: false;
}