// Generated by kea-typegen on Sun, 10 May 2026 15:03:39 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from "kea";

import type { RecruitmentQuota, Study } from "../../../../types";

export interface recruitPlanLogicType extends Logic {
  actionCreators: {
    loadStudy: () => {
      type: "load study (features.studies.tabs.recruit.recruitPlanLogic)";
      payload: any;
    };
    hydrateFromStudy: (study: Study) => {
      type: "hydrate from study (features.studies.tabs.recruit.recruitPlanLogic)";
      payload: {
        study: Study;
      };
    };
    setAudience: (audience: string) => {
      type: "set audience (features.studies.tabs.recruit.recruitPlanLogic)";
      payload: {
        audience: string;
      };
    };
    setCompletedCount: (count: number) => {
      type: "set completed count (features.studies.tabs.recruit.recruitPlanLogic)";
      payload: {
        count: number;
      };
    };
    setQuotas: (quotas: RecruitmentQuota[]) => {
      type: "set quotas (features.studies.tabs.recruit.recruitPlanLogic)";
      payload: {
        quotas: RecruitmentQuota[];
      };
    };
    openQuotaDialog: (quotaIndex?: number | null) => {
      type: "open quota dialog (features.studies.tabs.recruit.recruitPlanLogic)";
      payload: {
        quotaIndex: number | null;
      };
    };
    closeQuotaDialog: () => {
      type: "close quota dialog (features.studies.tabs.recruit.recruitPlanLogic)";
      payload: {
        value: true;
      };
    };
    setDraftQuota: (quota: RecruitmentQuota | null) => {
      type: "set draft quota (features.studies.tabs.recruit.recruitPlanLogic)";
      payload: {
        quota: RecruitmentQuota | null;
      };
    };
    upsertQuota: (
      index: number | null,
      quota: RecruitmentQuota,
    ) => {
      type: "upsert quota (features.studies.tabs.recruit.recruitPlanLogic)";
      payload: {
        index: number | null;
        quota: RecruitmentQuota;
      };
    };
    removeQuota: (index: number) => {
      type: "remove quota (features.studies.tabs.recruit.recruitPlanLogic)";
      payload: {
        index: number;
      };
    };
    saveRecruitmentPlan: () => {
      type: "save recruitment plan (features.studies.tabs.recruit.recruitPlanLogic)";
      payload: any;
    };
    saveRecruitmentPlanSuccess: (
      savedAt: string | null,
      payload?: any,
    ) => {
      type: "save recruitment plan success (features.studies.tabs.recruit.recruitPlanLogic)";
      payload: {
        savedAt: string | null;
        payload?: any;
      };
    };
    saveRecruitmentPlanFailure: (
      error: string,
      errorObject?: any,
    ) => {
      type: "save recruitment plan failure (features.studies.tabs.recruit.recruitPlanLogic)";
      payload: {
        error: string;
        errorObject?: any;
      };
    };
  };
  actionKeys: {
    "load study (features.studies.tabs.recruit.recruitPlanLogic)": "loadStudy";
    "hydrate from study (features.studies.tabs.recruit.recruitPlanLogic)": "hydrateFromStudy";
    "set audience (features.studies.tabs.recruit.recruitPlanLogic)": "setAudience";
    "set completed count (features.studies.tabs.recruit.recruitPlanLogic)": "setCompletedCount";
    "set quotas (features.studies.tabs.recruit.recruitPlanLogic)": "setQuotas";
    "open quota dialog (features.studies.tabs.recruit.recruitPlanLogic)": "openQuotaDialog";
    "close quota dialog (features.studies.tabs.recruit.recruitPlanLogic)": "closeQuotaDialog";
    "set draft quota (features.studies.tabs.recruit.recruitPlanLogic)": "setDraftQuota";
    "upsert quota (features.studies.tabs.recruit.recruitPlanLogic)": "upsertQuota";
    "remove quota (features.studies.tabs.recruit.recruitPlanLogic)": "removeQuota";
    "save recruitment plan (features.studies.tabs.recruit.recruitPlanLogic)": "saveRecruitmentPlan";
    "save recruitment plan success (features.studies.tabs.recruit.recruitPlanLogic)": "saveRecruitmentPlanSuccess";
    "save recruitment plan failure (features.studies.tabs.recruit.recruitPlanLogic)": "saveRecruitmentPlanFailure";
  };
  actionTypes: {
    loadStudy: "load study (features.studies.tabs.recruit.recruitPlanLogic)";
    hydrateFromStudy: "hydrate from study (features.studies.tabs.recruit.recruitPlanLogic)";
    setAudience: "set audience (features.studies.tabs.recruit.recruitPlanLogic)";
    setCompletedCount: "set completed count (features.studies.tabs.recruit.recruitPlanLogic)";
    setQuotas: "set quotas (features.studies.tabs.recruit.recruitPlanLogic)";
    openQuotaDialog: "open quota dialog (features.studies.tabs.recruit.recruitPlanLogic)";
    closeQuotaDialog: "close quota dialog (features.studies.tabs.recruit.recruitPlanLogic)";
    setDraftQuota: "set draft quota (features.studies.tabs.recruit.recruitPlanLogic)";
    upsertQuota: "upsert quota (features.studies.tabs.recruit.recruitPlanLogic)";
    removeQuota: "remove quota (features.studies.tabs.recruit.recruitPlanLogic)";
    saveRecruitmentPlan: "save recruitment plan (features.studies.tabs.recruit.recruitPlanLogic)";
    saveRecruitmentPlanSuccess: "save recruitment plan success (features.studies.tabs.recruit.recruitPlanLogic)";
    saveRecruitmentPlanFailure: "save recruitment plan failure (features.studies.tabs.recruit.recruitPlanLogic)";
  };
  actions: {
    loadStudy: () => void;
    hydrateFromStudy: (study: Study) => void;
    setAudience: (audience: string) => void;
    setCompletedCount: (count: number) => void;
    setQuotas: (quotas: RecruitmentQuota[]) => void;
    openQuotaDialog: (quotaIndex?: number | null) => void;
    closeQuotaDialog: () => void;
    setDraftQuota: (quota: RecruitmentQuota | null) => void;
    upsertQuota: (index: number | null, quota: RecruitmentQuota) => void;
    removeQuota: (index: number) => void;
    saveRecruitmentPlan: () => void;
    saveRecruitmentPlanSuccess: (savedAt: string | null, payload?: any) => void;
    saveRecruitmentPlanFailure: (error: string, errorObject?: any) => void;
  };
  asyncActions: {
    loadStudy: () => Promise<any>;
    hydrateFromStudy: (study: Study) => Promise<any>;
    setAudience: (audience: string) => Promise<any>;
    setCompletedCount: (count: number) => Promise<any>;
    setQuotas: (quotas: RecruitmentQuota[]) => Promise<any>;
    openQuotaDialog: (quotaIndex?: number | null) => Promise<any>;
    closeQuotaDialog: () => Promise<any>;
    setDraftQuota: (quota: RecruitmentQuota | null) => Promise<any>;
    upsertQuota: (
      index: number | null,
      quota: RecruitmentQuota,
    ) => Promise<any>;
    removeQuota: (index: number) => Promise<any>;
    saveRecruitmentPlan: () => Promise<any>;
    saveRecruitmentPlanSuccess: (
      savedAt: string | null,
      payload?: any,
    ) => Promise<any>;
    saveRecruitmentPlanFailure: (
      error: string,
      errorObject?: any,
    ) => Promise<any>;
  };
  defaults: {
    draftAudience: string;
    draftCount: number;
    draftQuotas: RecruitmentQuota[];
    dialogOpen: boolean;
    editingIndex: number | null;
    stagedQuota: RecruitmentQuota | null;
    savedAt: string | null;
    savedAtLoading: boolean;
  };
  events: {};
  key: undefined;
  listeners: {};
  path: ["features", "studies", "tabs", "recruit", "recruitPlanLogic"];
  pathString: "features.studies.tabs.recruit.recruitPlanLogic";
  props: Record<string, unknown>;
  reducer: (
    state: any,
    action: any,
    fullState: any,
  ) => {
    draftAudience: string;
    draftCount: number;
    draftQuotas: RecruitmentQuota[];
    dialogOpen: boolean;
    editingIndex: number | null;
    stagedQuota: RecruitmentQuota | null;
    savedAt: string | null;
    savedAtLoading: boolean;
  };
  reducers: {
    draftAudience: (state: string, action: any, fullState: any) => string;
    draftCount: (state: number, action: any, fullState: any) => number;
    draftQuotas: (
      state: RecruitmentQuota[],
      action: any,
      fullState: any,
    ) => RecruitmentQuota[];
    dialogOpen: (state: boolean, action: any, fullState: any) => boolean;
    editingIndex: (
      state: number | null,
      action: any,
      fullState: any,
    ) => number | null;
    stagedQuota: (
      state: RecruitmentQuota | null,
      action: any,
      fullState: any,
    ) => RecruitmentQuota | null;
    savedAt: (
      state: string | null,
      action: any,
      fullState: any,
    ) => string | null;
    savedAtLoading: (state: boolean, action: any, fullState: any) => boolean;
  };
  selector: (state: any) => {
    draftAudience: string;
    draftCount: number;
    draftQuotas: RecruitmentQuota[];
    dialogOpen: boolean;
    editingIndex: number | null;
    stagedQuota: RecruitmentQuota | null;
    savedAt: string | null;
    savedAtLoading: boolean;
  };
  selectors: {
    draftAudience: (state: any, props?: any) => string;
    draftCount: (state: any, props?: any) => number;
    draftQuotas: (state: any, props?: any) => RecruitmentQuota[];
    dialogOpen: (state: any, props?: any) => boolean;
    editingIndex: (state: any, props?: any) => number | null;
    stagedQuota: (state: any, props?: any) => RecruitmentQuota | null;
    savedAt: (state: any, props?: any) => string | null;
    savedAtLoading: (state: any, props?: any) => boolean;
    study: (state: any, props?: any) => Study | null;
    studyId: (state: any, props?: any) => string | null;
    totalQuotaTargets: (state: any, props?: any) => number;
    hasUnsavedChanges: (state: any, props?: any) => boolean;
  };
  sharedListeners: {};
  values: {
    draftAudience: string;
    draftCount: number;
    draftQuotas: RecruitmentQuota[];
    dialogOpen: boolean;
    editingIndex: number | null;
    stagedQuota: RecruitmentQuota | null;
    savedAt: string | null;
    savedAtLoading: boolean;
    study: Study | null;
    studyId: string | null;
    totalQuotaTargets: number;
    hasUnsavedChanges: boolean;
  };
  _isKea: true;
  _isKeaWithKey: false;
  __keaTypeGenInternalSelectorTypes: {
    totalQuotaTargets: (draftQuotas: RecruitmentQuota[]) => number;
    hasUnsavedChanges: (
      study: Study | null,
      draftAudience: string,
      draftCount: number,
      draftQuotas: RecruitmentQuota[],
    ) => boolean;
  };
}
