// Generated by kea-typegen on Sat, 09 May 2026 18:41:14 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from "kea";

import type { Study } from "../types";

export interface studiesModelType extends Logic {
  actionCreators: {
    loadStudies: () => {
      type: "load studies (models.studiesModel)";
      payload: any;
    };
    loadStudiesSuccess: (
      studies: Study[],
      payload?: any,
    ) => {
      type: "load studies success (models.studiesModel)";
      payload: {
        studies: Study[];
        payload?: any;
      };
    };
    loadStudiesFailure: (
      error: string,
      errorObject?: any,
    ) => {
      type: "load studies failure (models.studiesModel)";
      payload: {
        error: string;
        errorObject?: any;
      };
    };
  };
  actionKeys: {
    "load studies (models.studiesModel)": "loadStudies";
    "load studies success (models.studiesModel)": "loadStudiesSuccess";
    "load studies failure (models.studiesModel)": "loadStudiesFailure";
  };
  actionTypes: {
    loadStudies: "load studies (models.studiesModel)";
    loadStudiesSuccess: "load studies success (models.studiesModel)";
    loadStudiesFailure: "load studies failure (models.studiesModel)";
  };
  actions: {
    loadStudies: () => void;
    loadStudiesSuccess: (studies: Study[], payload?: any) => void;
    loadStudiesFailure: (error: string, errorObject?: any) => void;
  };
  asyncActions: {
    loadStudies: () => Promise<any>;
    loadStudiesSuccess: (studies: Study[], payload?: any) => Promise<any>;
    loadStudiesFailure: (error: string, errorObject?: any) => Promise<any>;
  };
  defaults: {
    studies: Study[];
    studiesLoading: boolean;
  };
  events: {};
  key: undefined;
  listeners: {};
  path: ["models", "studiesModel"];
  pathString: "models.studiesModel";
  props: Record<string, unknown>;
  reducer: (
    state: any,
    action: any,
    fullState: any,
  ) => {
    studies: Study[];
    studiesLoading: boolean;
  };
  reducers: {
    studies: (state: Study[], action: any, fullState: any) => Study[];
    studiesLoading: (state: boolean, action: any, fullState: any) => boolean;
  };
  selector: (state: any) => {
    studies: Study[];
    studiesLoading: boolean;
  };
  selectors: {
    studies: (state: any, props?: any) => Study[];
    studiesLoading: (state: any, props?: any) => boolean;
    studyById: (state: any, props?: any) => (id: string) => Study | undefined;
    activeStudies: (state: any, props?: any) => Study[];
  };
  sharedListeners: {};
  values: {
    studies: Study[];
    studiesLoading: boolean;
    studyById: (id: string) => Study | undefined;
    activeStudies: Study[];
  };
  _isKea: true;
  _isKeaWithKey: false;
  __keaTypeGenInternalSelectorTypes: {
    studyById: (studies: Study[]) => (id: string) => Study | undefined;
    activeStudies: (studies: Study[]) => Study[];
  };
}
