// Generated by kea-typegen on Sat, 09 May 2026 18:41:16 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { Organization, Team, User } from '../types'

export interface teamLogicType extends Logic {
    actionCreators: {};
    actionKeys: {};
    actionTypes: {};
    actions: {};
    asyncActions: {};
    defaults: {};
    events: {};
    key: undefined;
    listeners: {};
    path: [
        "models",
        "teamLogic"
    ];
    pathString: "models.teamLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {};
    reducers: {};
    selector: (state: any) => {};
    selectors: {
        user: (state: any, props?: any) => User | null;
        currentTeam: (state: any, props?: any) => Team | null;
        currentTeamId: (state: any, props?: any) => string | null;
        currentOrganization: (state: any, props?: any) => Organization | null;
    };
    sharedListeners: {};
    values: {
        user: User | null;
        currentTeam: Team | null;
        currentTeamId: string | null;
        currentOrganization: Organization | null;
    };
    _isKea: true;
    _isKeaWithKey: false;
    __keaTypeGenInternalSelectorTypes: {
        currentTeam: (user: null | import("/home/jia/posthog-foss/merism-app/frontend/src/types").User) => Team | null;
        currentTeamId: (user: null | import("/home/jia/posthog-foss/merism-app/frontend/src/types").User) => string | null;
        currentOrganization: (user: null | import("/home/jia/posthog-foss/merism-app/frontend/src/types").User) => Organization | null;
    };
}