// Generated by kea-typegen on Sat, 09 May 2026 18:41:14 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { User } from '../types'

export interface userLogicType extends Logic {
    actionCreators: {
        loadUser: () => ({
            type: "load user (models.userLogic)";
            payload: any;
        });
        loadUserSuccess: (user: User | null, payload?: any) => ({
            type: "load user success (models.userLogic)";
            payload: {
                user: User | null;
                payload?: any;
            };
        });
        loadUserFailure: (error: string, errorObject?: any) => ({
            type: "load user failure (models.userLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
    };
    actionKeys: {
        "load user (models.userLogic)": "loadUser";
        "load user success (models.userLogic)": "loadUserSuccess";
        "load user failure (models.userLogic)": "loadUserFailure";
    };
    actionTypes: {
        loadUser: "load user (models.userLogic)";
        loadUserSuccess: "load user success (models.userLogic)";
        loadUserFailure: "load user failure (models.userLogic)";
    };
    actions: {
        loadUser: () => void;
        loadUserSuccess: (user: User | null, payload?: any) => void;
        loadUserFailure: (error: string, errorObject?: any) => void;
    };
    asyncActions: {
        loadUser: () => Promise<any>;
        loadUserSuccess: (user: User | null, payload?: any) => Promise<any>;
        loadUserFailure: (error: string, errorObject?: any) => Promise<any>;
    };
    defaults: {
        user: User | null;
        userLoading: boolean;
    };
    events: {};
    key: undefined;
    listeners: {};
    path: [
        "models",
        "userLogic"
    ];
    pathString: "models.userLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {
        user: User | null;
        userLoading: boolean;
    };
    reducers: {
        user: (state: User | null, action: any, fullState: any) => User | null;
        userLoading: (state: boolean, action: any, fullState: any) => boolean;
    };
    selector: (state: any) => {
        user: User | null;
        userLoading: boolean;
    };
    selectors: {
        user: (state: any, props?: any) => User | null;
        userLoading: (state: any, props?: any) => boolean;
        isAuthenticated: (state: any, props?: any) => boolean;
        currentTeamId: (state: any, props?: any) => string | null;
    };
    sharedListeners: {};
    values: {
        user: User | null;
        userLoading: boolean;
        isAuthenticated: boolean;
        currentTeamId: string | null;
    };
    _isKea: true;
    _isKeaWithKey: false;
    __keaTypeGenInternalSelectorTypes: {
        isAuthenticated: (user: User | null) => boolean;
        currentTeamId: (user: User | null) => string | null;
    };
}