// Generated by kea-typegen on Sun, 10 May 2026 14:20:48 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from "kea";

import type { StudyAggregate, StudyNarrative } from "./analysisLogic";

export interface analysisLogicType extends Logic {
  actionCreators: {
    refreshNarrative: () => {
      type: "refresh narrative (features.studies.tabs.analysis.analysisLogic)";
      payload: {
        value: true;
      };
    };
    loadAggregate: () => {
      type: "load aggregate (features.studies.tabs.analysis.analysisLogic)";
      payload: any;
    };
    loadAggregateSuccess: (
      aggregate: StudyAggregate | null,
      payload?: any,
    ) => {
      type: "load aggregate success (features.studies.tabs.analysis.analysisLogic)";
      payload: {
        aggregate: StudyAggregate | null;
        payload?: any;
      };
    };
    loadAggregateFailure: (
      error: string,
      errorObject?: any,
    ) => {
      type: "load aggregate failure (features.studies.tabs.analysis.analysisLogic)";
      payload: {
        error: string;
        errorObject?: any;
      };
    };
    refreshNarrativeSuccess: (
      narrative: StudyNarrative | null,
      payload?: {
        value: true;
      },
    ) => {
      type: "refresh narrative success (features.studies.tabs.analysis.analysisLogic)";
      payload: {
        narrative: StudyNarrative | null;
        payload?: {
          value: true;
        };
      };
    };
    refreshNarrativeFailure: (
      error: string,
      errorObject?: any,
    ) => {
      type: "refresh narrative failure (features.studies.tabs.analysis.analysisLogic)";
      payload: {
        error: string;
        errorObject?: any;
      };
    };
  };
  actionKeys: {
    "refresh narrative (features.studies.tabs.analysis.analysisLogic)": "refreshNarrative";
    "load aggregate (features.studies.tabs.analysis.analysisLogic)": "loadAggregate";
    "load aggregate success (features.studies.tabs.analysis.analysisLogic)": "loadAggregateSuccess";
    "load aggregate failure (features.studies.tabs.analysis.analysisLogic)": "loadAggregateFailure";
    "refresh narrative success (features.studies.tabs.analysis.analysisLogic)": "refreshNarrativeSuccess";
    "refresh narrative failure (features.studies.tabs.analysis.analysisLogic)": "refreshNarrativeFailure";
  };
  actionTypes: {
    refreshNarrative: "refresh narrative (features.studies.tabs.analysis.analysisLogic)";
    loadAggregate: "load aggregate (features.studies.tabs.analysis.analysisLogic)";
    loadAggregateSuccess: "load aggregate success (features.studies.tabs.analysis.analysisLogic)";
    loadAggregateFailure: "load aggregate failure (features.studies.tabs.analysis.analysisLogic)";
    refreshNarrativeSuccess: "refresh narrative success (features.studies.tabs.analysis.analysisLogic)";
    refreshNarrativeFailure: "refresh narrative failure (features.studies.tabs.analysis.analysisLogic)";
  };
  actions: {
    refreshNarrative: () => void;
    loadAggregate: () => void;
    loadAggregateSuccess: (
      aggregate: StudyAggregate | null,
      payload?: any,
    ) => void;
    loadAggregateFailure: (error: string, errorObject?: any) => void;
    refreshNarrativeSuccess: (
      narrative: StudyNarrative | null,
      payload?: {
        value: true;
      },
    ) => void;
    refreshNarrativeFailure: (error: string, errorObject?: any) => void;
  };
  asyncActions: {
    refreshNarrative: () => Promise<any>;
    loadAggregate: () => Promise<any>;
    loadAggregateSuccess: (
      aggregate: StudyAggregate | null,
      payload?: any,
    ) => Promise<any>;
    loadAggregateFailure: (error: string, errorObject?: any) => Promise<any>;
    refreshNarrativeSuccess: (
      narrative: StudyNarrative | null,
      payload?: {
        value: true;
      },
    ) => Promise<any>;
    refreshNarrativeFailure: (error: string, errorObject?: any) => Promise<any>;
  };
  defaults: {
    aggregate: StudyAggregate | null;
    aggregateLoading: boolean;
    narrative: StudyNarrative | null;
    narrativeLoading: boolean;
  };
  events: {};
  key: undefined;
  listeners: {};
  path: ["features", "studies", "tabs", "analysis", "analysisLogic"];
  pathString: "features.studies.tabs.analysis.analysisLogic";
  props: Record<string, unknown>;
  reducer: (
    state: any,
    action: any,
    fullState: any,
  ) => {
    aggregate: StudyAggregate | null;
    aggregateLoading: boolean;
    narrative: StudyNarrative | null;
    narrativeLoading: boolean;
  };
  reducers: {
    aggregate: (
      state: StudyAggregate | null,
      action: any,
      fullState: any,
    ) => StudyAggregate | null;
    aggregateLoading: (state: boolean, action: any, fullState: any) => boolean;
    narrative: (
      state: StudyNarrative | null,
      action: any,
      fullState: any,
    ) => StudyNarrative | null;
    narrativeLoading: (state: boolean, action: any, fullState: any) => boolean;
  };
  selector: (state: any) => {
    aggregate: StudyAggregate | null;
    aggregateLoading: boolean;
    narrative: StudyNarrative | null;
    narrativeLoading: boolean;
  };
  selectors: {
    aggregate: (state: any, props?: any) => StudyAggregate | null;
    aggregateLoading: (state: any, props?: any) => boolean;
    narrative: (state: any, props?: any) => StudyNarrative | null;
    narrativeLoading: (state: any, props?: any) => boolean;
    studyId: (state: any, props?: any) => string | null;
    hasData: (state: any, props?: any) => boolean;
    sentimentDistList: (
      state: any,
      props?: any,
    ) => {
      key: string;
      value: number;
    }[];
  };
  sharedListeners: {};
  values: {
    aggregate: StudyAggregate | null;
    aggregateLoading: boolean;
    narrative: StudyNarrative | null;
    narrativeLoading: boolean;
    studyId: string | null;
    hasData: boolean;
    sentimentDistList: {
      key: string;
      value: number;
    }[];
  };
  _isKea: true;
  _isKeaWithKey: false;
  __keaTypeGenInternalSelectorTypes: {
    hasData: (aggregate: StudyAggregate | null) => boolean;
    sentimentDistList: (aggregate: StudyAggregate | null) => {
      key: string;
      value: number;
    }[];
  };
}
