// Generated by kea-typegen on Sun, 10 May 2026 03:57:12 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from "kea";

import type { Study } from "../../../../types";
import type { ConceptReport } from "./conceptReportLogic";

export interface conceptReportLogicType extends Logic {
  actionCreators: {
    loadReports: () => {
      type: "load reports (features.studies.tabs.analysis.conceptReportLogic)";
      payload: any;
    };
    loadReportsSuccess: (
      reports: ConceptReport[],
      payload?: any,
    ) => {
      type: "load reports success (features.studies.tabs.analysis.conceptReportLogic)";
      payload: {
        reports: ConceptReport[];
        payload?: any;
      };
    };
    loadReportsFailure: (
      error: string,
      errorObject?: any,
    ) => {
      type: "load reports failure (features.studies.tabs.analysis.conceptReportLogic)";
      payload: {
        error: string;
        errorObject?: any;
      };
    };
  };
  actionKeys: {
    "load reports (features.studies.tabs.analysis.conceptReportLogic)": "loadReports";
    "load reports success (features.studies.tabs.analysis.conceptReportLogic)": "loadReportsSuccess";
    "load reports failure (features.studies.tabs.analysis.conceptReportLogic)": "loadReportsFailure";
  };
  actionTypes: {
    loadReports: "load reports (features.studies.tabs.analysis.conceptReportLogic)";
    loadReportsSuccess: "load reports success (features.studies.tabs.analysis.conceptReportLogic)";
    loadReportsFailure: "load reports failure (features.studies.tabs.analysis.conceptReportLogic)";
  };
  actions: {
    loadReports: () => void;
    loadReportsSuccess: (reports: ConceptReport[], payload?: any) => void;
    loadReportsFailure: (error: string, errorObject?: any) => void;
  };
  asyncActions: {
    loadReports: () => Promise<any>;
    loadReportsSuccess: (
      reports: ConceptReport[],
      payload?: any,
    ) => Promise<any>;
    loadReportsFailure: (error: string, errorObject?: any) => Promise<any>;
  };
  defaults: {
    reports: ConceptReport[];
    reportsLoading: boolean;
  };
  events: {};
  key: undefined;
  listeners: {};
  path: ["features", "studies", "tabs", "analysis", "conceptReportLogic"];
  pathString: "features.studies.tabs.analysis.conceptReportLogic";
  props: Record<string, unknown>;
  reducer: (
    state: any,
    action: any,
    fullState: any,
  ) => {
    reports: ConceptReport[];
    reportsLoading: boolean;
  };
  reducers: {
    reports: (
      state: ConceptReport[],
      action: any,
      fullState: any,
    ) => ConceptReport[];
    reportsLoading: (state: boolean, action: any, fullState: any) => boolean;
  };
  selector: (state: any) => {
    reports: ConceptReport[];
    reportsLoading: boolean;
  };
  selectors: {
    reports: (state: any, props?: any) => ConceptReport[];
    reportsLoading: (state: any, props?: any) => boolean;
    study: (state: any, props?: any) => Study | null;
    hasReports: (state: any, props?: any) => boolean;
  };
  sharedListeners: {};
  values: {
    reports: ConceptReport[];
    reportsLoading: boolean;
    study: Study | null;
    hasReports: boolean;
  };
  _isKea: true;
  _isKeaWithKey: false;
  __keaTypeGenInternalSelectorTypes: {
    hasReports: (reports: ConceptReport[]) => boolean;
  };
}
