// Generated by kea-typegen on Sat, 09 May 2026 18:41:10 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { CustomReportMessage } from './customReportLogic'

export interface customReportLogicType extends Logic {
    actionCreators: {
        openFor: (studyId: string) => ({
            type: "open for (scenes.custom_report.customReportLogic)";
            payload: {
                studyId: string;
            };
        });
        close: () => ({
            type: "close (scenes.custom_report.customReportLogic)";
            payload: {
                value: true;
            };
        });
        askQuestion: (question: string) => ({
            type: "ask question (scenes.custom_report.customReportLogic)";
            payload: {
                question: string;
            };
        });
        pushMessage: (message: CustomReportMessage) => ({
            type: "push message (scenes.custom_report.customReportLogic)";
            payload: {
                message: CustomReportMessage;
            };
        });
        updateMessage: (id: string, patch: Partial<CustomReportMessage>) => ({
            type: "update message (scenes.custom_report.customReportLogic)";
            payload: {
                id: string;
                patch: Partial<CustomReportMessage>;
            };
        });
        setSending: (sending: boolean) => ({
            type: "set sending (scenes.custom_report.customReportLogic)";
            payload: {
                sending: boolean;
            };
        });
        togglePin: (id: string) => ({
            type: "toggle pin (scenes.custom_report.customReportLogic)";
            payload: {
                id: string;
            };
        });
    };
    actionKeys: {
        "open for (scenes.custom_report.customReportLogic)": "openFor";
        "close (scenes.custom_report.customReportLogic)": "close";
        "ask question (scenes.custom_report.customReportLogic)": "askQuestion";
        "push message (scenes.custom_report.customReportLogic)": "pushMessage";
        "update message (scenes.custom_report.customReportLogic)": "updateMessage";
        "set sending (scenes.custom_report.customReportLogic)": "setSending";
        "toggle pin (scenes.custom_report.customReportLogic)": "togglePin";
    };
    actionTypes: {
        openFor: "open for (scenes.custom_report.customReportLogic)";
        close: "close (scenes.custom_report.customReportLogic)";
        askQuestion: "ask question (scenes.custom_report.customReportLogic)";
        pushMessage: "push message (scenes.custom_report.customReportLogic)";
        updateMessage: "update message (scenes.custom_report.customReportLogic)";
        setSending: "set sending (scenes.custom_report.customReportLogic)";
        togglePin: "toggle pin (scenes.custom_report.customReportLogic)";
    };
    actions: {
        openFor: (studyId: string) => void;
        close: () => void;
        askQuestion: (question: string) => void;
        pushMessage: (message: CustomReportMessage) => void;
        updateMessage: (id: string, patch: Partial<CustomReportMessage>) => void;
        setSending: (sending: boolean) => void;
        togglePin: (id: string) => void;
    };
    asyncActions: {
        openFor: (studyId: string) => Promise<any>;
        close: () => Promise<any>;
        askQuestion: (question: string) => Promise<any>;
        pushMessage: (message: CustomReportMessage) => Promise<any>;
        updateMessage: (id: string, patch: Partial<CustomReportMessage>) => Promise<any>;
        setSending: (sending: boolean) => Promise<any>;
        togglePin: (id: string) => Promise<any>;
    };
    defaults: {
        open: boolean;
        studyId: string | null;
        messages: CustomReportMessage[];
        isSending: boolean;
    };
    events: {};
    key: undefined;
    listeners: {
        "askQuestion": ((action: {
            type: "ask question (scenes.custom_report.customReportLogic)";
            payload: {
                question: string;
            };
        }, previousState: any) => void | Promise<void>)[];
    };
    path: [
        "scenes",
        "custom_report",
        "customReportLogic"
    ];
    pathString: "scenes.custom_report.customReportLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {
        open: boolean;
        studyId: string | null;
        messages: CustomReportMessage[];
        isSending: boolean;
    };
    reducers: {
        open: (state: boolean, action: any, fullState: any) => boolean;
        studyId: (state: string | null, action: any, fullState: any) => string | null;
        messages: (state: CustomReportMessage[], action: any, fullState: any) => CustomReportMessage[];
        isSending: (state: boolean, action: any, fullState: any) => boolean;
    };
    selector: (state: any) => {
        open: boolean;
        studyId: string | null;
        messages: CustomReportMessage[];
        isSending: boolean;
    };
    selectors: {
        open: (state: any, props?: any) => boolean;
        studyId: (state: any, props?: any) => string | null;
        messages: (state: any, props?: any) => CustomReportMessage[];
        isSending: (state: any, props?: any) => boolean;
    };
    sharedListeners: {};
    values: {
        open: boolean;
        studyId: string | null;
        messages: CustomReportMessage[];
        isSending: boolean;
    };
    _isKea: true;
    _isKeaWithKey: false;
}