// Generated by kea-typegen on Sat, 09 May 2026 19:18:16 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { Study } from '../../../../types'
import type { WizardStep } from './briefWizardLogic'
import type { DeepPartial, DeepPartialMap, FieldName, ValidationErrorType } from 'kea-forms'
import type { ZodBoolean, ZodDefault, ZodEnum, ZodNumber, ZodObject, ZodString, ZodTypeAny } from 'zod'

export interface briefWizardLogicType extends Logic {
    actionCreators: {
        loadStudy: () => ({
            type: "load study (features.studies.briefWizardLogic)";
            payload: any;
        });
        goToStep: (step: WizardStep) => ({
            type: "go to step (features.studies.briefWizardLogic)";
            payload: {
                step: "done" | "goal" | "mode" | "plan" | "review";
            };
        });
        next: () => ({
            type: "next (features.studies.briefWizardLogic)";
            payload: {
                value: true;
            };
        });
        back: () => ({
            type: "back (features.studies.briefWizardLogic)";
            payload: {
                value: true;
            };
        });
        hydrateFromStudy: (study: Study) => ({
            type: "hydrate from study (features.studies.briefWizardLogic)";
            payload: {
                study: Study;
            };
        });
        setBriefValue: (key: FieldName, value: any) => ({
            type: "set brief value (features.studies.briefWizardLogic)";
            payload: {
                name: FieldName;
                value: any;
            };
        });
        setBriefValues: (values: DeepPartial<{
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis: string;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background: string;
            research_goal: string;
        }>) => ({
            type: "set brief values (features.studies.briefWizardLogic)";
            payload: {
                values: DeepPartial<{
                    barge_in_enabled: boolean;
                    estimated_minutes: number;
                    hypothesis: string;
                    interview_mode: "offline" | "text" | "video" | "voice";
                    research_background: string;
                    research_goal: string;
                }>;
            };
        });
        setBriefManualErrors: (errors: Record<string, any>) => ({
            type: "set brief manual errors (features.studies.briefWizardLogic)";
            payload: {
                errors: Record<string, any>;
            };
        });
        touchBriefField: (key: string) => ({
            type: "touch brief field (features.studies.briefWizardLogic)";
            payload: {
                key: string;
            };
        });
        resetBrief: (values?: {
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis: string;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background: string;
            research_goal: string;
        }) => ({
            type: "reset brief (features.studies.briefWizardLogic)";
            payload: {
                values?: {
                    barge_in_enabled: boolean;
                    estimated_minutes: number;
                    hypothesis: string;
                    interview_mode: "offline" | "text" | "video" | "voice";
                    research_background: string;
                    research_goal: string;
                };
            };
        });
        submitBrief: () => ({
            type: "submit brief (features.studies.briefWizardLogic)";
            payload: {
                value: boolean;
            };
        });
        submitBriefRequest: (brief: {
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis: string;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background: string;
            research_goal: string;
        }) => ({
            type: "submit brief request (features.studies.briefWizardLogic)";
            payload: {
                brief: {
                    barge_in_enabled: boolean;
                    estimated_minutes: number;
                    hypothesis: string;
                    interview_mode: "offline" | "text" | "video" | "voice";
                    research_background: string;
                    research_goal: string;
                };
            };
        });
        submitBriefSuccess: (brief: {
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis: string;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background: string;
            research_goal: string;
        }) => ({
            type: "submit brief success (features.studies.briefWizardLogic)";
            payload: {
                brief: {
                    barge_in_enabled: boolean;
                    estimated_minutes: number;
                    hypothesis: string;
                    interview_mode: "offline" | "text" | "video" | "voice";
                    research_background: string;
                    research_goal: string;
                };
            };
        });
        submitBriefFailure: (error: Error, errors: Record<string, any>) => ({
            type: "submit brief failure (features.studies.briefWizardLogic)";
            payload: {
                error: Error;
                errors: Record<string, any>;
            };
        });
    };
    actionKeys: {
        "load study (features.studies.briefWizardLogic)": "loadStudy";
        "go to step (features.studies.briefWizardLogic)": "goToStep";
        "next (features.studies.briefWizardLogic)": "next";
        "back (features.studies.briefWizardLogic)": "back";
        "hydrate from study (features.studies.briefWizardLogic)": "hydrateFromStudy";
        "set brief value (features.studies.briefWizardLogic)": "setBriefValue";
        "set brief values (features.studies.briefWizardLogic)": "setBriefValues";
        "set brief manual errors (features.studies.briefWizardLogic)": "setBriefManualErrors";
        "touch brief field (features.studies.briefWizardLogic)": "touchBriefField";
        "reset brief (features.studies.briefWizardLogic)": "resetBrief";
        "submit brief (features.studies.briefWizardLogic)": "submitBrief";
        "submit brief request (features.studies.briefWizardLogic)": "submitBriefRequest";
        "submit brief success (features.studies.briefWizardLogic)": "submitBriefSuccess";
        "submit brief failure (features.studies.briefWizardLogic)": "submitBriefFailure";
    };
    actionTypes: {
        loadStudy: "load study (features.studies.briefWizardLogic)";
        goToStep: "go to step (features.studies.briefWizardLogic)";
        next: "next (features.studies.briefWizardLogic)";
        back: "back (features.studies.briefWizardLogic)";
        hydrateFromStudy: "hydrate from study (features.studies.briefWizardLogic)";
        setBriefValue: "set brief value (features.studies.briefWizardLogic)";
        setBriefValues: "set brief values (features.studies.briefWizardLogic)";
        setBriefManualErrors: "set brief manual errors (features.studies.briefWizardLogic)";
        touchBriefField: "touch brief field (features.studies.briefWizardLogic)";
        resetBrief: "reset brief (features.studies.briefWizardLogic)";
        submitBrief: "submit brief (features.studies.briefWizardLogic)";
        submitBriefRequest: "submit brief request (features.studies.briefWizardLogic)";
        submitBriefSuccess: "submit brief success (features.studies.briefWizardLogic)";
        submitBriefFailure: "submit brief failure (features.studies.briefWizardLogic)";
    };
    actions: {
        loadStudy: () => void;
        goToStep: (step: WizardStep) => void;
        next: () => void;
        back: () => void;
        hydrateFromStudy: (study: Study) => void;
        setBriefValue: (key: FieldName, value: any) => void;
        setBriefValues: (values: DeepPartial<{
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis: string;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background: string;
            research_goal: string;
        }>) => void;
        setBriefManualErrors: (errors: Record<string, any>) => void;
        touchBriefField: (key: string) => void;
        resetBrief: (values?: {
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis: string;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background: string;
            research_goal: string;
        }) => void;
        submitBrief: () => void;
        submitBriefRequest: (brief: {
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis: string;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background: string;
            research_goal: string;
        }) => void;
        submitBriefSuccess: (brief: {
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis: string;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background: string;
            research_goal: string;
        }) => void;
        submitBriefFailure: (error: Error, errors: Record<string, any>) => void;
    };
    asyncActions: {
        loadStudy: () => Promise<any>;
        goToStep: (step: WizardStep) => Promise<any>;
        next: () => Promise<any>;
        back: () => Promise<any>;
        hydrateFromStudy: (study: Study) => Promise<any>;
        setBriefValue: (key: FieldName, value: any) => Promise<any>;
        setBriefValues: (values: DeepPartial<{
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis: string;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background: string;
            research_goal: string;
        }>) => Promise<any>;
        setBriefManualErrors: (errors: Record<string, any>) => Promise<any>;
        touchBriefField: (key: string) => Promise<any>;
        resetBrief: (values?: {
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis: string;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background: string;
            research_goal: string;
        }) => Promise<any>;
        submitBrief: () => Promise<any>;
        submitBriefRequest: (brief: {
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis: string;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background: string;
            research_goal: string;
        }) => Promise<any>;
        submitBriefSuccess: (brief: {
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis: string;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background: string;
            research_goal: string;
        }) => Promise<any>;
        submitBriefFailure: (error: Error, errors: Record<string, any>) => Promise<any>;
    };
    defaults: {
        step: WizardStep;
        brief: {
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis: string;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background: string;
            research_goal: string;
        };
        isBriefSubmitting: boolean;
        showBriefErrors: boolean;
        briefChanged: boolean;
        briefTouches: Record<string, boolean>;
        briefManualErrors: Record<string, any>;
    };
    events: {};
    key: undefined;
    listeners: {
        "hydrateFromStudy": ((action: {
            type: "hydrate from study (features.studies.briefWizardLogic)";
            payload: {
                study: Study;
            };
        }, previousState: any) => void | Promise<void>)[];
    };
    path: [
        "features",
        "studies",
        "briefWizardLogic"
    ];
    pathString: "features.studies.briefWizardLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {
        step: WizardStep;
        brief: {
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis: string;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background: string;
            research_goal: string;
        };
        isBriefSubmitting: boolean;
        showBriefErrors: boolean;
        briefChanged: boolean;
        briefTouches: Record<string, boolean>;
        briefManualErrors: Record<string, any>;
    };
    reducers: {
        step: (state: WizardStep, action: any, fullState: any) => WizardStep;
        brief: (state: {
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis: string;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background: string;
            research_goal: string;
        }, action: any, fullState: any) => {
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis: string;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background: string;
            research_goal: string;
        };
        isBriefSubmitting: (state: boolean, action: any, fullState: any) => boolean;
        showBriefErrors: (state: boolean, action: any, fullState: any) => boolean;
        briefChanged: (state: boolean, action: any, fullState: any) => boolean;
        briefTouches: (state: Record<string, boolean>, action: any, fullState: any) => Record<string, boolean>;
        briefManualErrors: (state: Record<string, any>, action: any, fullState: any) => Record<string, any>;
    };
    selector: (state: any) => {
        step: WizardStep;
        brief: {
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis: string;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background: string;
            research_goal: string;
        };
        isBriefSubmitting: boolean;
        showBriefErrors: boolean;
        briefChanged: boolean;
        briefTouches: Record<string, boolean>;
        briefManualErrors: Record<string, any>;
    };
    selectors: {
        step: (state: any, props?: any) => WizardStep;
        brief: (state: any, props?: any) => {
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis: string;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background: string;
            research_goal: string;
        };
        isBriefSubmitting: (state: any, props?: any) => boolean;
        showBriefErrors: (state: any, props?: any) => boolean;
        briefChanged: (state: any, props?: any) => boolean;
        briefTouches: (state: any, props?: any) => Record<string, boolean>;
        briefManualErrors: (state: any, props?: any) => Record<string, any>;
        study: (state: any, props?: any) => Study | null;
        briefTouched: (state: any, props?: any) => boolean;
        briefValidationErrors: (state: any, props?: any) => DeepPartialMap<{
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis: string;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background: string;
            research_goal: string;
        }, ValidationErrorType>;
        briefAllErrors: (state: any, props?: any) => Record<string, any>;
        briefHasErrors: (state: any, props?: any) => boolean;
        briefErrors: (state: any, props?: any) => DeepPartialMap<{
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis: string;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background: string;
            research_goal: string;
        }, ValidationErrorType>;
        isBriefValid: (state: any, props?: any) => boolean;
        currentStepIndex: (state: any, props?: any) => number;
        canGoBack: (state: any, props?: any) => boolean;
        isLastStep: (state: any, props?: any) => boolean;
        schema: (state: any, props?: any) => ZodObject<{
            barge_in_enabled: ZodBoolean;
            estimated_minutes: ZodNumber;
            hypothesis: ZodDefault<ZodString>;
            interview_mode: ZodEnum<[
                "voice",
                "video",
                "text",
                "offline"
            ]>;
            research_background: ZodDefault<ZodString>;
            research_goal: ZodString;
        }, "strip", ZodTypeAny, {
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis: string;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background: string;
            research_goal: string;
        }, {
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis?: string | undefined;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background?: string | undefined;
            research_goal: string;
        }>;
    };
    sharedListeners: {};
    values: {
        step: WizardStep;
        brief: {
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis: string;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background: string;
            research_goal: string;
        };
        isBriefSubmitting: boolean;
        showBriefErrors: boolean;
        briefChanged: boolean;
        briefTouches: Record<string, boolean>;
        briefManualErrors: Record<string, any>;
        study: Study | null;
        briefTouched: boolean;
        briefValidationErrors: DeepPartialMap<{
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis: string;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background: string;
            research_goal: string;
        }, ValidationErrorType>;
        briefAllErrors: Record<string, any>;
        briefHasErrors: boolean;
        briefErrors: DeepPartialMap<{
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis: string;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background: string;
            research_goal: string;
        }, ValidationErrorType>;
        isBriefValid: boolean;
        currentStepIndex: number;
        canGoBack: boolean;
        isLastStep: boolean;
        schema: ZodObject<{
            barge_in_enabled: ZodBoolean;
            estimated_minutes: ZodNumber;
            hypothesis: ZodDefault<ZodString>;
            interview_mode: ZodEnum<[
                "voice",
                "video",
                "text",
                "offline"
            ]>;
            research_background: ZodDefault<ZodString>;
            research_goal: ZodString;
        }, "strip", ZodTypeAny, {
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis: string;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background: string;
            research_goal: string;
        }, {
            barge_in_enabled: boolean;
            estimated_minutes: number;
            hypothesis?: string | undefined;
            interview_mode: "offline" | "text" | "video" | "voice";
            research_background?: string | undefined;
            research_goal: string;
        }>;
    };
    _isKea: true;
    _isKeaWithKey: false;
    __keaTypeGenInternalSelectorTypes: {
        currentStepIndex: (step: WizardStep) => number;
        canGoBack: (step: WizardStep) => boolean;
        isLastStep: (step: WizardStep) => boolean;
    };
}