// Generated by kea-typegen on Sun, 10 May 2026 06:29:05 GMT.
// Manually rewritten 2026-05-24 to match the merged "Research goal" UI:
// one list section feeds both research_goal (joined string) and
// research_objectives (raw list). See studySettingsLogic.ts.

import type { Logic } from "kea";

import type { Study } from "../../../../types";
import type { SettingsSection } from "./studySettingsLogic";

export interface studySettingsLogicType extends Logic {
  actionCreators: {
    loadStudy: () => {
      type: "load study (features.studies.tabs.settings.studySettingsLogic)";
      payload: any;
    };
    startEdit: (section: Exclude<SettingsSection, null>) => {
      type: "start edit (features.studies.tabs.settings.studySettingsLogic)";
      payload: {
        section: "details" | "goals";
      };
    };
    cancelEdit: () => {
      type: "cancel edit (features.studies.tabs.settings.studySettingsLogic)";
      payload: {
        value: true;
      };
    };
    setDraftName: (name: string) => {
      type: "set draft name (features.studies.tabs.settings.studySettingsLogic)";
      payload: {
        name: string;
      };
    };
    setDraftGoals: (goals: string[]) => {
      type: "set draft goals (features.studies.tabs.settings.studySettingsLogic)";
      payload: {
        goals: string[];
      };
    };
    hydrateFromStudy: (study: Study) => {
      type: "hydrate from study (features.studies.tabs.settings.studySettingsLogic)";
      payload: {
        study: Study;
      };
    };
    saveAll: () => {
      type: "save all (features.studies.tabs.settings.studySettingsLogic)";
      payload: any;
    };
    saveAllSuccess: (
      saveSuccess: boolean,
      payload?: any,
    ) => {
      type: "save all success (features.studies.tabs.settings.studySettingsLogic)";
      payload: {
        saveSuccess: boolean;
        payload?: any;
      };
    };
    saveAllFailure: (
      error: string,
      errorObject?: any,
    ) => {
      type: "save all failure (features.studies.tabs.settings.studySettingsLogic)";
      payload: {
        error: string;
        errorObject?: any;
      };
    };
  };
  actionKeys: {
    "load study (features.studies.tabs.settings.studySettingsLogic)": "loadStudy";
    "start edit (features.studies.tabs.settings.studySettingsLogic)": "startEdit";
    "cancel edit (features.studies.tabs.settings.studySettingsLogic)": "cancelEdit";
    "set draft name (features.studies.tabs.settings.studySettingsLogic)": "setDraftName";
    "set draft goals (features.studies.tabs.settings.studySettingsLogic)": "setDraftGoals";
    "hydrate from study (features.studies.tabs.settings.studySettingsLogic)": "hydrateFromStudy";
    "save all (features.studies.tabs.settings.studySettingsLogic)": "saveAll";
    "save all success (features.studies.tabs.settings.studySettingsLogic)": "saveAllSuccess";
    "save all failure (features.studies.tabs.settings.studySettingsLogic)": "saveAllFailure";
  };
  actionTypes: {
    loadStudy: "load study (features.studies.tabs.settings.studySettingsLogic)";
    startEdit: "start edit (features.studies.tabs.settings.studySettingsLogic)";
    cancelEdit: "cancel edit (features.studies.tabs.settings.studySettingsLogic)";
    setDraftName: "set draft name (features.studies.tabs.settings.studySettingsLogic)";
    setDraftGoals: "set draft goals (features.studies.tabs.settings.studySettingsLogic)";
    hydrateFromStudy: "hydrate from study (features.studies.tabs.settings.studySettingsLogic)";
    saveAll: "save all (features.studies.tabs.settings.studySettingsLogic)";
    saveAllSuccess: "save all success (features.studies.tabs.settings.studySettingsLogic)";
    saveAllFailure: "save all failure (features.studies.tabs.settings.studySettingsLogic)";
  };
  actions: {
    loadStudy: () => void;
    startEdit: (section: Exclude<SettingsSection, null>) => void;
    cancelEdit: () => void;
    setDraftName: (name: string) => void;
    setDraftGoals: (goals: string[]) => void;
    hydrateFromStudy: (study: Study) => void;
    saveAll: () => void;
    saveAllSuccess: (saveSuccess: boolean, payload?: any) => void;
    saveAllFailure: (error: string, errorObject?: any) => void;
  };
  asyncActions: {
    loadStudy: () => Promise<any>;
    startEdit: (section: Exclude<SettingsSection, null>) => Promise<any>;
    cancelEdit: () => Promise<any>;
    setDraftName: (name: string) => Promise<any>;
    setDraftGoals: (goals: string[]) => Promise<any>;
    hydrateFromStudy: (study: Study) => Promise<any>;
    saveAll: () => Promise<any>;
    saveAllSuccess: (saveSuccess: boolean, payload?: any) => Promise<any>;
    saveAllFailure: (error: string, errorObject?: any) => Promise<any>;
  };
  defaults: {
    editingSection: SettingsSection;
    draftName: string;
    draftGoals: string[];
    saveSuccess: boolean;
    saveSuccessLoading: boolean;
  };
  events: {};
  key: undefined;
  listeners: {};
  path: ["features", "studies", "tabs", "settings", "studySettingsLogic"];
  pathString: "features.studies.tabs.settings.studySettingsLogic";
  props: Record<string, unknown>;
  reducer: (
    state: any,
    action: any,
    fullState: any,
  ) => {
    editingSection: SettingsSection;
    draftName: string;
    draftGoals: string[];
    saveSuccess: boolean;
    saveSuccessLoading: boolean;
  };
  reducers: {
    editingSection: (
      state: SettingsSection,
      action: any,
      fullState: any,
    ) => SettingsSection;
    draftName: (state: string, action: any, fullState: any) => string;
    draftGoals: (state: string[], action: any, fullState: any) => string[];
    saveSuccess: (state: boolean, action: any, fullState: any) => boolean;
    saveSuccessLoading: (
      state: boolean,
      action: any,
      fullState: any,
    ) => boolean;
  };
  selector: (state: any) => {
    editingSection: SettingsSection;
    draftName: string;
    draftGoals: string[];
    saveSuccess: boolean;
    saveSuccessLoading: boolean;
  };
  selectors: {
    editingSection: (state: any, props?: any) => SettingsSection;
    draftName: (state: any, props?: any) => string;
    draftGoals: (state: any, props?: any) => string[];
    saveSuccess: (state: any, props?: any) => boolean;
    saveSuccessLoading: (state: any, props?: any) => boolean;
    study: (state: any, props?: any) => Study | null;
    studyId: (state: any, props?: any) => string | null;
    isEditing: (state: any, props?: any) => boolean;
    isSavingSettings: (state: any, props?: any) => boolean;
  };
  sharedListeners: {};
  values: {
    editingSection: SettingsSection;
    draftName: string;
    draftGoals: string[];
    saveSuccess: boolean;
    saveSuccessLoading: boolean;
    study: Study | null;
    studyId: string | null;
    isEditing: boolean;
    isSavingSettings: boolean;
  };
  _isKea: true;
  _isKeaWithKey: false;
  __keaTypeGenInternalSelectorTypes: {
    isEditing: (editingSection: SettingsSection) => boolean;
    isSavingSettings: (saveSuccessLoading: boolean) => boolean;
  };
}
