// Generated by hand to mirror kea-typegen output until the generator can
// process the analysis logic tree in this workspace.

import type { Logic } from "kea";

export interface insightsLogicType extends Logic {
  actionCreators: {
    setStudyId: (studyId: string) => {
      type: "set study id (features.analysis.insightsLogic)";
      payload: {
        studyId: string;
      };
    };
    toggleFinding: (findingId: string) => {
      type: "toggle finding (features.analysis.insightsLogic)";
      payload: {
        findingId: string;
      };
    };
    rerunInsights: () => {
      type: "rerun insights (features.analysis.insightsLogic)";
      payload: {
        value: true;
      };
    };
    startPolling: () => {
      type: "start polling (features.analysis.insightsLogic)";
      payload: {
        value: true;
      };
    };
    stopPolling: () => {
      type: "stop polling (features.analysis.insightsLogic)";
      payload: {
        value: true;
      };
    };
    loadInsights: () => {
      type: "load insights (features.analysis.insightsLogic)";
      payload: any;
    };
    loadInsightsSuccess: (
      insights: any,
      payload?: any,
    ) => {
      type: "load insights success (features.analysis.insightsLogic)";
      payload: {
        insights: any;
        payload?: any;
      };
    };
    loadInsightsFailure: (
      error: string,
      errorObject?: any,
    ) => {
      type: "load insights failure (features.analysis.insightsLogic)";
      payload: {
        error: string;
        errorObject?: any;
      };
    };
    loadHighlights: () => {
      type: "load highlights (features.analysis.insightsLogic)";
      payload: any;
    };
    loadHighlightsSuccess: (
      highlights: any[],
      payload?: any,
    ) => {
      type: "load highlights success (features.analysis.insightsLogic)";
      payload: {
        highlights: any[];
        payload?: any;
      };
    };
    loadHighlightsFailure: (
      error: string,
      errorObject?: any,
    ) => {
      type: "load highlights failure (features.analysis.insightsLogic)";
      payload: {
        error: string;
        errorObject?: any;
      };
    };
    loadFindings: () => {
      type: "load findings (features.analysis.insightsLogic)";
      payload: any;
    };
    loadFindingsSuccess: (
      findings: any[],
      payload?: any,
    ) => {
      type: "load findings success (features.analysis.insightsLogic)";
      payload: {
        findings: any[];
        payload?: any;
      };
    };
    loadFindingsFailure: (
      error: string,
      errorObject?: any,
    ) => {
      type: "load findings failure (features.analysis.insightsLogic)";
      payload: {
        error: string;
        errorObject?: any;
      };
    };
  };
  actionKeys: Record<string, string>;
  actionTypes: Record<string, string>;
  actions: {
    setStudyId: (studyId: string) => void;
    toggleFinding: (findingId: string) => void;
    rerunInsights: () => void;
    startPolling: () => void;
    stopPolling: () => void;
    loadInsights: () => void;
    loadInsightsSuccess: (insights: any, payload?: any) => void;
    loadInsightsFailure: (error: string, errorObject?: any) => void;
    loadHighlights: () => void;
    loadHighlightsSuccess: (highlights: any[], payload?: any) => void;
    loadHighlightsFailure: (error: string, errorObject?: any) => void;
    loadFindings: () => void;
    loadFindingsSuccess: (findings: any[], payload?: any) => void;
    loadFindingsFailure: (error: string, errorObject?: any) => void;
  };
  asyncActions: {
    setStudyId: (studyId: string) => Promise<any>;
    toggleFinding: (findingId: string) => Promise<any>;
    rerunInsights: () => Promise<any>;
    startPolling: () => Promise<any>;
    stopPolling: () => Promise<any>;
    loadInsights: () => Promise<any>;
    loadInsightsSuccess: (insights: any, payload?: any) => Promise<any>;
    loadInsightsFailure: (error: string, errorObject?: any) => Promise<any>;
    loadHighlights: () => Promise<any>;
    loadHighlightsSuccess: (highlights: any[], payload?: any) => Promise<any>;
    loadHighlightsFailure: (error: string, errorObject?: any) => Promise<any>;
    loadFindings: () => Promise<any>;
    loadFindingsSuccess: (findings: any[], payload?: any) => Promise<any>;
    loadFindingsFailure: (error: string, errorObject?: any) => Promise<any>;
  };
  defaults: {
    studyId: string;
    expandedFindings: Record<string, boolean>;
    _pollTimer: ReturnType<typeof setInterval> | null;
    insights: any;
    insightsLoading: boolean;
    highlights: any[];
    highlightsLoading: boolean;
    findings: any[];
    findingsLoading: boolean;
    isLoading: boolean;
    isGenerating: boolean;
    isFailed: boolean;
    errorMessage: string;
    isEmpty: boolean;
  };
  events: Record<string, never>;
  key: undefined;
  listeners: Record<string, any>;
  path: ["features", "analysis", "insightsLogic"];
  pathString: "features.analysis.insightsLogic";
  props: Record<string, unknown>;
  reducer: (state: any, action: any, fullState: any) => any;
  reducers: Record<string, any>;
  selector: (state: any) => any;
  selectors: Record<string, any>;
  sharedListeners: Record<string, never>;
  values: {
    studyId: string;
    expandedFindings: Record<string, boolean>;
    _pollTimer: ReturnType<typeof setInterval> | null;
    insights: any;
    insightsLoading: boolean;
    highlights: any[];
    highlightsLoading: boolean;
    findings: any[];
    findingsLoading: boolean;
    isLoading: boolean;
    isGenerating: boolean;
    isFailed: boolean;
    errorMessage: string;
    isEmpty: boolean;
  };
  _isKea: true;
  _isKeaWithKey: false;
  __keaTypeGenInternalSelectorTypes: Record<string, any>;
}
