// Generated by hand to mirror kea-typegen output until the generator can
// process the analysis logic tree in this workspace.

import type { Logic } from "kea";

import type { CustomReportData } from "./reportsLogic";

export interface reportsLogicType extends Logic {
  actionCreators: {
    setStudyId: (studyId: string) => {
      type: "set study id (features.analysis.reportsLogic)";
      payload: {
        studyId: string;
      };
    };
    createReport: (title: string) => {
      type: "create report (features.analysis.reportsLogic)";
      payload: {
        title: string;
      };
    };
    deleteReport: (reportId: string) => {
      type: "delete report (features.analysis.reportsLogic)";
      payload: {
        reportId: string;
      };
    };
    loadReports: () => {
      type: "load reports (features.analysis.reportsLogic)";
      payload: any;
    };
    loadReportsSuccess: (
      reports: CustomReportData[],
      payload?: any,
    ) => {
      type: "load reports success (features.analysis.reportsLogic)";
      payload: {
        reports: CustomReportData[];
        payload?: any;
      };
    };
    loadReportsFailure: (
      error: string,
      errorObject?: any,
    ) => {
      type: "load reports failure (features.analysis.reportsLogic)";
      payload: {
        error: string;
        errorObject?: any;
      };
    };
  };
  actionKeys: Record<string, string>;
  actionTypes: Record<string, string>;
  actions: {
    setStudyId: (studyId: string) => void;
    createReport: (title: string) => void;
    deleteReport: (reportId: string) => void;
    loadReports: () => void;
    loadReportsSuccess: (reports: CustomReportData[], payload?: any) => void;
    loadReportsFailure: (error: string, errorObject?: any) => void;
  };
  asyncActions: {
    setStudyId: (studyId: string) => Promise<any>;
    createReport: (title: string) => Promise<any>;
    deleteReport: (reportId: string) => Promise<any>;
    loadReports: () => Promise<any>;
    loadReportsSuccess: (
      reports: CustomReportData[],
      payload?: any,
    ) => Promise<any>;
    loadReportsFailure: (error: string, errorObject?: any) => Promise<any>;
  };
  defaults: {
    studyId: string;
    reports: CustomReportData[];
    reportsLoading: boolean;
    isLoading: boolean;
  };
  events: Record<string, never>;
  key: undefined;
  listeners: Record<string, any>;
  path: ["features", "analysis", "reportsLogic"];
  pathString: "features.analysis.reportsLogic";
  props: Record<string, unknown>;
  reducer: (state: any, action: any, fullState: any) => any;
  reducers: Record<string, any>;
  selector: (state: any) => any;
  selectors: Record<string, any>;
  sharedListeners: Record<string, never>;
  values: {
    studyId: string;
    reports: CustomReportData[];
    reportsLoading: boolean;
    isLoading: boolean;
  };
  _isKea: true;
  _isKeaWithKey: false;
  __keaTypeGenInternalSelectorTypes: Record<string, any>;
}
