// Generated by hand to mirror kea-typegen output until the generator can
// process the analysis logic tree in this workspace.

import type { Logic } from "kea";

import type {
  ReportQuestion,
  ReportSegment,
  CustomReportData,
} from "./reportsLogic";

export interface reportDetailLogicType extends Logic {
  actionCreators: {
    setReportId: (reportId: string) => {
      type: "set report id (features.analysis.reportDetailLogic)";
      payload: {
        reportId: string;
      };
    };
    generateReport: () => {
      type: "generate report (features.analysis.reportDetailLogic)";
      payload: {
        value: true;
      };
    };
    togglePublic: () => {
      type: "toggle public (features.analysis.reportDetailLogic)";
      payload: {
        value: true;
      };
    };
    setActiveSegment: (segmentId: string | null) => {
      type: "set active segment (features.analysis.reportDetailLogic)";
      payload: {
        segmentId: string | null;
      };
    };
    addQuestion: (
      title: string,
      questionType: string,
    ) => {
      type: "add question (features.analysis.reportDetailLogic)";
      payload: {
        title: string;
        questionType: string;
      };
    };
    startPolling: () => {
      type: "start polling (features.analysis.reportDetailLogic)";
      payload: {
        value: true;
      };
    };
    stopPolling: () => {
      type: "stop polling (features.analysis.reportDetailLogic)";
      payload: {
        value: true;
      };
    };
    loadReport: () => {
      type: "load report (features.analysis.reportDetailLogic)";
      payload: any;
    };
    loadReportSuccess: (
      report: CustomReportData | null,
      payload?: any,
    ) => {
      type: "load report success (features.analysis.reportDetailLogic)";
      payload: {
        report: CustomReportData | null;
        payload?: any;
      };
    };
    loadReportFailure: (
      error: string,
      errorObject?: any,
    ) => {
      type: "load report failure (features.analysis.reportDetailLogic)";
      payload: {
        error: string;
        errorObject?: any;
      };
    };
    loadQuestions: () => {
      type: "load questions (features.analysis.reportDetailLogic)";
      payload: any;
    };
    loadQuestionsSuccess: (
      questions: ReportQuestion[],
      payload?: any,
    ) => {
      type: "load questions success (features.analysis.reportDetailLogic)";
      payload: {
        questions: ReportQuestion[];
        payload?: any;
      };
    };
    loadQuestionsFailure: (
      error: string,
      errorObject?: any,
    ) => {
      type: "load questions failure (features.analysis.reportDetailLogic)";
      payload: {
        error: string;
        errorObject?: any;
      };
    };
    loadSegments: () => {
      type: "load segments (features.analysis.reportDetailLogic)";
      payload: any;
    };
    loadSegmentsSuccess: (
      segments: ReportSegment[],
      payload?: any,
    ) => {
      type: "load segments success (features.analysis.reportDetailLogic)";
      payload: {
        segments: ReportSegment[];
        payload?: any;
      };
    };
    loadSegmentsFailure: (
      error: string,
      errorObject?: any,
    ) => {
      type: "load segments failure (features.analysis.reportDetailLogic)";
      payload: {
        error: string;
        errorObject?: any;
      };
    };
  };
  actionKeys: Record<string, string>;
  actionTypes: Record<string, string>;
  actions: {
    setReportId: (reportId: string) => void;
    generateReport: () => void;
    togglePublic: () => void;
    setActiveSegment: (segmentId: string | null) => void;
    addQuestion: (title: string, questionType: string) => void;
    startPolling: () => void;
    stopPolling: () => void;
    loadReport: () => void;
    loadReportSuccess: (report: CustomReportData | null, payload?: any) => void;
    loadReportFailure: (error: string, errorObject?: any) => void;
    loadQuestions: () => void;
    loadQuestionsSuccess: (questions: ReportQuestion[], payload?: any) => void;
    loadQuestionsFailure: (error: string, errorObject?: any) => void;
    loadSegments: () => void;
    loadSegmentsSuccess: (segments: ReportSegment[], payload?: any) => void;
    loadSegmentsFailure: (error: string, errorObject?: any) => void;
  };
  asyncActions: {
    setReportId: (reportId: string) => Promise<any>;
    generateReport: () => Promise<any>;
    togglePublic: () => Promise<any>;
    setActiveSegment: (segmentId: string | null) => Promise<any>;
    addQuestion: (title: string, questionType: string) => Promise<any>;
    startPolling: () => Promise<any>;
    stopPolling: () => Promise<any>;
    loadReport: () => Promise<any>;
    loadReportSuccess: (
      report: CustomReportData | null,
      payload?: any,
    ) => Promise<any>;
    loadReportFailure: (error: string, errorObject?: any) => Promise<any>;
    loadQuestions: () => Promise<any>;
    loadQuestionsSuccess: (
      questions: ReportQuestion[],
      payload?: any,
    ) => Promise<any>;
    loadQuestionsFailure: (error: string, errorObject?: any) => Promise<any>;
    loadSegments: () => Promise<any>;
    loadSegmentsSuccess: (
      segments: ReportSegment[],
      payload?: any,
    ) => Promise<any>;
    loadSegmentsFailure: (error: string, errorObject?: any) => Promise<any>;
  };
  defaults: {
    reportId: string;
    activeSegment: string | null;
    report: CustomReportData | null;
    reportLoading: boolean;
    questions: ReportQuestion[];
    questionsLoading: boolean;
    segments: ReportSegment[];
    segmentsLoading: boolean;
    isLoading: boolean;
    isGenerating: boolean;
    filteredQuestions: ReportQuestion[];
  };
  events: Record<string, never>;
  key: undefined;
  listeners: Record<string, any>;
  path: ["features", "analysis", "reportDetailLogic"];
  pathString: "features.analysis.reportDetailLogic";
  props: Record<string, unknown>;
  reducer: (state: any, action: any, fullState: any) => any;
  reducers: Record<string, any>;
  selector: (state: any) => any;
  selectors: Record<string, any>;
  sharedListeners: Record<string, never>;
  values: {
    reportId: string;
    activeSegment: string | null;
    report: CustomReportData | null;
    reportLoading: boolean;
    questions: ReportQuestion[];
    questionsLoading: boolean;
    segments: ReportSegment[];
    segmentsLoading: boolean;
    isLoading: boolean;
    isGenerating: boolean;
    filteredQuestions: ReportQuestion[];
  };
  _isKea: true;
  _isKeaWithKey: false;
  __keaTypeGenInternalSelectorTypes: Record<string, any>;
}
