"""Deterministic LLM fake.

Implements enough of the OpenAI ``chat.completions`` protocol (both sync and
async, both streaming and non-streaming) to be a drop-in replacement for
``openai.OpenAI`` / ``openai.AsyncOpenAI`` / LangChain's ``ChatOpenAI`` in tests.

Responses are either:
- Looked up by a prefix of the last user message (``prefix_to_response``), or
- Returned from a pre-canned FIFO queue (``responses``), or
- Generated by a callable (``responder``).

All invocations are recorded on ``llm.calls`` so tests can assert what the
agent actually prompted.
"""

from __future__ import annotations

from collections.abc import AsyncIterator, Callable, Iterator, Sequence
from dataclasses import dataclass, field
from typing import Any


@dataclass
class LLMCall:
    """A single recorded LLM invocation."""

    messages: list[dict[str, Any]]
    model: str | None = None
    stream: bool = False
    extra: dict[str, Any] = field(default_factory=dict)

    @property
    def prompt(self) -> str:
        """Concatenated ``content`` of all messages, useful for quick asserts."""
        return "\n".join(str(m.get("content", "")) for m in self.messages)

    @property
    def system_prompt(self) -> str:
        for m in self.messages:
            if m.get("role") == "system":
                return str(m.get("content", ""))
        return ""

    @property
    def last_user_message(self) -> str:
        for m in reversed(self.messages):
            if m.get("role") == "user":
                return str(m.get("content", ""))
        return ""


class DeterministicLLM:
    """OpenAI-protocol LLM fake.

    Example::

        llm = DeterministicLLM(
            prefix_to_response={
                "Classify intent": "greeting",
                "Summarize": "User said they liked the pricing page.",
            },
            default="I don't know.",
        )

        response = llm.chat_completions_create(
            messages=[{"role": "user", "content": "Classify intent: hi"}],
            model="gpt-4.1-mini",
        )
        assert response["choices"][0]["message"]["content"] == "greeting"
        assert len(llm.calls) == 1
    """

    def __init__(
        self,
        *,
        prefix_to_response: dict[str, str] | None = None,
        responses: Sequence[str] | None = None,
        responder: Callable[[LLMCall], str] | None = None,
        default: str = "",
        model: str = "deterministic-test-model",
    ) -> None:
        self._prefix_to_response = dict(prefix_to_response or {})
        self._responses: list[str] = list(responses or [])
        self._responder = responder
        self._default = default
        self._model = model
        self.calls: list[LLMCall] = []

    # ─── Public helpers ─────────────────────────────────────────

    def reset(self) -> None:
        self.calls.clear()

    def set_response_for(self, prefix: str, response: str) -> None:
        self._prefix_to_response[prefix] = response

    def push_response(self, response: str) -> None:
        """Queue a single response to be returned on the next call."""
        self._responses.append(response)

    @property
    def last_call(self) -> LLMCall:
        if not self.calls:
            raise AssertionError("DeterministicLLM has not been invoked yet")
        return self.calls[-1]

    # ─── Protocol surface: OpenAI chat.completions ──────────────

    def chat_completions_create(
        self,
        *,
        messages: list[dict[str, Any]],
        model: str | None = None,
        stream: bool = False,
        **kwargs: Any,
    ) -> dict[str, Any] | Iterator[dict[str, Any]]:
        call = LLMCall(messages=messages, model=model, stream=stream, extra=dict(kwargs))
        self.calls.append(call)
        content = self._resolve_response(call)

        if stream:
            return self._emit_sync_stream(content, model or self._model)
        return self._build_completion(content, model or self._model)

    async def chat_completions_acreate(
        self,
        *,
        messages: list[dict[str, Any]],
        model: str | None = None,
        stream: bool = False,
        **kwargs: Any,
    ) -> dict[str, Any] | AsyncIterator[dict[str, Any]]:
        call = LLMCall(messages=messages, model=model, stream=stream, extra=dict(kwargs))
        self.calls.append(call)
        content = self._resolve_response(call)

        if stream:
            return self._emit_async_stream(content, model or self._model)
        return self._build_completion(content, model or self._model)

    # ─── LangChain ChatModel protocol ───────────────────────────

    def invoke(self, messages: list[dict[str, Any]], **kwargs: Any) -> dict[str, Any]:
        """LangChain-style ``invoke``. Returns a dict shaped like an AIMessage."""
        call = LLMCall(messages=messages, model=self._model, stream=False, extra=dict(kwargs))
        self.calls.append(call)
        return {"role": "assistant", "content": self._resolve_response(call)}

    async def ainvoke(self, messages: list[dict[str, Any]], **kwargs: Any) -> dict[str, Any]:
        return self.invoke(messages, **kwargs)

    # ─── Internals ──────────────────────────────────────────────

    def _resolve_response(self, call: LLMCall) -> str:
        if self._responder is not None:
            return self._responder(call)
        if self._responses:
            return self._responses.pop(0)
        last_user = call.last_user_message
        for prefix, response in self._prefix_to_response.items():
            if prefix in last_user:
                return response
        return self._default

    @staticmethod
    def _build_completion(content: str, model: str) -> dict[str, Any]:
        return {
            "id": f"chatcmpl-deterministic-{len(content)}",
            "object": "chat.completion",
            "model": model,
            "choices": [
                {
                    "index": 0,
                    "finish_reason": "stop",
                    "message": {"role": "assistant", "content": content},
                }
            ],
            "usage": {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0},
        }

    @staticmethod
    def _emit_sync_stream(content: str, model: str) -> Iterator[dict[str, Any]]:
        # One delta per token-ish chunk. Keep small so tests can count chunks.
        for chunk in _tokenize_for_streaming(content):
            yield {
                "object": "chat.completion.chunk",
                "model": model,
                "choices": [{"index": 0, "delta": {"content": chunk}, "finish_reason": None}],
            }
        yield {
            "object": "chat.completion.chunk",
            "model": model,
            "choices": [{"index": 0, "delta": {}, "finish_reason": "stop"}],
        }

    @staticmethod
    async def _emit_async_stream(content: str, model: str) -> AsyncIterator[dict[str, Any]]:
        for chunk in _tokenize_for_streaming(content):
            yield {
                "object": "chat.completion.chunk",
                "model": model,
                "choices": [{"index": 0, "delta": {"content": chunk}, "finish_reason": None}],
            }
        yield {
            "object": "chat.completion.chunk",
            "model": model,
            "choices": [{"index": 0, "delta": {}, "finish_reason": "stop"}],
        }


def _tokenize_for_streaming(content: str, max_chunks: int = 8) -> list[str]:
    """Split content into up to ``max_chunks`` streaming pieces, roughly evenly."""
    if not content:
        return []
    chunk_size = max(1, len(content) // max_chunks)
    chunks = [content[i : i + chunk_size] for i in range(0, len(content), chunk_size)]
    return chunks
