// Generated by kea-typegen on Sun, 10 May 2026 07:02:18 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { Study } from '../types'
import type { Scene } from '../app/routes'
import type { SceneParams } from '../app/sceneTypes'

export interface sidebarLogicType extends Logic {
    actionCreators: {
        touchStudy: (studyId: string) => ({
            type: "touch study (layout.sidebarLogic)";
            payload: {
                studyId: string;
            };
        });
    };
    actionKeys: {
        "touch study (layout.sidebarLogic)": "touchStudy";
    };
    actionTypes: {
        touchStudy: "touch study (layout.sidebarLogic)";
    };
    actions: {
        touchStudy: (studyId: string) => void;
    };
    asyncActions: {
        touchStudy: (studyId: string) => Promise<any>;
    };
    defaults: {
        recentStudyIds: string[];
    };
    events: {};
    key: undefined;
    listeners: {};
    path: [
        "layout",
        "sidebarLogic"
    ];
    pathString: "layout.sidebarLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {
        recentStudyIds: string[];
    };
    reducers: {
        recentStudyIds: (state: string[], action: any, fullState: any) => string[];
    };
    selector: (state: any) => {
        recentStudyIds: string[];
    };
    selectors: {
        recentStudyIds: (state: any, props?: any) => string[];
        studies: (state: any, props?: any) => Study[];
        activeScene: (state: any, props?: any) => Scene;
        sceneParams: (state: any, props?: any) => SceneParams;
        pinnedStudies: (state: any, props?: any) => Study[];
    };
    sharedListeners: {};
    values: {
        recentStudyIds: string[];
        studies: Study[];
        activeScene: Scene;
        sceneParams: SceneParams;
        pinnedStudies: Study[];
    };
    _isKea: true;
    _isKeaWithKey: false;
    __keaTypeGenInternalSelectorTypes: {
        pinnedStudies: (recentStudyIds: string[], studies: import("~//types").Study[]) => Study[];
    };
    __keaTypeGenInternalReducerActions: {
        "set scene (app.sceneLogic)": (scene: Scene, params: SceneParams) => ({
            payload: {
                params: SceneParams;
                scene: Scene;
            };
            type: "set scene (app.sceneLogic)";
        });
    };
}