// Generated by kea-typegen on Sun, 10 May 2026 18:01:56 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { InboxItem } from './inboxLogic'

export interface inboxLogicType extends Logic {
    actionCreators: {
        loadInbox: () => ({
            type: "load inbox (features.inbox.inboxLogic)";
            payload: any;
        });
        loadInboxSuccess: (items: InboxItem[], payload?: any) => ({
            type: "load inbox success (features.inbox.inboxLogic)";
            payload: {
                items: InboxItem[];
                payload?: any;
            };
        });
        loadInboxFailure: (error: string, errorObject?: any) => ({
            type: "load inbox failure (features.inbox.inboxLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
        markRead: (id: string) => ({
            type: "mark read (features.inbox.inboxLogic)";
            payload: string;
        });
        markReadSuccess: (items: InboxItem[], payload?: string) => ({
            type: "mark read success (features.inbox.inboxLogic)";
            payload: {
                items: InboxItem[];
                payload?: string;
            };
        });
        markReadFailure: (error: string, errorObject?: any) => ({
            type: "mark read failure (features.inbox.inboxLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
    };
    actionKeys: {
        "load inbox (features.inbox.inboxLogic)": "loadInbox";
        "load inbox success (features.inbox.inboxLogic)": "loadInboxSuccess";
        "load inbox failure (features.inbox.inboxLogic)": "loadInboxFailure";
        "mark read (features.inbox.inboxLogic)": "markRead";
        "mark read success (features.inbox.inboxLogic)": "markReadSuccess";
        "mark read failure (features.inbox.inboxLogic)": "markReadFailure";
    };
    actionTypes: {
        loadInbox: "load inbox (features.inbox.inboxLogic)";
        loadInboxSuccess: "load inbox success (features.inbox.inboxLogic)";
        loadInboxFailure: "load inbox failure (features.inbox.inboxLogic)";
        markRead: "mark read (features.inbox.inboxLogic)";
        markReadSuccess: "mark read success (features.inbox.inboxLogic)";
        markReadFailure: "mark read failure (features.inbox.inboxLogic)";
    };
    actions: {
        loadInbox: () => void;
        loadInboxSuccess: (items: InboxItem[], payload?: any) => void;
        loadInboxFailure: (error: string, errorObject?: any) => void;
        markRead: (id: string) => void;
        markReadSuccess: (items: InboxItem[], payload?: string) => void;
        markReadFailure: (error: string, errorObject?: any) => void;
    };
    asyncActions: {
        loadInbox: () => Promise<any>;
        loadInboxSuccess: (items: InboxItem[], payload?: any) => Promise<any>;
        loadInboxFailure: (error: string, errorObject?: any) => Promise<any>;
        markRead: (id: string) => Promise<any>;
        markReadSuccess: (items: InboxItem[], payload?: string) => Promise<any>;
        markReadFailure: (error: string, errorObject?: any) => Promise<any>;
    };
    defaults: {
        items: InboxItem[];
        itemsLoading: boolean;
    };
    events: {};
    key: undefined;
    listeners: {};
    path: [
        "features",
        "inbox",
        "inboxLogic"
    ];
    pathString: "features.inbox.inboxLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {
        items: InboxItem[];
        itemsLoading: boolean;
    };
    reducers: {
        items: (state: InboxItem[], action: any, fullState: any) => InboxItem[];
        itemsLoading: (state: boolean, action: any, fullState: any) => boolean;
    };
    selector: (state: any) => {
        items: InboxItem[];
        itemsLoading: boolean;
    };
    selectors: {
        items: (state: any, props?: any) => InboxItem[];
        itemsLoading: (state: any, props?: any) => boolean;
    };
    sharedListeners: {};
    values: {
        items: InboxItem[];
        itemsLoading: boolean;
    };
    _isKea: true;
    _isKeaWithKey: false;
}