// Generated by kea-typegen on Sat, 09 May 2026 19:18:12 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from "kea";

import type { LoginFormValues } from "./loginLogic";
import type {
  DeepPartial,
  DeepPartialMap,
  FieldName,
  ValidationErrorType,
} from "kea-forms";

export interface loginLogicType extends Logic {
  actionCreators: {
    push: (
      url: string,
      searchInput?: string | Record<string, any>,
      hashInput?: string | Record<string, any>,
    ) => {
      type: "push (features.authentication.loginLogic)";
      payload: {
        hashInput: string | Record<string, any>;
        searchInput: string | Record<string, any>;
        url: string;
      };
    };
    setLoginValue: (
      key: FieldName,
      value: any,
    ) => {
      type: "set login value (features.authentication.loginLogic)";
      payload: {
        name: FieldName;
        value: any;
      };
    };
    setLoginValues: (values: DeepPartial<LoginFormValues>) => {
      type: "set login values (features.authentication.loginLogic)";
      payload: {
        values: DeepPartial<LoginFormValues>;
      };
    };
    setLoginManualErrors: (errors: Record<string, any>) => {
      type: "set login manual errors (features.authentication.loginLogic)";
      payload: {
        errors: Record<string, any>;
      };
    };
    touchLoginField: (key: string) => {
      type: "touch login field (features.authentication.loginLogic)";
      payload: {
        key: string;
      };
    };
    resetLogin: (values?: LoginFormValues) => {
      type: "reset login (features.authentication.loginLogic)";
      payload: {
        values?: LoginFormValues;
      };
    };
    submitLogin: () => {
      type: "submit login (features.authentication.loginLogic)";
      payload: {
        value: boolean;
      };
    };
    submitLoginRequest: (login: LoginFormValues) => {
      type: "submit login request (features.authentication.loginLogic)";
      payload: {
        login: LoginFormValues;
      };
    };
    submitLoginSuccess: (login: LoginFormValues) => {
      type: "submit login success (features.authentication.loginLogic)";
      payload: {
        login: LoginFormValues;
      };
    };
    submitLoginFailure: (
      error: Error,
      errors: Record<string, any>,
    ) => {
      type: "submit login failure (features.authentication.loginLogic)";
      payload: {
        error: Error;
        errors: Record<string, any>;
      };
    };
  };
  actionKeys: {
    "push (features.authentication.loginLogic)": "push";
    "set login value (features.authentication.loginLogic)": "setLoginValue";
    "set login values (features.authentication.loginLogic)": "setLoginValues";
    "set login manual errors (features.authentication.loginLogic)": "setLoginManualErrors";
    "touch login field (features.authentication.loginLogic)": "touchLoginField";
    "reset login (features.authentication.loginLogic)": "resetLogin";
    "submit login (features.authentication.loginLogic)": "submitLogin";
    "submit login request (features.authentication.loginLogic)": "submitLoginRequest";
    "submit login success (features.authentication.loginLogic)": "submitLoginSuccess";
    "submit login failure (features.authentication.loginLogic)": "submitLoginFailure";
  };
  actionTypes: {
    push: "push (features.authentication.loginLogic)";
    setLoginValue: "set login value (features.authentication.loginLogic)";
    setLoginValues: "set login values (features.authentication.loginLogic)";
    setLoginManualErrors: "set login manual errors (features.authentication.loginLogic)";
    touchLoginField: "touch login field (features.authentication.loginLogic)";
    resetLogin: "reset login (features.authentication.loginLogic)";
    submitLogin: "submit login (features.authentication.loginLogic)";
    submitLoginRequest: "submit login request (features.authentication.loginLogic)";
    submitLoginSuccess: "submit login success (features.authentication.loginLogic)";
    submitLoginFailure: "submit login failure (features.authentication.loginLogic)";
  };
  actions: {
    push: (
      url: string,
      searchInput?: string | Record<string, any>,
      hashInput?: string | Record<string, any>,
    ) => void;
    setLoginValue: (key: FieldName, value: any) => void;
    setLoginValues: (values: DeepPartial<LoginFormValues>) => void;
    setLoginManualErrors: (errors: Record<string, any>) => void;
    touchLoginField: (key: string) => void;
    resetLogin: (values?: LoginFormValues) => void;
    submitLogin: () => void;
    submitLoginRequest: (login: LoginFormValues) => void;
    submitLoginSuccess: (login: LoginFormValues) => void;
    submitLoginFailure: (error: Error, errors: Record<string, any>) => void;
  };
  asyncActions: {
    push: (
      url: string,
      searchInput?: string | Record<string, any>,
      hashInput?: string | Record<string, any>,
    ) => Promise<any>;
    setLoginValue: (key: FieldName, value: any) => Promise<any>;
    setLoginValues: (values: DeepPartial<LoginFormValues>) => Promise<any>;
    setLoginManualErrors: (errors: Record<string, any>) => Promise<any>;
    touchLoginField: (key: string) => Promise<any>;
    resetLogin: (values?: LoginFormValues) => Promise<any>;
    submitLogin: () => Promise<any>;
    submitLoginRequest: (login: LoginFormValues) => Promise<any>;
    submitLoginSuccess: (login: LoginFormValues) => Promise<any>;
    submitLoginFailure: (
      error: Error,
      errors: Record<string, any>,
    ) => Promise<any>;
  };
  defaults: {
    login: LoginFormValues;
    isLoginSubmitting: boolean;
    showLoginErrors: boolean;
    loginChanged: boolean;
    loginTouches: Record<string, boolean>;
    loginManualErrors: Record<string, any>;
  };
  events: {};
  key: undefined;
  listeners: {
    submitLoginFailure: ((
      action: {
        type: "submit login failure (features.authentication.loginLogic)";
        payload: {
          error: Error;
          errors: Record<string, any>;
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
  };
  path: ["features", "authentication", "loginLogic"];
  pathString: "features.authentication.loginLogic";
  props: Record<string, unknown>;
  reducer: (
    state: any,
    action: any,
    fullState: any,
  ) => {
    login: LoginFormValues;
    isLoginSubmitting: boolean;
    showLoginErrors: boolean;
    loginChanged: boolean;
    loginTouches: Record<string, boolean>;
    loginManualErrors: Record<string, any>;
  };
  reducers: {
    login: (
      state: LoginFormValues,
      action: any,
      fullState: any,
    ) => LoginFormValues;
    isLoginSubmitting: (state: boolean, action: any, fullState: any) => boolean;
    showLoginErrors: (state: boolean, action: any, fullState: any) => boolean;
    loginChanged: (state: boolean, action: any, fullState: any) => boolean;
    loginTouches: (
      state: Record<string, boolean>,
      action: any,
      fullState: any,
    ) => Record<string, boolean>;
    loginManualErrors: (
      state: Record<string, any>,
      action: any,
      fullState: any,
    ) => Record<string, any>;
  };
  selector: (state: any) => {
    login: LoginFormValues;
    isLoginSubmitting: boolean;
    showLoginErrors: boolean;
    loginChanged: boolean;
    loginTouches: Record<string, boolean>;
    loginManualErrors: Record<string, any>;
  };
  selectors: {
    login: (state: any, props?: any) => LoginFormValues;
    isLoginSubmitting: (state: any, props?: any) => boolean;
    showLoginErrors: (state: any, props?: any) => boolean;
    loginChanged: (state: any, props?: any) => boolean;
    loginTouches: (state: any, props?: any) => Record<string, boolean>;
    loginManualErrors: (state: any, props?: any) => Record<string, any>;
    loginTouched: (state: any, props?: any) => boolean;
    loginValidationErrors: (
      state: any,
      props?: any,
    ) => DeepPartialMap<LoginFormValues, ValidationErrorType>;
    loginAllErrors: (state: any, props?: any) => Record<string, any>;
    loginHasErrors: (state: any, props?: any) => boolean;
    loginErrors: (
      state: any,
      props?: any,
    ) => DeepPartialMap<LoginFormValues, ValidationErrorType>;
    isLoginValid: (state: any, props?: any) => boolean;
  };
  sharedListeners: {};
  values: {
    login: LoginFormValues;
    isLoginSubmitting: boolean;
    showLoginErrors: boolean;
    loginChanged: boolean;
    loginTouches: Record<string, boolean>;
    loginManualErrors: Record<string, any>;
    loginTouched: boolean;
    loginValidationErrors: DeepPartialMap<LoginFormValues, ValidationErrorType>;
    loginAllErrors: Record<string, any>;
    loginHasErrors: boolean;
    loginErrors: DeepPartialMap<LoginFormValues, ValidationErrorType>;
    isLoginValid: boolean;
  };
  _isKea: true;
  _isKeaWithKey: false;
}
