"""Pydantic models + helpers for the v3 outline.

Persistence shape on `InterviewGuide.sections`:

    {
        "version": "v3",
        "sections": [
            {
                "id": "background",
                "title": "Background",
                "questions": [
                    {
                        "id": "role_context",                  # auto-gen
                        "ask": "...",                          # 题目原文
                        "follow_up_mode": "standard",          # off/standard/deep
                        "probe_instruction": "..."             # 可选, 追问指引
                    }
                ]
            }
        ]
    }

The top-level ``version: "v3"`` literal is the dual-engine routing key
per AGENTS.md Rule 13. ``Outline.model_validate(payload)`` is the
single entry point.

Per-question ``follow_up_mode`` lets researchers tune probing intensity
per question — background questions can be ``off`` while pain-point
deep-dives are ``deep``. The per-mode follow-up budget (turn count) is
hardcoded in ``Configuration``: ``off`` = 0, ``standard`` = 2,
``deep`` = 4. Researchers do NOT set follow-up counts per question —
mode picks the budget.
"""

from __future__ import annotations

from typing import Literal, TypedDict

from pydantic import BaseModel, ConfigDict, Field


class OutlineError(ValueError):
    """Raised by :func:`validate_outline` on duplicate ids or other
    structural invariants Pydantic field-level checks cannot express.
    """


#: Three follow-up modes — see ``state.FollowUpMode`` for the runtime
#: alias. Mirrored here on the schema so each question can override
#: independently.
QuestionFollowUpMode = Literal["off", "standard", "deep"]


class Question(BaseModel):
    """A single interview question.

    Researchers write 3 fields plus an optional ``probe_instruction``;
    ``id`` is auto-generated by the frontend. Engine reads ``ask``
    verbatim. ``follow_up_mode`` decides which judge node runs after
    this question; the per-mode budget (number of probe turns) lives in
    ``Configuration`` (``standard_followups`` / ``deep_followups``), not
    on the question.
    """

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    id: str = Field(min_length=1, pattern=r"^[a-zA-Z0-9_]+$")
    ask: str = Field(min_length=1)
    follow_up_mode: QuestionFollowUpMode = "standard"
    probe_instruction: str | None = None


class Section(BaseModel):
    """An ordered group of questions."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    id: str = Field(min_length=1, pattern=r"^[a-zA-Z0-9_]+$")
    title: str = Field(min_length=1)
    questions: list[Question] = Field(default_factory=list)


class Outline(BaseModel):
    """Top-level outline persisted on ``InterviewGuide.sections``."""

    model_config = ConfigDict(extra="forbid")

    version: Literal["v3"] = "v3"
    sections: list[Section] = Field(default_factory=list)


class Turn(TypedDict):
    """A single conversation turn appended to ``OverallState.transcript``.

    Plain TypedDict (not Pydantic) because LangGraph state values must be
    JSON-serializable plain dicts for the ``operator.add`` reducer.
    """

    section_id: str
    question_id: str
    kind: Literal["main", "followup"]
    question: str
    answer: str


def validate_outline(outline: Outline) -> None:
    """Raise :class:`OutlineError` if the outline violates structural
    invariants beyond Pydantic field-level checks.

    Catches:
      - duplicate section id
      - duplicate question id (across all sections)
      - empty section (no questions)

    Pydantic already enforces id pattern, max_followups bounds, ask/goal
    non-empty, ``extra="forbid"``; this function covers cross-field rules.
    """
    seen_section_ids: set[str] = set()
    seen_question_ids: set[str] = set()
    for section in outline.sections:
        if section.id in seen_section_ids:
            raise OutlineError(f"duplicate section id: {section.id!r}")
        seen_section_ids.add(section.id)
        if not section.questions:
            raise OutlineError(f"section {section.id!r} has no questions")
        for question in section.questions:
            if question.id in seen_question_ids:
                raise OutlineError(f"duplicate question id: {question.id!r}")
            seen_question_ids.add(question.id)


def flatten_questions(outline: Outline) -> list[tuple[Section, Question]]:
    """Return ``(section, question)`` pairs in traversal order.

    Engine cursor advance walks this flattened list.
    """
    return [(section, question) for section in outline.sections for question in section.questions]


def find_question(outline: Outline, question_id: str) -> tuple[Section, Question] | None:
    """Locate a question by id. Returns ``(section, question)`` or ``None``."""
    for section, question in flatten_questions(outline):
        if question.id == question_id:
            return section, question
    return None


__all__ = [
    "Outline",
    "OutlineError",
    "Question",
    "Section",
    "Turn",
    "find_question",
    "flatten_questions",
    "validate_outline",
]
